### ISSUE TITLE
Kokkos Kernels tests fail on A100 GPUs

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#1010]
@benc303 reports failures when running Trilinos tests of Kokkos Kernels on A100.
I am not sure where we can go to investigate that issue but I will look into that.

**Comment by srajama1** [comment]
Do we have a KOKKOS_ARCH for A100?

**Comment by benc303** [comment]
AMPERE80

**Comment by ndellingwood** [comment]
I think this should be resolved by PR #1118
