### ISSUE TITLE
Blake, Intel18, complex: blas trsm fails

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#1041]
Test ``serial.trsm_complex_double`` has been failing in the nightly Intel18 build on Blake.

**Comment by ndellingwood** [comment]
Duplicate of #559 , from that issue the guess was this could be related to a compiler issue with intel/18 but a workaround has not yet been proposed or submitted.

**Comment by brian-kelley** [comment]
Closed as duplicate
