### ISSUE TITLE
Test GMRES example with half_t

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos-kernels#1049]
Depends on https://github.com/kokkos/kokkos-kernels/pull/1028.

**Comment by e10harvey** [comment]
I will use the pending changes at https://github.com/kokkos/kokkos/pull/4156 for testing.

**Comment by e10harvey** [comment]
@jennloe: I update the gmres example to use half_t.

Building with [kokkos@half_t_fixes_for_belos_alignas2](https://github.com/e10harvey/kokkos/tree/half_t_fixes_for_belos_alignas2) and [kokkos-kernels@issue1049](https://github.com/e10harvey/kokkos-kernels/tree/issue1049) using all execution spaces (serial, openmp, and cuda) CGS2 is not converging; right off the bat I am seeing:
```
Shortcut relative residual for iteration 0 is: nan
```

Are there matrix sizes, limits, or tolerances in the GMRES example that must be modified to work with half precision?

**Comment by jennloe** [comment]
Hmmm.... I wouldn't be surprised if using half precision gave a loss of accuracy, but you shouldn't be seeing Nans in the residual right out of the gate.  
Which example code are you running?

I'll try to build this and debug on my own system.

**Comment by e10harvey** [comment]
> Which example code are you running?

`KokkosKernels_gmres_test_real_A`

**Comment by jennloe** [comment]
I've narrowed in on the issue: 
It seems that the problem occurs in gmres.hpp line 199 when we compute
`MT tmpNrm = KokkosBlas::nrm2(Wj);`
This is when we compute the norm of the newly added Krylov vector.  Apparently the norm of the first vector in our subspace is higher than what can be stored in half precision, and the variable is overflowing.  So `tmpNrm` gets a value of `inf` which later turns into `nan` after more attempted calculations.  

I have a few possible workarounds in mind.  I'll let you know if any work well.

**Comment by jennloe** [comment]
@e10harvey Can you make the MatrixMarket Reader work with half precision?  I'm curious to try this with some matrix market files as in the ex_real_A.cpp file.  Current error is: 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  scalar_t in read_mtx() incompatible with float or double typed MatrixMarket file.
```

**Comment by e10harvey** [comment]
@jennloe: This has been updated at [kokkos-kernels@issue1049](https://github.com/e10harvey/kokkos-kernels/tree/issue1049). I tried running the ex_real_A binary with these changes and see:
```
$ ./gmres_ex_real_A
File to process is: bcsstk09.mtx
Convergence tolerance is: 1e-10
Convergence tolerance is: 0.000000
Shortcut relative residual for iteration 0 is: nan
<snip>
```

**Comment by jennloe** [comment]
Hi @e10harvey,

I'm somewhat happy with the results of this.  I can read in a 2D Laplacian, and the solver iterates a few steps without any problems.  I'm now trying to print-debug some residual computations later in the file.  After the line that calls `KokkosBlas::trsm`, I added
```
        std::cout << "Printing GlsSoln vec: " << std::endl;
        for(int i = 0; i < m; i++){
          std::cout << GLsSoln_h(i) << std::endl;  //Build is failing at this line. 
        }   
        std::cout << std::endl;
```
And I get the following error:
```
/ascldap/users/jloe/Kokkos/Halft/kokkos-kernels/example/gmres/gmres.hpp(253): error: no instance of overloaded function "Kokkos::View<DataType, Properties...>::operator() [with DataType=Kokkos::Experimental::half_t **, Properties=<default_layout, Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>>]" matches the argument list
            argument types are: (int)
            object type is: Kokkos::View<Kokkos::Experimental::half_t **, default_layout, Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>>
          detected during instantiation of "GmresStats gmres(const KokkosSparse::CrsMatrix<ScalarType, OrdinalType, EXSP, void, Kokkos::ViewTraits<OrdinalType *, EXSP, void, void>::size_type> &, const Kokkos::View<ScalarType *, Layout, EXSP> &, Kokkos::View<ScalarType *, Layout, EXSP> &, Kokkos::Details::ArithTraits<ScalarType>::mag_type, int, int, std::__cxx11::string) [with ScalarType=Kokkos::Experimental::half_t, Layout=Kokkos::LayoutLeft, EXSP=Kokkos::Serial, OrdinalType=int]"
/ascldap/users/jloe/Kokkos/Halft/kokkos-kernels/example/gmres/ex_real_A.cpp(120): here
```

Can you fix this so I can run the print debugging?  Or did I mess up something on my end?

**Comment by e10harvey** [comment]
@jennloe: I've run into this before. Since `GLsSoln_h` is a 2-rank view (even though the rightmost dimension is 1), you can solve this build error a few different ways:
1. Use the available () operator overload via:
`GLsSoln_h(i,0)`
2. Use the underlying data pointer via:
`GLsSoln_h.data()[i]`
3. Change `GLsSoln` to a 1-rank view and then use `GLsSoln_h(i)`:
`ViewMatrixType GLsSoln("GLsSoln",m)`

**Comment by jennloe** [comment]
Hi @e10harvey, this code is all running fine for me.  ('Fine' as in there aren't any actual problems with the function calls.)  I think a certain amount of NaN's are to be expected when running the entire GMRES iterations in half precision.  I think it will be best for me to wrap the GMRES half precision code in an iterative refinement loop.  In any case, I think the necessary changes on your end are finished for now.  I would be fine if you mark this 'done' and/or go ahead and push those additional half precision fixes.  Thanks for working on this!
