### ISSUE TITLE
BlockCrsMatrix coordinate-based constructor uses wrong dimensions

### ISSUE THREAD

**Issue by uhetmaniuk** [kokkos/kokkos-kernels#1051]
- The [dimension](https://github.com/kokkos/kokkos-kernels/blob/5462e7332c5df093fc89e8ca6cacc60f30c74d68/src/sparse/KokkosSparse_BlockCrsMatrix.hpp#L923) is not right.  
- The [constructor implementation](https://github.com/kokkos/kokkos-kernels/blob/5462e7332c5df093fc89e8ca6cacc60f30c74d68/src/sparse/KokkosSparse_BlockCrsMatrix.hpp#L908) does not use the block size.

**Comment by uhetmaniuk** [comment]
@cwpearson  I do not know how to add you as an assignee.

**Comment by ndellingwood** [comment]
I think BlockCrsMatrix was deprecated and removed in favor of BSR, so this can be closed. Please reopen if necessary
