### ISSUE TITLE
Build kokkos

### ISSUE THREAD

**Issue by YuxinxinChen** [kokkos/kokkos-kernels#1055]
Hi,

I am trying to use graph coloring (GPU) in kokkos. However, I have a problem config the cmake.
```
mkdir build & cd build
cmake .. -DCMAKE_CXX_COMPILER=g++ -DKokkos_ROOT=/home/yuxin420/kokkos/kokkos/build -DCMAKE_INSTALL_PREFIX=/home/yuxin420/kokkos/kokkos-kernels/build -DKokkosKernels_REQUIRE_DEVICES=CUDA
```
But I got an error:
```
CMake Error at /home/yuxin420/kokkos/kokkos/build/KokkosConfig.cmake:62 (INCLUDE):
  INCLUDE could not find load file:

    /home/yuxin420/kokkos/kokkos/build/KokkosTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:88 (FIND_PACKAGE)
```
Could you give more information on how to build Kokkos-kernel? Thanks

Yuxin

**Comment by jennloe** [comment]
Hi Yuxin, 
Make sure you have run "make install" for your Kokks build.  Then the -DKokkos_ROOT value should point to the Kokkos install location, probably "-DKokkos_ROOT=/home/yuxin420/kokkos/kokkos/install".

Does that fix the problem?

**Comment by YuxinxinChen** [comment]
Hi,

Thanks for your reply! I realized Kokkos is different from Kokkos kernel. I have installed kokkos and kokkos-kernel successfully.
I would like to run the GPU graph coloring and I noticed there is one under the `perf_test` directory. However, after `make install` kokkos-kernel, the tests under `perf_test` directory are not compiled and the CMakeList.txt under `perf_test` can not be run directly. 
I would like to know how can I compile the perf_test code and run it. Could you help me with that? 
Thanks very much!

-Yuxin

**Comment by lucbv** [comment]
@YuxinxinChen based on issue #1056 it seems that you are now able to compile Kokkos Kernels correctly.
I will close this issue and leave the other one open so you get answers on how to enable tests in one place.
