### ISSUE TITLE
Not clear how to install without Trilinos

### ISSUE THREAD

**Issue by mfdeakin-sandia** [kokkos/kokkos-kernels#106]
It's not clear what the preferred method of using kokkos-kernels is from the readme. Is the entire repository meant to be snapshot into other projects, as the snapshot.py script does?
I'd prefer to rely on an external installation of this repo (and need to be able to do so without Trilinos), as carrying around the whole thing seems like overkill. Is this possible?

**Comment by crtrott** [comment]
Yes that is possible. If you use GNU Make it is pretty straight forward. The CMake integration is not yet done, but you could simply add include paths and libraries to your CMake flags manually. 

Basically you use the scripts/generate_makefile.bash file to compile and install KokkosKernels, and if you look in the install directory there is a Makefile.kokkos-kernels. Including that in your Makefile allows you to use its Make variables which set the include paths, link paths and libraries. 

Does that make sense?

**Comment by mfdeakin-sandia** [comment]
I had done that, but got the following error:
```make[2]: /ascldap/users/mdeakin/prefix/core/src/Makefile: No such file or directory```
which looks like it's expecting me to pass in the path to the kokkos repository, rather than my installation of it, which seems wrong to me, hence my confusion

**Comment by jjwilke** [comment]
This has been superseded by the new CMake system. Instructions are both in the repo and on the wiki.
