### ISSUE TITLE
Very Slow GEMV performance for Kokkos::Experimental::half_t

### ISSUE THREAD

**Issue by jennloe** [kokkos/kokkos-kernels#1081]
I am observing very slow GEMV performance (`twoLevel` kernel) using scalar type half_t in Kokkos Kernels.  
This is likely the cause of the slowdown reported in #1075. 

These timings are from A*x where A is about 1 million by 10 and x is 10 by 1.  (But I suspect similar bad performance occurs also with smaller sizes.)

From Kokkos SimpleKernelTimer:

```
- KokkosBlas::gemv[noETI]
 (REGION)   151.656376 82 1.849468 99.994307 83.840793
Kernels: 
 
- KokkosBlas::gemv[twoLevel]
 (ParFor)   151.463312 42 3.606269 99.867011 83.734060
- KokkosBlas::gemv[twoLevelTranspose]
 (ParFor)   0.191844 40 0.004796 0.126492 0.106058
```
From NVProf:
```
==139911== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   99.86%  151.449s        42  3.60592s  1.09123s  5.85614s  __nv_static_61__48_tmpxft_00022087_00000000_6_test_half_gIR_cpp1_ii_3e75a74a__ZN6Kokkos4Impl33cuda_parallel_launch_local_memoryINS0_11ParallelForIN10KokkosBlas4Impl12TwoLevelGEMVINS_4ViewIPPKNS_12Experimental6half_tEJNS_10LayoutLeftENS_6DeviceINS_4CudaENS_9CudaSpaceEEENS_12MemoryTraitsILj1EEEEEENS6_ISA_JSC_SG_SI_EEENS6_IPS8_JSC_SG_SI_EEEjEENS_10TeamPolicyIJSE_NS4_26TwoLevelGEMV_LayoutLeftTagEEEESE_EEEEvT_
```

For comparison, running the same code in float precision takes a fraction of that time:
```
- KokkosBlas::gemv[TPL_CUBLAS,float]
 (REGION)   0.006562 82 0.000080 68.477882 0.020084

**Comment by srajama1** [comment]
Can you check the input parameters (transpose option) and alpha and beta values. It will help determine which one of the branches in this routine is taken
https://github.com/kokkos/kokkos-kernels/blob/fe439b2100bfd1a8913f66506bfe14ce94552237/src/blas/impl/KokkosBlas2_gemv_impl.hpp#L565

**Comment by jennloe** [comment]
Looks like the only code path which matches the profiler line `KokkosBlas::gemv[twoLevel]` is at line 789: 
https://github.com/kokkos/kokkos-kernels/blob/c151fbb6572eeac5c113dc83903e4402693025b6/src/blas/impl/KokkosBlas2_gemv_impl.hpp#L789

**Comment by jennloe** [comment]
No transpose.  We should be in the "LayoutLeft" case.  alpha and beta are -1 and +1.

**Comment by jennloe** [comment]
> 
> These timings are from A*x where A is about 1 million by 10 and x is 10 by 1. (But I suspect similar bad performance occurs also with smaller sizes.)

I'm observing that things get even slower as the length of x increases.  So A 1M by 10 and x 10 by 1 is noticeably faster than, say, A 1M by 50 and x 50 by 1.

**Comment by jennloe** [comment]
Using 'print' to understand the parameters set in https://github.com/kokkos/kokkos-kernels/blob/c151fbb6572eeac5c113dc83903e4402693025b6/src/blas/impl/KokkosBlas2_gemv_impl.hpp#L771-L782

I have (for A is 1 million by k, vec is k by 1, k runs from 1 to 10): 
```
sharedPerTeam is: 64  (always)
numTeams is: 32 (always)
teamSize is 32*k (after being adjusted in line 779)
numBlocks is k
functor.columnsPerThread is: 1
```

**Comment by srajama1** [comment]
Quick check this seems like a problem. Just 32 teams always? That seems like a problem. A.extent(0) should be 1 million, right? Looks like that is the problem.

**Comment by brian-kelley** [comment]
@srajama1 @jennloe Christian explained that atomics with half_t are implemented with lock tables, so that explains the slowness. I fixed it locally by doing the accumulation in float instead (which is good for accuracy anyway), and it's back up to 140 gflops for 1M x 10, which is about like the performance for float. I'll open a PR to do this.

It doesn't use 32 teams, it uses A.extent(0), rounded up to a multiple of 32. However, it hardcodes the row block length to 32 which I suspect is why it's slow on AMD (it should be 64 in that case).

**Comment by srajama1** [comment]
ok, thanks, @brian-kelley ! I thought there was a bug in A.extent code that numTeams is 32 always comment from @jennloe

**Comment by brian-kelley** [comment]
Fix is ready in #1082.

**Comment by crtrott** [comment]
We will add half precision atomics independently. Note that half precision atomic support is limited in the hardware, for example only add is there I think like with FP64. Also half precision atomic throughput from my experiments is about half that of float and double. I.e. its slower to do atomics with half than with float.

**Comment by brian-kelley** [comment]
@jennloe The fix has been merged into develop, so let me know if there are still issues with half.

Yesterday I started looking at the MI100 performance relative to V100 - would you mind creating an issue with the information you sent Siva and me on email? Just to keep track of things.

**Comment by jennloe** [comment]
@brian-kelley Will do!  Thanks!

**Comment by e10harvey** [comment]
Thanks all. We are still iterating on the implementation of the half_t volatile operators, which currently use atomics.

**Comment by jennloe** [comment]
This is MUCH improved after PR #1082. Thanks!

**Comment by e10harvey** [comment]
Note that with the merge of https://github.com/kokkos/kokkos/pull/4156, we do not see poor GEMV performance on V100 when using half_t as the accumulator type. For details, see https://github.com/kokkos/kokkos-kernels/issues/1075#issuecomment-929502048.
