### ISSUE TITLE
Not clear how to build outer product spgemm

### ISSUE THREAD

**Issue by ajain324** [kokkos/kokkos-kernels#109]
It is not clear how to build the spgemm kernel using the outer multi memory option. The "src/sparse/impl/KokkosSparse_spgemm_impl.hpp" has an "ifdef KOKKOSKERNELS_HAVE_OUTER" snippet for compiling the multi-memory outer matrix spgemm code (The implementation files also have the same ifdef without which using this algorithm results in an exception). However I could not find where this macro is defined.
It seems that I am missing something. Can you please suggest how I can compile the outer multi memory spgemm code or where I should define the macro so that an extension to the unit tests using the outer multimem spgemm works?

**Comment by mndevec** [comment]
@ajain324 

That is an experimental research code that I am working on, and not supporting it publicly. 
That is why the compilation is not enabled, and probably break if you simply add the flags. 

Why are you specifically interested in this method?
