### ISSUE TITLE
CrsMatrix: sumIntoValues and replaceValues incorrectly count the number of valid column indices.

### ISSUE THREAD

**Issue by vbrunini** [kokkos/kokkos-kernels#11]
I believe in both cases the ++numValid; line needs to be within the if(offset != length) branch, right now it is executed unconditionally.

**Comment by aprokop** [comment]
Looking at older Tpetra implementation, this is the case. Both it and hint are inside the `if (offset != length)` branch.

**Comment by mhoemmen** [comment]
@vbrunini oops!  sorry about that :-)

**Comment by crtrott** [comment]
Mark did you fix this?

**Comment by mhoemmen** [comment]
@crtrott Not yet; too many things on my plate.

**Comment by crtrott** [comment]
Is this actually fixed?

**Comment by mhoemmen** [comment]
@crtrott No.  I can take it if you haven't started yet.

**Comment by mhoemmen** [comment]
I'm on it.

**Comment by mhoemmen** [comment]
@mndevec I submitted a PR, #88.  Please review; thanks!  It's ready to merge if you approve.

**Comment by mhoemmen** [comment]
@mndevec FYI I tested the PR through Trilinos already.

**Comment by crtrott** [comment]
Did you test with CUDA?

**Comment by mhoemmen** [comment]
@crtrott wrote:
> Did you test with CUDA?

Yes, at least Tpetra.  There are some Stokhos tests that were failing before for me; this is not relevant to that.  Thanks!
