### ISSUE TITLE
Build examples failed

### ISSUE THREAD

**Issue by Fyz01** [kokkos/kokkos-kernels#1103]
Hello，I want to build examples，I used 

> cmake .. -DKokkos_ROOT=/home/fangyz/kokkos-install -DCMAKE_CXX_COMPILER=g++ -DKokkosKernels_ENABLE_EXAMPLES=ON

error information：

> CMake Error at cmake/kokkoskernels_tribits.cmake:158 (TARGET_LINK_LIBRARIES):
  Error evaluating generator expression:

    $<LINK_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  test_common/CMakeLists.txt:5 (KOKKOSKERNELS_ADD_EXECUTABLE)

I don't know much about CMake...

**Comment by lucbv** [comment]
@Fyz01 we are answer roughly the same question in issue #1104 please look there and see if it helps?
