### ISSUE TITLE
How can I run example just use OpenMP？

### ISSUE THREAD

**Issue by Fyz01** [kokkos/kokkos-kernels#1105]
I want to run example use OpenMP, I have set **Kokkos_ENABLE_CUDA=OFF**.
When I build kokkos-kernels, **make** was successful,  **make install** failed. 
Could you tell me what should I do?

**Comment by lucbv** [comment]
Well you you `Kokkos_ENABLE_OPENMP:BOOL=ON` for OpenMP.
Can you post what error you see from make install?

**Comment by Fyz01** [comment]
> Well you you `Kokkos_ENABLE_OPENMP:BOOL=ON` for OpenMP.
> Can you post what error you see from make install?

Yes, I have set Kokkos_ENABLE_OPENMP=ON.
Error just like this:
/home/fangyz/kokkos-install/lib/libkokkoscore.a(Kokkos_Profiling.cpp.o): In function `__sti____cudaRegisterAll()':
tmpxft_00007a6b_00000000-5_Kokkos_Profiling.cudafe1.cpp:(.text.startup+0xc): undefined reference to `__cudaRegisterFatBinary'
tmpxft_00007a6b_00000000-5_Kokkos_Profiling.cudafe1.cpp:(.text.startup+0x1b): undefined reference to `__cudaRegisterFatBinaryEnd'
/home/fangyz/kokkos-install/lib/libkokkoscore.a(Kokkos_SharedAlloc.cpp.o): In function `__cudaUnregisterBinaryUtil()':
tmpxft_00007a68_00000000-5_Kokkos_SharedAlloc.cudafe1.cpp:(.text+0x8): undefined reference to `__cudaUnregisterFatBinary'
/home/fangyz/kokkos-install/lib/libkokkoscore.a(Kokkos_SharedAlloc.cpp.o): In function `__sti____cudaRegisterAll()':
tmpxft_00007a68_00000000-5_Kokkos_SharedAlloc.cudafe1.cpp:(.text.startup+0xc): undefined reference to `__cudaRegisterFatBinary'
tmpxft_00007a68_00000000-5_Kokkos_SharedAlloc.cudafe1.cpp:(.text.startup+0x1b): undefined reference to `__cudaRegisterFatBinaryEnd'
/home/fangyz/kokkos-install/lib/libkokkoscore.a(Kokkos_OpenMP_Exec.cpp.o): In function `__cudaUnregisterBinaryUtil()':
tmpxft_00007a95_00000000-5_Kokkos_OpenMP_Exec.cudafe1.cpp:(.text+0x298): undefined reference to `__cudaUnregisterFatBinary'
/home/fangyz/kokkos-install/lib/libkokkoscore.a(Kokkos_OpenMP_Exec.cpp.o): In function `__sti____cudaRegisterAll()':
tmpxft_00007a95_00000000-5_Kokkos_OpenMP_Exec.cudafe1.cpp:(.text.startup+0xc): undefined reference to `__cudaRegisterFatBinary'
tmpxft_00007a95_00000000-5_Kokkos_OpenMP_Exec.cudafe1.cpp:(.text.startup+0x1b): undefined reference to `__cudaRegisterFatBinaryEnd'
/home/fangyz/kokkos-install/lib/libkokkoscore.a(Kokkos_CPUDiscovery.cpp.o): In function `__cudaUnregisterBinaryUtil()':
tmpxft_00007a6e_00000000-5_Kokkos_CPUDiscovery.cudafe1.cpp:(.text+0x8): undefined reference to `__cudaUnregisterFatBinary'
/home/fangyz/kokkos-install/lib/libkokkoscore.a(Kokkos_CPUDiscovery.cpp.o): In function `__sti____cudaRegisterAll()':
tmpxft_00007a6e_00000000-5_Kokkos_CPUDiscovery.cudafe1.cpp:(.text.startup+0xc): undefined reference to `__cudaRegisterFatBinary'
tmpxft_00007a6e_00000000-5_Kokkos_CPUDiscovery.cudafe1.cpp:(.text.startup+0x1b): undefined reference to `__cudaRegisterFatBinaryEnd'
/home/fangyz/kokkos-install/lib/libkokkoscore.a(Kokkos_hwloc.cpp.o): In function `__cudaUnregisterBinaryUtil()':
tmpxft_00007a7c_00000000-5_Kokkos_hwloc.cudafe1.cpp:(.text+0x8): undefined reference to `__cudaUnregisterFatBinary'
/home/fangyz/kokkos-install/lib/libkokkoscore.a(Kokkos_hwloc.cpp.o): In function `__sti____cudaRegisterAll()':
tmpxft_00007a7c_00000000-5_Kokkos_hwloc.cudafe1.cpp:(.text.startup+0xc): undefined reference to `__cudaRegisterFatBinary'
tmpxft_00007a7c_00000000-5_Kokkos_hwloc.cudafe1.cpp:(.text.startup+0x1b): undefined reference to `__cudaRegisterFatBinaryEnd'
collect2: error: ld returned 1 exit status
unit_test/CMakeFiles/KokkosKernels_sparse_openmp.dir/build.make:302: recipe for target 'unit_test/KokkosKernels_sparse_openmp' failed
make[2]: *** [unit_test/KokkosKernels_sparse_openmp] Error 1
CMakeFiles/Makefile2:1981: recipe for target 'unit_test/CMakeFiles/KokkosKernels_sparse_openmp.dir/all' failed
make[1]: *** [unit_test/CMakeFiles/KokkosKernels_sparse_openmp.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lucbv** [comment]
It does look like you are compiling with CUDA on, I would delete all files in the build directory and reconfigure/rebuild Kokkos and Kokkos Kernels.

**Comment by Fyz01** [comment]
> It does look like you are compiling with CUDA on, I would delete all files in the build directory and reconfigure/rebuild Kokkos and Kokkos Kernels.

I have just rebuild Kokkos and Kokkos Kernels, but it doesn't work. 
When I build Kokkos, I use:
> cmake \
> -DCMAKE_CXX_COMPILER=nvcc_wrapper \
> -DCMAKE_INSTALL_PREFIX=../../kokkos-install \
> -DKokkos_ENABLE_CUDA=OFF \
> -DKokkos_ENABLE_OPENMP=ON \
> -DKokkos_ENABLE_SERIAL=ON \
> -DKokkos_ENABLE_EXAMPLES=ON \
> -DCMAKE_VERBOSE_MAKEFILE=ON \
> -DCMAKE_CXX_EXTENSIONS=OFF \
> -DCMAKE_BUILD_TYPE=Release \
> ..
 When I build Kokkos Kernels, I use:
> cmake .. -DKokkos_DIR=/home/fangyz/kokkos-install/lib/cmake/Kokkos -DCMAKE_INSTALL_PREFIX=home/fangyz/kokkos-kernels-install -DKokkosKernels_ENABLE_EXAMPLES=ON

Do you think there is something wrong with it?

**Comment by lucbv** [comment]
If you are building with `-D Kokkos_ENABLE_CUDA=OFF` then you should not use `-D. CMAKE_CXX_COMPIER=nvcc_wrapper` instead just set that variable to the compiler you want to use, maybe `g++`, `clang++` or `icpc`

**Comment by Fyz01** [comment]
> If you are building with `-D Kokkos_ENABLE_CUDA=OFF` then you should not use `-D. CMAKE_CXX_COMPIER=nvcc_wrapper` instead just set that variable to the compiler you want to use, maybe `g++`, `clang++` or `icpc`

Thank you very much ! I used CMAKE_CXX_COMPIER=g++, and make install successfully.
