### ISSUE TITLE
Build fail 

### ISSUE THREAD

**Issue by AbandiGa** [kokkos/kokkos-kernels#1108]
Hello,

I'm trying to build kokkos kernels but I got this error. 
"
**cmake -D CMAKE_CXX_COMPILER:STRING="g++" \
    -D CMAKE_CXX_STANDARD:STRING="14" \
    -D Kokkos_DIR:PATH="home/kokkos-install/lib/cmake/kokkos" \
    -D KokkosKernels_ENABLE_TESTS:BOOL=ON \
    -D KokkosKernels_ENABLE_EXAMPLES:BOOL=ON \
    /home/kokkos-kernels
-- Setting policy CMP0074 to use <Package>_ROOT variables
-- The project name is: KokkosKernels
CMake Error at CMakeLists.txt:88 (FIND_PACKAGE):
  By not providing "FindKokkos.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Kokkos", but
  CMake did not find one.

  Could not find a package configuration file provided by "Kokkos" with any
  of the following names:

    KokkosConfig.cmake
    kokkos-config.cmake

  Add the installation prefix of "Kokkos" to CMAKE_PREFIX_PATH or set
  "Kokkos_DIR" to a directory containing one of the above files.  If "Kokkos"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/kokkos-kernels/build/CMakeFiles/CMakeOutput.log".**
"
Also, Can I build kokkos and kokkos kernels for OpenMP and CUDA in the same build and install directory? Cause I tried to do so and I got an error. 

Thank you

**Comment by lucbv** [comment]
First you can build Kokkos with both OpenMP and CUDA backends enabled so no need to build that twice.
I would recommend that you build and install Kokkos and Kokkos Kernels in two separate directories as there is no guarantee that build system files are named differently in each library.

Then regarding you build error, it just seems that you did not set `-D Kokkos_DIR="/path/to/kokkos/install"` correctly to CMake. So I would suggest adding that, sometimes you need to point CMake directly at the directory that contains `KokkosConfig.cmake` and `kokkos-config.cmake`, the locations of these files might be `/path/to/kokkos/install/lib64/cmake/Kokkos` or `/path/to/kokkos/install/lib/cmake/Kokkos`

**Comment by AbandiGa** [comment]
>First you can build Kokkos with both OpenMP and CUDA backends enabled so no need to build that twice.
Thank you I enabled both and it worked fine.

> /path/to/kokkos/install/lib64/cmake/Kokkos 

I was able to build kokkos-kernel using this path.

Thank you for the help.
