### ISSUE TITLE
Inconsistent flag for IFDEF in `KokkosSparse_spmv.hpp`

### ISSUE THREAD

**Issue by uhetmaniuk** [kokkos/kokkos-kernels#1148]
The line https://github.com/kokkos/kokkos-kernels/blob/f631acbf0673b45b2fa802cf9d015a9d1d6ec34f/src/sparse/KokkosSparse_spmv.hpp#L274

should use `KOKKOSKERNELS_INST_LAYOUTRIGHT`

**Comment by lucbv** [comment]
This is not fixed by PR #1151
