### ISSUE TITLE
Replace lamdas with functor in unit test

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#116]
Replace lambdas with functors in the unit test Test_Sparse_spmv.hpp until lambda support required by KokkosKernels.

**Comment by ndellingwood** [comment]
PR #115 issued for this.

**Comment by ndellingwood** [comment]
Ran into issues testing this PR. Building kokkos-kernels with Cuda (cuda 8 + gcc5.4) or OpenMP (gcc5.4) resulted in all tests building and passing. 

Building with Cuda AND OpenMP resulted in many OpenMP test failures on both the PR branch and the develop branch. 
```
[----------] 204 tests from openmp (38529 ms total)
 
[----------] Global test environment tear-down
[==========] 204 tests from 1 test case ran. (38530 ms total)
[  PASSED  ] 67 tests.
[  FAILED  ] 137 tests, listed below:
```

**Comment by ndellingwood** [comment]
With @mndevec we tried replacing occurrences of `Kokkos::fence()` with `DeviceType::execution_space::fence()` which fixed the failing tests for that file (tested with `unit_test/batched/Test_Batched_SerialGemm.hpp`). 

Potential issue with `Kokkos::fence()`? @crtrott

**Comment by ndellingwood** [comment]
From @ibaned - 

> The real problem is this: “device-side assert triggered”.
> A CUDA kernel ran and hit an assert inside its code, and the next call to fence is when this is realized.
> You should run the failing test under cuda-memcheck or cuda-gdb to find out which kernel the assert happens in.
> My guess is that during OpenMP testing, something was not properly templated on execution space and runs on CUDA instead

Running check through cuda-gdb confirms a discrepancy between spaces, for example a View templated on OpenMP memory space, passed to a parallel_reduce with the execution space of the RangePolicy as Cuda (likely defaulted). Opening up a new issue.

**Comment by ndellingwood** [comment]
@mndevec pushed fix to the PR for test issues mentioned above. Tests now pass when Cuda+OpenMP enabled.

**Comment by srajama1** [comment]
@ndellingwood @mndevec : Thanks for the quick turn around.
