### ISSUE TITLE
Feature request: utilities to convert sparse matrix formats

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos-kernels#1164]
Basically, this would be portable versions of cusparse's Csr2cscEx2() or coo2csr(). This would be very helpful for complicated algorithms that requires fine grained manipulation of the matrix between kernel calls.

**Comment by srajama1** [comment]
@Char-Aznable  This is not too hard to do, we can prioritize it among other things you are working on. In case, you happen to write one one of this do not hesitate to post a PR.

**Comment by e10harvey** [comment]
@Char-Aznable: What formats do you require converting between? Just CSR <-> CSC and COO <-> CSR?

**Comment by Char-Aznable** [comment]
Yes, CSR <-> CSC and COO <-> CSR. If this is not asking too much, it would be almost trivial to add CSC<->COO given CSR<->COO because it would be just a one liner of swapping the COO's i and j index arrays.

**Comment by e10harvey** [comment]
@srajama1: Shall I close this as complete?

**Comment by e10harvey** [comment]
coo2ccs was not implemented but can be achieved via ccs2crs, coo2crs, crs2ccs.

**Comment by e10harvey** [comment]
Closing as complete.
