### ISSUE TITLE
Test failures when enabling Cuda and OpenMP

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#117]
On the develop branch many OpenMP test failures when enabling both Cuda and OpenMP (cuda 8 + gcc 5.4).

Test failure all have same message:
```
unknown file: Failure
C++ exception with description "cudaDeviceSynchronize() error( cudaErrorAssert): device-side assert triggered /ascldap/users/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119
Traceback functionality not available
" thrown in the test body.
```

Running tests through cuda-gdb showed that in some of these failing tests there is mismatch of the execution/memory space between Views (e.g. OpenMP) and the RangePolicy's execution space for the parallel_* (e.g. Cuda) they are passed to.

**Comment by ndellingwood** [comment]
List of failing tests attached
[OpenMP_Errors.txt](https://github.com/kokkos/kokkos-kernels/files/1459515/OpenMP_Errors.txt)

**Comment by srajama1** [comment]
Both Sparse and batch tests fail.

**Comment by mndevec** [comment]
We fixed this. Actually it was only spmv tests that was failing, any call to Kokkos::fence() after this test is executed was reporting the previous failures.
