### ISSUE TITLE
using namespace KokkosBatched.hpp causes build errors in application codes

### ISSUE THREAD

**Issue by jfike** [kokkos/kokkos-kernels#1170]
We are currently seeing build errors with the latest version of kokkos in Trilinos. Specifically, `error: reference to 'Vector' is ambiguous` due to KokkosBatched::Vector. I've also heard of at least one other application code with similar build errors.

I found three spots in kokkos-kernels with `using namespace KokkosBatched.hpp`. Specifically, KokkosBlas3_trsm_impl, KokkosBlas3_trmm_impl, and KokkosBlas_trtri_impl. I removed the `using namespace` lines and fixed the calls in those files.

This allowed our application code to build without any errors.

**Comment by srajama1** [comment]
@jfike Sorry about this! I don't think this is new code, I have to check. We will fix it in Trilinos and develop here. 

@ndellingwood

**Comment by lucbv** [comment]
I am working on this now, will update after giving this a careful look.

**Comment by lucbv** [comment]
@jfike PR #1171 should have taken care of this issue, thanks for reporting it to us.

**Comment by jfike** [comment]
Thank you.  I'll keep an eye out for when it gets merged into Trilinos.
