### ISSUE TITLE
clang Not Found Error?

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos-kernels#119]
Seeing this when trying to use a non-standard named LLVM compiler. I am specifying the compiler with the `--compiler=..` option.

```
/bin/sh: clang: command not found
mkdir -p /home/sdhammo/git/kokkos-kernels-github-repo/build/kokkos/install
mkdir -p /home/sdhammo/git/kokkos-kernels-github-repo/build/kokkos/install/bin
mkdir -p /home/sdhammo/git/kokkos-kernels-github-repo/build/kokkos/install/include
```

**Comment by ndellingwood** [comment]
@nmhamster I've testing `--compiler=clang++` with clang/3.9 and the generate_makefile script works for me now. I'm going to close this issue, please reopen though if there are still problems on your end.
