### ISSUE TITLE
spgemm_symbolic consumes as much memory as dense gemm

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos-kernels#1191]
Consider this code:
```c++
#include <iostream>
#include <string>
#include <Kokkos_Core.hpp>
#include <Kokkos_Random.hpp>
#include <KokkosKernels_Sorting.hpp>
#include <KokkosSparse_CrsMatrix.hpp>
#include <KokkosSparse_spgemm.hpp>

using ExecutionSpace = Kokkos::DefaultExecutionSpace;
using MemorySpace = ExecutionSpace::memory_space;
using Device = Kokkos::Device<ExecutionSpace,MemorySpace>;
using ScratchSpace = ExecutionSpace::scratch_memory_space;
using ScratchDevice = Kokkos::Device<ExecutionSpace, ScratchSpace>;
using HostExecutionSpace = Kokkos::DefaultHostExecutionSpace;
using HostMemorySpace = HostExecutionSpace::memory_space;
using HostDevice = Kokkos::Device<HostExecutionSpace, HostMemorySpace>;

using M = typename KokkosSparse::CrsMatrix<float, int, Device>;
using RowMap = typename M::row_map_type::non_const_type;
using ColIdx = typename M::index_type;
using Values  = typename M::values_type;

using O = typename RowMap::value_type;
using I = typename ColIdx::value_type;
using V = typename Values::value_type;

using KernelHandle = KokkosKernels::Experimental::KokkosKernelsHandle<
  O, I, V, ExecutionSpace, MemorySpace, MemorySpace>;

using UnmanagedTrait = Kokkos::MemoryTraits<Kokkos::Unmanaged>;

template < class T > using ScratchView = Kokkos::View<T, ScratchDevice, UnmanagedTrait>;

template < class I = int, class ... Ts >
KokkosSparse::CrsMatrix<
  typename Kokkos::View<Ts...>::value_type,
  I,
  typename Kokkos::View<Ts...>::device_type,
  typename Kokkos::View<Ts...>::memory_traits,
  typename Kokkos::View<Ts...>::size_type>
dense2CrsMatrix(const Kokkos::View<Ts...>& v, const bool sortColIdx = true) {
  using View = std::decay_t<decltype(v)>;
  static_assert(View::rank == 2, "dense2CrsMatrix: input view is not 2-dimensional");
  using V = typename View::value_type;
  using Device = typename View::device_type;
  using E = typename Device::execution_space;
  using O = typename View::size_type;
  using MemoryTraits = typename View::memory_traits;
  using M = KokkosSparse::CrsMatrix<V, I, Device, MemoryTraits, O>;
  using Policy = Kokkos::TeamPolicy<E, Kokkos::Schedule<Kokkos::Dynamic>, I>; 
  using Team = typename Policy::member_type;
  using SM = typename E::scratch_memory_space;
  using SD = Kokkos::Device<E, SM>;
  using ScratchViewCounts = Kokkos::View<O, SD, Kokkos::MemoryTraits<Kokkos::Unmanaged>>;
  const I nRows = v.extent(0);
  const I nCols = v.extent(1);
  Kokkos::View<O*, Device> rowMap("rowMap", nRows + 1);
  //Count nnz for each row
  Policy policyNNZ(static_cast<int>(nRows), Kokkos::AUTO, Kokkos::AUTO);
  Kokkos::parallel_for(policyNNZ, KOKKOS_LAMBDA (const Team& team) {
    const auto iRow = team.league_rank();
    Kokkos::parallel_reduce(Kokkos::TeamVectorRange(team, nCols),
      [&] (const auto jCol, O& update) {
      if(v(iRow, jCol) != V{0}) { update += 1; }
    }, rowMap(iRow + 1));
  });
  O nnz;
  Kokkos::parallel_scan("scanRowMap",
    Kokkos::RangePolicy<E, I>{E{}, I{1}, nRows + 1},
    KOKKOS_LAMBDA (const I iRow, O& update, const bool isFinal) {
    update += rowMap(iRow);
    if(isFinal) {
      rowMap(iRow) = update;
    }
  }, nnz);
  Kokkos::View<I*, Device> colIdx("colIdx", nnz);
  Kokkos::View<V*, Device> values("values", nnz);

  Policy policyValues = Policy{static_cast<int>(nRows), Kokkos::AUTO, Kokkos::AUTO}.
    set_scratch_size(0, Kokkos::PerTeam(ScratchViewCounts::shmem_size()));
  Kokkos::parallel_for(policyValues, KOKKOS_LAMBDA (const Team& team) {
    const auto iRow = team.league_rank();
    ScratchViewCounts iNNZ(team.team_scratch(0));
    Kokkos::single(Kokkos::PerTeam(team), [&] () { iNNZ() = rowMap(iRow); });
    team.team_barrier();
    Kokkos::parallel_for(Kokkos::TeamVectorRange(team, nCols),
      [&] (const auto jCol) {
      if(v(iRow, jCol) != V{0}) {
        const auto idx = Kokkos::atomic_fetch_add(&iNNZ(), 1);
        values(idx) = v(iRow, jCol);
        colIdx(idx) = jCol;
      }
    });
  });
  M ans{"dense2CrsMatrix", nRows, nCols, nnz, values, rowMap, colIdx};
  if(sortColIdx) {
    KokkosKernels::sort_crs_matrix(ans);
  }
  return ans;

}

M randomCrsMatrix(const I nRows, const I nCols, const float fractionNNZ,
  Kokkos::Random_XorShift64_Pool<Device>& rndPool) {
  Kokkos::View<V**, Device> mDense("mDense", nRows, nCols);
  Kokkos::parallel_for("randomCrsMatrix::randomDense",
    Kokkos::MDRangePolicy<ExecutionSpace, Kokkos::Rank<2>, int>(
      {0, 0}, {mDense.extent_int(0), mDense.extent_int(1)}),
    KOKKOS_LAMBDA (const int iRow, const int jCol) {
    auto rndEngine = rndPool.get_state();
    if(rndEngine.drand() <= fractionNNZ) {
      mDense(iRow, jCol) = rndEngine.drand();
    }
    rndPool.free_state(rndEngine);
  });
  return dense2CrsMatrix(mDense);
}

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  const I nRows = 1024;
  const I nCtr = nRows - 1;
  const I nCols = nCtr * 500;
  const float fracitonNNZ = 0.05;
  Kokkos::Random_XorShift64_Pool<Device> rndPool(823982);
  auto m = randomCrsMatrix(nRows, nCtr, fracitonNNZ, rndPool);
  auto n = randomCrsMatrix(nCtr, nCols, fracitonNNZ, rndPool);

  KernelHandle kh;
  kh.set_dynamic_scheduling(true);
  std::string ags("SPGEMM_KK_DENSE");
  KokkosSparse::SPGEMMAlgorithm spgemm_algorithm{
    KokkosSparse::StringToSPGEMMAlgorithm(ags)};
  kh.create_spgemm_handle(spgemm_algorithm);

  M c;
  KokkosSparse::spgemm_symbolic(kh, m, false, n, false, c);
  KokkosSparse::spgemm_numeric(kh, m, false, n, false, c);

  std::cout << "Result: " << c.numRows() << " x " << c.numCols() << " with " << c.nnz() << " elements\n";

  } Kokkos::finalize(); }
```
Gperftools show the spgemm_symbolic() call consumes about 3.8GB of memory with the input size of about 200MB:
[testSPGEMM.hprof.0005.pdf](https://github.com/kokkos/kokkos-kernels/files/7530431/testSPGEMM.hprof.0005.pdf)

This is on OpenMP backend and I tried setting OMP_NUM_THREADS=1 and redo the profiling but it doesn't make a difference

**Comment by Char-Aznable** [comment]
Note the dense version of the input and output matrices sum to about 3.9 GB, which is roughly the same as the spgemm_symbolic() consumption

**Comment by Char-Aznable** [comment]
These are the cmake build options I used:
```
cmake .. \
-DCMAKE_CXX_COMPILER=$CXX \
-DCMAKE_CXX_STANDARD=14 \
-DCMAKE_VERBOSE_MAKEFILE=ON \
-DCMAKE_INSTALL_RPATH=${LIBRARY_PATH} \
-DUSE_GPERFTOOLS=ON \
-DBUILD_SHARED_LIBS=ON \
-DKokkos_ARCH_HSW=ON \
-DKokkos_ENABLE_OPENMP=ON \
-DKokkos_ENABLE_DEPRECATED_CODE=OFF \
-DKokkos_ENABLE_EXPLICIT_INSTANTIATION=OFF \
-DKokkosKernels_ADD_DEFAULT_ETI=OFF \
-DKokkosKernels_ENABLE_TPL_BLAS=ON \
-DKokkosKernels_ENABLE_TPL_LAPACK=ON \
-DKokkosKernels_LINALG_OPT_LEVEL=3

```

**Comment by Char-Aznable** [comment]
Can @crtrott @srajama1 @mndevec comment on possible ways to tune down the memory usage since you are the authors of the spgemm paper? It seems to me that this implementation defeats its purpose by requiring as much memory as the dense matrix version

**Comment by mndevec** [comment]
Hi Char-Aznable,
It  has been long time since I worked on this code, so I may not remember the details correctly.  It is very possible that we might have a bug, but I suspect it is the case here.

Couple observations:
* I think KK_DENSE is not the most memory efficient option, in fact its memory cost is the heaviest. You will have an additional memory cost of num_threads * (accumulator_size = nCtr * 500), in addition to input and output matrices. 
* But I suspect that it will be any better if you use any other "memory-efficient" methods for this example. Mainly because it is multiplying two random matrices with 5% sparsity (if I am not mistaken). The result is very likely to be very dense (what is the sparsity you observe for the output?), in such cases dense matrix multiplication might be preferable. 
*  In general, this is mostly designed for scientific computing or graph analytics where sparsity is way less than 5%. I dont think this is really optimized for such cases. 

I think Prof. Edgar Solomonik had a study comparing dense and sparse matrix multiplications with different sparsities. After some certain sparsity, it makes more sense to use dense matrix multiplication in general.

**Comment by Char-Aznable** [comment]
@mndevec Thank you for your input! The output matrix's sparsity is indeed very high (> 90%). But my naive thinking is that at the very least it shouldn't involve the memory consumption for the dense input matrices because I can imagine an algorithm to first transpose the rhs and then do a nRows * nCols dot product, which should only takes the memory for the two input sparse and the output dense matrix plus some fraction of overhead due to tranposition. 

>I think KK_DENSE is not the most memory efficient option, in fact its memory cost is the heaviest. You will have an additional memory cost of num_threads * (accumulator_size = nCtr * 500), in addition to input and output matrices.

I did try using only 1 thread but it doesn't make any difference in memory consumption. Which of the implemented KK_* algorithms would be more efficient? Some of them appears to only have the label but never implemented and I struggle to find documentation for them.

>What is the application that you are using it for? Do the matrices you are interested have 5% sparsity with similar random nonzero distribution? If so, yes, dense matrix multiplication might be more useful (not only for memory but also for runtime).

My application is actually product of A*B where A is a lower triangle matrix and B is a binary sparse matrix. The sparsity of B is kinda data dependent but its dimension is on the order of 10^6 * 10^6 so dense matrix product is out of question

**Comment by mndevec** [comment]
I think most of the memory actually comes from the output matrix itself, if the output has 0.90 sparsity.

nr = 1023
ncols = 1023 * 500
nnz = 1023 * 1023 * 500 * 0.9 (sparsity) = 470938050 

The result matrix when stored as a sparse matrix: 
* You will need 470938050 int to store column indices --> 1796 MB.
* You will again need 470938050 floats to store column values --> 1796 MB.

Note that, storing it as a dense matrix only needs 1023 * 1023 * 500 floating point values --> 1996 MB.

I think what you would need is an implementation that is optimized for the case where two sparse matrices' multiplication resulting in a dense matrix. I might be wrong but MKL might have something optimized for this scenario.

**Comment by mndevec** [comment]
(or it should be easy to implement this using Kokkos)

**Comment by Char-Aznable** [comment]
@mndevec I think you are right about the output sizing. For my specific implementation, what I actually need is a lower triangular matrix L * B where B is CrsMatrix resulting in probably a dense matrix. I believe lower triangular format should avoid hash table look up for the dot product so it should be straightforward to implement, am I right? Anyway, thank you again for your comments! This helps me a lot

**Comment by mndevec** [comment]
[Here](https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-fortran/top/blas-and-sparse-blas-routines/inspector-executor-sparse-blas-routines/inspector-executor-sparse-blas-execution-routines/mkl-sparse-spmmd.html) is the function from MKL.

If MKL is not an option, something like Gustavson's algorithm can be implemented.
```
// A - sparse with nr rows and nCtr cols.
// B - sparse with nCtr rows and nc cols.
C = 0 // dense matrix with nr rows and nc cols.
# pragma omp for 
for row in A:
  for colArowB in A[row]:
    for colB in B[colArowB]:
      C[row, colB] += A[row, colArowB] * B[colArowB, colb]
```
I hope it helps.

**Comment by Char-Aznable** [comment]
Thank you! I'll close this for now

**Comment by srajama1** [comment]
Just copying from Github for posterity
@Char Aznable Looks like your C (output) is really, really dense. Is this the use case that you want. None of our algorithms are optimized for this use case as I haven't found a practical reason for this. Can you describe your use case please?


We optimize KK_DENSE uses a dense accumulator (based on the#cols in B). LTG could be used, but the L in LTG is for low thread counts. You can't use it on GPUs.

For a matrix as dense as you are describing, the best approach might be allocate C as dense, and then write directly to the entries of C. This could be written, but we do not have an use case from our projects. If you write one, please contrubite to Kokkos Kernels.

**Additional questions:** If L is lower triangular B is sparse, what is the sparsity of L and B to give a dense C? The reason I am asking is, there are reordering that you could apply to L in some special cases (triangle counting) to avoid dense C.

@mndevec : Welcome back :) !

**Comment by Char-Aznable** [comment]
>Additional questions: If L is lower triangular B is sparse, what is the sparsity of L and B to give a dense C? The reason I am asking is, there are reordering that you could apply to L in some special cases (triangle counting) to avoid dense C.

@srajama1 The sparsity the B is data dependent so there isn't a fixed pattern there. I am not familiar with the triangle counting thing. Do you have a reference?
