### ISSUE TITLE
Rename files and NameSpace to KokkosKernels

### ISSUE THREAD

**Issue by srajama1** [kokkos/kokkos-kernels#12]
Rename files and NameSpace to KokkosKernels

The files start with Kokkos now. Namespace is Kokkos as well.

**Comment by crtrott** [comment]
Didn't we actually want to name them KokkosBlas, KokkosSparse, etc.?

**Comment by crtrott** [comment]
And same for namespaces. If we do that then there is only a handful of files we need to change, some of which are deprecated.
