### ISSUE TITLE
cuBLAS gemv wrapper: support mixed value types between A,B,C

### ISSUE THREAD

**Issue by tmranse** [kokkos/kokkos-kernels#1203]
I noticed that when running the following code on the device:
``` C++
using DeviceSpace = Kokkos::CudaSpace;
using matrix_value_t = float;
const int M = 1000;
const int N = 1000;
Kokkos::View<matrix_value_t**,DeviceSpace> A(Kokkos::ViewAllocateWithoutInitializing("A"),M,N);
Kokkos::View<double*,DeviceSpace> x(Kokkos::ViewAllocateWithoutInitializing("X"),N);
Kokkos::View<double*,DeviceSpace> y(Kokkos::ViewAllocateWithoutInitializing("Y"),N);

Kokkos::deep_copy(A,1.0);
Kokkos::deep_copy(x,3.0);

const double alpha = double(1.0);
const double beta = double(0.0);

for (int i=0;i<1000;++i)
  KokkosBlas::gemv("N",alpha,A,x,beta,y);
```
I get different behavior if `matrix_value_t = double` vs `matrix_value_t = float`. Running with the space-time stack profiler, it looks like `KokkosBlas::gemv()` is falling back to the single level impl for mixed value types (e.g. when `matrix_value_t = float`).

It would be helpful for the cublas wrapper to support any value type combination.

**Comment by tmranse** [comment]
If cuBLAS can't support mixed precision, I think that falling back to the two-level version for the device kernels would be more helpful than falling back to single-level.

**Comment by srajama1** [comment]
@lucbv @brian-kelley : This is needed for the milestone problem. Let us raise priority and discuss offline.

**Comment by brian-kelley** [comment]
@tmranse I just ran this example in my own build, and it did run the two-level kernel:
```
Kernels: 

- KokkosBlas::gemv[twoLevel]
 (ParFor)   0.000141 1 0.000141 50.042337 23.840258
- Kokkos::ViewFill-1D
 (ParFor)   0.000078 2 0.000039 27.688400 13.190803
- Kokkos::View::initialization [A] via memset
 (ParFor)   0.000050 1 0.000050 17.696867 8.430819
- Kokkos::View::initialization [x] via memset
 (ParFor)   0.000007 1 0.000007 2.455546 1.169827
- Kokkos::View::initialization [y] via memset
 (ParFor)   0.000006 1 0.000006 2.116850 1.008471
```

I don't think this would have changed since November, but can you try it again?
And you're right, cuBLAS doesn't support mixed scalar types.

**Comment by tmranse** [comment]
@brian-kelley sure, I just confirmed that I'm still seeing the SingleLevel call. Our last integration was on 12-07-2021.
```
BEGIN KOKKOS PROFILING REPORT:
TOTAL TIME: 0.994738 seconds
TOP-DOWN TIME TREE:
<average time> <percent of total time> <percent time in Kokkos> <percent MPI imbalance> <remainder> <kernels per second> <number of calls> <name> [type]
===================
|-> 5.76e-01 sec 57.9% 99.5% 0.0% 0.5% 1.74e+03 1000 KokkosBlas::gemv[noETI] [region]
|   |-> 5.74e-01 sec 57.7% 100.0% 0.0% ------ 1000 KokkosBlas::gemv[SingleLevel] [for]

BOTTOM-UP TIME TREE:
<average time> <percent of total time> <percent time in Kokkos> <percent MPI imbalance> <number of calls> <name> [type]
===================
|-> 5.74e-01 sec 57.7% 100.0% 0.0% ------ 1000 KokkosBlas::gemv[SingleLevel] [for]
|   |-> 5.74e-01 sec 57.7% 100.0% 0.0% 0.0% 0.00e+00 1000 KokkosBlas::gemv[noETI] [region]
|-> 2.68e-03 sec 0.3% 0.0% 0.0% 0.0% 0.00e+00 1000 KokkosBlas::gemv[noETI] [region]

KOKKOS HOST SPACE:
===================
MAX MEMORY ALLOCATED: 0.0 kB
MPI RANK WITH MAX MEMORY: 0
ALLOCATIONS AT TIME OF HIGH WATER MARK:

KOKKOS CUDA SPACE:
===================
MAX MEMORY ALLOCATED: 3921.9 kB
MPI RANK WITH MAX MEMORY: 0
ALLOCATIONS AT TIME OF HIGH WATER MARK:
  99.6% A
  0.2% X
  0.2% Y

Host process high water mark memory consumption: 2579408 kB
  Max: 2579408, Min: 2579408, Ave: 2579408 kB

END KOKKOS PROFILING REPORT.
```

**Comment by brian-kelley** [comment]
@tmranse The relevant changes went into KokkosKernels develop on 4-16, Trilinos develop branch on 10-28, and still aren't in a Trilinos master. So I guess it depends on which branch you do integration from, whether that explains you still getting the single level kernel.

**Comment by brian-kelley** [comment]
@tmranse I had my master pointed at the wrong remote - it actually got it on 10-28 also. If you can grep for "TwoLevelGEMV_LayoutLeftTag" in packages/kokkos-kernels, then you'll know you have the changes.

**Comment by tmranse** [comment]
@brian-kelley I see that tag on the fresh pull of Trillinos master, but not on our current integration point. Either way it seems this issue will be solved on our end with a new integration so we can go ahead and close this ticket.

Thanks,
Tom

**Comment by tmranse** [comment]
@brian-kelley just confirmed that with the fresh pull, I am seeing the two-level kernel. Thanks for the clarification.

**Comment by srajama1** [comment]
Thanks @brian-kelley @tmranse !!

**Comment by e10harvey** [comment]
@brian-kelley: I never use `--set-upstream` and always use `git {push,pull,fetch} remote-name local-branch`. It's a few more key strokes but makes me pause -- especially before `git push`.
