### ISSUE TITLE
Kokkos Kernels version Macros

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#1207]
@ndellingwood @crtrott @srajama1 
Currently we are only defining CMake variables to keep track of the current version of Kokkos Kernels.
It would be beneficial for users to have access to a MACRO that computes the full version number as it is done in Kokkos.
We might also want to provide additional macros for MAJOR, MINOR and PATCH number too.

**Comment by crtrott** [comment]
I agree lets add all four on both side and define the version the usual way MAJOR*10000 + MINOR*100 + PATCH

**Comment by srajama1** [comment]
Yes, agreed

**Comment by lucbv** [comment]
Based on discussion during the Kokkos developers meeting we are not going to provide the four macros, just the macro that define the full version.
