### ISSUE TITLE
fatal error: impl/KokkosSparse_BsrMatrix_impl.hpp: No such file or directory

### ISSUE THREAD

**Issue by jczhang07** [kokkos/kokkos-kernels#1216]
I installed Kokkos and KK with their origin/develop branch.  When I compiled my own code,  I met

```
KokkosSparse_BsrMatrix.hpp:55:10: fatal error: impl/KokkosSparse_BsrMatrix_impl.hpp: No such file or directory
 #include "impl/KokkosSparse_BsrMatrix_impl.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It seems this is because `KokkosSparse_BsrMatrix_impl.hpp` is installed to `$INSTALL_PREFIX/include`, instead of `$INSTALL_PREFIX/impl/include`

Changing to  `#include "KokkosSparse_BsrMatrix_impl.hpp"`  fixed the error.

**Comment by brian-kelley** [comment]
Fix ready in #1222. It is just @jczhang07 's suggested fix.

**Comment by lucbv** [comment]
PR #1222 has just been merged so it is now fixed in develop.
@jczhang07 let us now if you still have issues?

**Comment by jczhang07** [comment]
@lucbv  It works on my end. Thanks.
