### ISSUE TITLE
Nightly test failures with cuda.batched_scalar_batched_gemm_nt_nt_half_half_right: View bounds error

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1224]
Nightly Cuda builds with View bounds checking are failing in the `cuda.batched_scalar_batched_gemm_nt_nt_half_half_right` due to a View bounds error, e.g.

```
01:13:14 2: [ RUN      ] cuda.batched_scalar_batched_gemm_nt_nt_half_half_right
01:13:14 2: :0: : block: [0,0,0], thread: [1,0,0] Assertion `View bounds error of view b_actual` failed.
...
```

This is following merge of #1217, @e10harvey are you able to investigate?

**Reproducer** (weaver):
```
module load cmake/3.19.3 cuda/10.1.243 ibm/xl/16.1.1 gcc/7.4.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Cuda,OpenMP --arch=Power9,Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-cuda-options=enable_lambda --boundscheck  --no-examples
```

**Comment by e10harvey** [comment]
@ndellingwood: Shall we spending time investigating this given the findings in https://github.com/kokkos/kokkos-kernels/issues/1157?

**Comment by ndellingwood** [comment]
@e10harvey yes, this is an ongoing supported Cuda build using gcc as host compiler (xl is loaded by default but not used, copy+pasted in the reproducer)

**Comment by ndellingwood** [comment]
Also adding @vqd8a (I thought @e10harvey had submitted #1217)
