### ISSUE TITLE
ETI build should default to off 

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos-kernels#1245]
In my experience, kokkos-kernels ETI build is expensive especially in CUDA build. In situations when kokkos-kernels is needed by a cmake fetchcontent or subdirectory project, one don't necessarily want to build kokkos-kernels ETI, e.g., if a subset of the header is needed from the fetchcontent project. To avoid the expensive ETI build, the current solution is to force all downstream dependency to explicitly call cmake `-DKokkosKernels_ADD_DEFAULT_ETI=OFF`, which is unmanagible for large dependency tree. I suggest the kokkos-kernels ETI should be set to off by default.

**Comment by lucbv** [comment]
Hi @Char-Aznable this seems to be an opinion statement based on your personal experience and not necessarily general enough to account for all software libraries that rely on Kokkos Kernels.
Thank you for sharing this, we are periodically re-evaluating our defaults but at this point there does not seem to be a reason to change `KokkosKernels_ADD_DEFAULT_ETI` so I will close this issue.
