### ISSUE TITLE
Add GEMM default Kernel

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-kernels#125]
The kernel should be able to handle arbitrary layouts as well as scalar types.
It also should have ok performance.

**Comment by mhoemmen** [comment]
Q: What should users do if the fall-back is host only?

**Comment by crtrott** [comment]
This kernel works on everything. And the point is that it is a fallback for not having the right type of TPL. It does not work with AD types which use internal parallelization though.

**Comment by mhoemmen** [comment]
Stokhos deals with this in its Belos adapters by calling GEMM on the underlying entry type (e.g., `double`).  Tpetra may still want to _compile_ those functions for Stokhos, etc. types, though.  If we get compilation errors, Tpetra can always work around by wrapping and specializing out for unsupported Scalar types.
