### ISSUE TITLE
Replace Kokkos::Impl::throw_runtime_exception with KokkosKernels version

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#1258]
Kokkos::Impl functions should be avoided in Kokkos Kernels if possible since they are susceptible to change without warning.
Further more in the particular instance of `Kokkos::Impl::throw_runtime_exception` there is no reason not to define our own as the function is a pretty simple wrapper around `std::runtime_error` that calls `traceback_callstack()` which can be done in Kokkos Kernels.
@dalg24

**Comment by ndellingwood** [comment]
PR #1294

**Comment by lucbv** [comment]
Thanks @ndellingwood, I should probably close this issue unless you want to keep it to track things in 3.6.0?
