### ISSUE TITLE
Build error with spack: half_t is not a member of 'Kokkos::Experimental

### ISSUE THREAD

**Issue by payerle** [kokkos/kokkos-kernels#1263]
I am trying to build kokkos-kernels@3.4.01 using spack, but when I do so if fails with the error
```console

$ spack install kokkos-kernels@3.4.01%gcc@9.4.0 +blas build_type=RelWithDebInfo +cblas ~cublas ~cuda ~cusparse execspace_cuda=False execspace_openmp=True execspace_serial=True execspace_threads=False +ipo +lapack ~lapacke layouts=left,right memspace_cudaspace=False memspace_cudauvmspace=False ~mkl offsets=int,size_t +openmp ordinals=int ~pthread scalars=complex_double,complex_float,double,float +serial +shared +superlu arch=linux-rhel8-zen2

[...]
     280    In file included from /tmp/spackswinst/spack-stage/spack-stage-kokkos-kernels-3.4.01-iuzbqtilacap7naqfforrlnpm3t7p43a/spack-src/src/batched/KokkosBatched_Trsm_Decl.hpp:7,
     281                     from /tmp/spackswinst/spack-stage/spack-stage-kokkos-kernels-3.4.01-iuzbqtilacap7naqfforrlnpm3t7p43a/spack-src/src/blas/impl/KokkosBlas3_trsm_impl.hpp:57,
     282                     from /tmp/spackswinst/spack-stage/spack-stage-kokkos-kernels-3.4.01-iuzbqtilacap7naqfforrlnpm3t7p43a/spack-src/src/blas/impl/KokkosBlas3_trsm_spec.hpp:53,
     283                     from /tmp/spackswinst/spack-stage/spack-stage-kokkos-kernels-3.4.01-iuzbqtilacap7naqfforrlnpm3t7p43a/spack-build-iuzbqti/src/impl/generated_specializations_cpp/trsm/Blas3_trsm_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_OPENMP
            _MEMSPACE_HOSTSPACE.cpp:48:
  >> 284    /tmp/spackswinst/spack-stage/spack-stage-kokkos-kernels-3.4.01-iuzbqtilacap7naqfforrlnpm3t7p43a/spack-src/src/batched/KokkosBatched_Util.hpp:208:57: error: 'half_t' is not a member of 'Kokkos::Experimental'
     285      208 |                    std::is_same<T,Kokkos::Experimental::half_t>::value,
     286          |                                                         ^~~~~~
  >> 287    /tmp/spackswinst/spack-stage/spack-stage-kokkos-kernels-3.4.01-iuzbqtilacap7naqfforrlnpm3t7p43a/spack-src/src/batched/KokkosBatched_Util.hpp:208:57: error: 'half_t' is not a member of 'Kokkos::Experimental'
  >> 288    /tmp/spackswinst/spack-stage/spack-stage-kokkos-kernels-3.4.01-iuzbqtilacap7naqfforrlnpm3t7p43a/spack-src/src/batched/KokkosBatched_Util.hpp:208:63: error: template argument 2 is invalid
     289      208 |                    std::is_same<T,Kokkos::Experimental::half_t>::value,
     290          |                                                               ^
  >> 291    make[2]: *** [src/CMakeFiles/kokkoskernels.dir/build.make:919: src/CMakeFiles/kokkoskernels.dir/impl/generated_specializations_cpp/trsm/Blas3_trsm_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_OPENMP_MEMSPACE_HOSTSPACE.cpp.o] Error 1
     292    make[2]: Leaving directory '/tmp/spackswinst/spack-stage/spack-stage-kokkos-kernels-3.4.01-iuzbqtilacap7naqfforrlnpm3t7p43a/spack-build-iuzbqti'
  >> 293    make[1]: *** [CMakeFiles/Makefile2:884: src/CMakeFiles/kokkoskernels.dir/all] Error 2
     294    make[1]: Leaving directory '/tmp/spackswinst/spack-stage/spack-stage-kokkos-kernels-3.4.01-iuzbqtilacap7naqfforrlnpm3t7p43a/spack-build-iuzbqti'
  >> 295    make: *** [Makefile:149: all] Error 2
```
This looks like an error in kokkos-kernels.  If I am interpretting the comment at line 669 of Kokkos_ArithTraits.hpp correctly, it sounds like Kokkos::Experimental::half_t is only defined in some cases (e.g. when KOKKOS_HALF_T_IS_FLOAT is defined and false???), but I am far from fluent in C++ and am having trouble following this code.

My spack environment is:
```console
$spack debug report * **Spack:** 0.17.0-319-5dce4d79bd
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo
```

I noticed the spack build instructions at https://github.com/kokkos/kokkos-kernels refers to a kokkos-spack git repo; I was unable to locate such, but am using the package.py, etc for kokkos-kernels shipped with spack (and have also tried with a slightly newer version of the package.py just downloaded from spack today), but no difference.  I also tried building kokkos-kernels@3.5.00

Attached is the full build output, along with CMakeCache and the arguments passed to cmake.
[kokkos-kernels.spack-build.txt](https://github.com/kokkos/kokkos-kernels/files/7866256/kokkos-kernels.spack-build.txt)
[CMakeCache.txt](https://github.com/kokkos/kokkos-kernels/files/7866270/CMakeCache.txt)
[spack-configure-args.txt](https://github.com/kokkos/kokkos-kernels/files/7866271/spack-configure-args.txt)

**Comment by e10harvey** [comment]
@payerle: Judging by the CMakeCache.txt, it look like spack is picking up kokkos version 3.1.01. Please try building with kokkos-kernels with kokkos version 3.4.01.

**Comment by lucbv** [comment]
@e10harvey I see that we have never been particularly good at populating the `depends_on()` statements for each versions of Kokkos Kernels, I will add them to ensure that people get a Kokkos version that matches that of Kokkos Kernels by default.

**Comment by lucbv** [comment]
@payerle 
I am working on updating the spack package, it will include the newest version of Kokkos Kernels: 3.5.00 and will automatically pick the corresponding Kokkos version. If you don't mind once that work is merged in the spack repo you might want to test again and see if things work a bit better automatically.

**Comment by lucbv** [comment]
Aright, I have the following PRs to tackle this issue:
Kokkos: https://github.com/spack/spack/pull/28410
Kokkos Kernels: https://github.com/spack/spack/pull/28409

**Comment by payerle** [comment]
Thanks to all of you for the prompt response.
I can confirm the issue was due to mismatch in kokkos/kokkos-kernels versions (successfully build with both @3.4.01).  I suspect the mismatch was a typo in my packages.yaml --- sorry.

I will try to test the spack PRs later today.

**Comment by payerle** [comment]
I just successfully build kokkos + kokkos-kernels@3.5.00 using spack with the aforementioned PRs.

Thanks again for all of your assitance.
