### ISSUE TITLE
Optimize BatchedGemm Double Buffering for LayoutLeft

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos-kernels#1274]
Paths forward (discussed with @vqd8a)

- [x] Swap parallel fors (illegal use of kokkos) to change access pattern (+)
  - [x] LL scratch (-)
- [x] use `member.team_rank()` instead of TeamThreadRange parallel for (=, -)
- [x] Use single TeamVectorRange parallel for with `getIndex` approach from @kliegeois (-, ~1.5x)
- [x] Remove both parallel fors in favor of `thread_id=member.team_rank()` and `vlane_id=member.thread_rank()`(*WONT DO: member.thread_rank() is not supported on all backends)
  - [x] Use `getIndex` approach overloaded on Layout type (WONT DO)

**Comment by ndellingwood** [comment]
@e10harvey with merge of #1299 is it safe to add InDevelop label?
