### ISSUE TITLE
CMake requirement for Kokkos Core and Kokkos Kernels is different

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#1309]
Should we bump up the required version of CMake for Kokkos Kernels?
Currently we are requiring the following:
```
cmake_minimum_required(VERSION 3.10 FATAL_ERROR)
```
while Kokkos is requiring:
```
cmake_minimum_required(VERSION 3.16 FATAL_ERROR)
```

**Comment by srajama1** [comment]
Let us use same as Core.

**Comment by lucbv** [comment]
Thanks @ndellingwood , I stumble upon it while working on the version macros and it seems odd since pretty much every user will need to configure Kokkos first with 3.16 requirement.
If this starts taking too much time let me know and I can help do the rebase.
The flag deduplication seems like something useful but if we want to wait until after the release to do that cleanly, I am totally fine with that approach.
