### ISSUE TITLE
Build error when MKL TPL is enabled

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos-kernels#135]
```
.../Trilinos/packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_mkl_impl.hpp:165:24: error: use of undeclared identifier 'valuesA'
    value_type *a_ew = valuesA.ptr_on_device();
                       ^
.../Trilinos/packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_mkl_impl.hpp:166:24: error: use of undeclared identifier 'valuesB'
    value_type *b_ew = valuesB.ptr_on_device();
                       ^
```
Please push fix to Trilinos as well.  Thanks!

**Comment by mndevec** [comment]
Sorry about this. Current pull request fixes this. I will simply disable this in Trilinos until the next KokkosKernels promotion,  as it is not used anyway.

**Comment by mhoemmen** [comment]
Thanks @mndevec !  Thanks also for the Trilinos PR.

**Comment by anates** [comment]
Same problem also occurs for the file KokkosSparse_spgemm_mkl2phase_impl.hpp, a similar fix might help (compilation works, unit tests not done yet)

**Comment by mndevec** [comment]
@anates 
What is the failure in the case of mkl2phase? Is it the same compilation failure? 
Are you using it through Trilinos or stand-alone?

**Comment by anates** [comment]
@mndevec Same compilation failure, I am using it through Trilinos

**Comment by mndevec** [comment]
@anates 
Sorry about the issue. I am pushing a fix to trilinos again. I will merge it as soon as auto-tester is done.

It looks like we are using different flags to enable MKL within Trilinos and standalone package. 
Trilinos is setting HAVE_KOKKOSKERNELS_MKL, while makefile system is setting KOKKOSKERNELS_ENABLE_TPL_MKL. 

@crtrott @srajama1 : Am I missing a place where trilinos sets both of the flags? Is this a bug that we should fix in Trilinos?

**Comment by mndevec** [comment]
@anates 
the fixes are pushed to trilinos develop branch. It should solve the problem.

**Comment by srajama1** [comment]
Trilinos sets the flag based on a combination of things : TPL name, what is in <packagename>_config.h.in and sometimes explicitly in a package/CMakeLists.txt. There is no one way to do this. I would check all three places and change to a consistent naming as needed

**Comment by srajama1** [comment]
The errors of not refreshing the screen, you have a fix already :)

**Comment by mndevec** [comment]
Siva, 
I pushed a fix, but I mean this might cause more bugs in future because of the inconsistencies.

**I am not sure, but** I think why this was not caught in kokkoskernels tests is because the flag used in KokkosKernels is different. 

When we enable MKL in kokkoskernels, makefile system sets only the flag the "KOKKOSKERNELS_ENABLE_TPL_MKL", not HAVE_KOKKOSKERNELS_MKL.

I think this part of the code may have never been compiled in standalone library.

**Comment by srajama1** [comment]
Let us review this code when you have few minutes.
