### ISSUE TITLE
SpGEMM Benchmark Verification

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos-kernels#136]
The SpGEMM benchmarks can be found below: 
https://github.com/kokkos/kokkos-kernels/wiki/SpGEMM_Benchmarks

The replication of these experiments are described below: 

- KNL [CACHE] MODE: https://github.com/kokkos/kokkos-kernels/wiki/knl_configure
- Power8: https://github.com/kokkos/kokkos-kernels/wiki/power8_configure
- P100: https://github.com/kokkos/kokkos-kernels/wiki/p100_configure

For a single matrix audi, it lists the expected times. Can you try and verify the results, and let me know if you run into any problems?

RAW TABLEs in the benchmark lists all the runtimes achieved for 83 matrices. If you want, you can try for other matrices as well. Let me know if you run into any issue.

**Comment by srajama1** [comment]
I have verified number of these (not all) on KNL, Power8, P100. It would be nice to merge PR#44 and make this automated w/ jenkins say once a week. @MicheldeMessieres

**Comment by srajama1** [comment]
I am closing this and creating a new issue for PR #44
