### ISSUE TITLE
Some sparse tests fail with floats on.

### ISSUE THREAD

**Issue by jgfouca** [kokkos/kokkos-kernels#1362]
The following tests have been failing for a while:
```
[  FAILED  ] openmp.sparse_spmv_float_int_int_TestExecSpace
[  FAILED  ] openmp.sparse_spmv_float_int_size_t_TestExecSpace
[  FAILED  ] openmp.sparse_spmv_mv_float_int_int_LayoutLeft_TestExecSpace
[  FAILED  ] openmp.sparse_spmv_mv_float_int_size_t_LayoutLeft_TestExecSpace
```

I have tried to bisect, but the problem goes back more than a month and my kokkos-kernels repo quickly becomes incompatible with my kokkos installation. That raises an additional question: as you go back in history, is there any way to know what version of kokkos to use with kokkos-kernels?

I am using the following to configure kokkos:
```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_SERIAL=ON -DCMAKE_INSTALL_PREFIX=${HOME}/kokkos/install ..
```

And this to configure kokkos-kernels:
```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DKokkosKernels_INST_FLOAT=ON -DKokkosKernels_ENABLE_TESTS=ON -DKokkos_ROOT=${HOME}/kokkos/install ..
```

I have the follow modules loaded:
```
 1) sems-archive-env   2) sems-archive-gcc/9.2.0   3) sems-archive-cmake/3.19.1   4) sems-archive-git/2.10.1   5) sems-archive-openmpi/4.0.2   6) sems-archive-hdf5/1.10.6/parallel   7) sems-archive-netcdf/4.7.3/parallel
```

And ran my tests via:
```
OMP_NUM_THREADS=8 ./KokkosKernels_sparse_openmp
```

@lucbv , I assigned you since I thought you might know who to pass the ticket to.

**Comment by lucbv** [comment]
Okay, hopefully PR #1412 fixed it, let me know if you see it again, otherwise we might be able to close this.

**Comment by lucbv** [comment]
I think so but @jgfouca should probably confirm first.

**Comment by jgfouca** [comment]
@lucbv , @ndellingwood , yep, appears to work now! Thanks!
