### ISSUE TITLE
Add example directory for Wiki examples 

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-kernels#137]
This also adds generic Makefiles which can be used to build the Wiki examples.

**Comment by crtrott** [comment]
Here are some examples of how to build the blas/abs example from some build directory:

```
make -f ~/Kokkos/kokkos-kernels/example/wiki/blas/abs/Makefile -j
make -f ~/Kokkos/kokkos-kernels/example/wiki/blas/abs/Makefile -j KOKKOS_DEVICES=Cuda,OpenMP KOKKOS_ARCH=Power8,Pascal60
```

**Comment by ndellingwood** [comment]
@crtrott based on the comments I'm assuming this was already done but we missed marking as InDevelop? Marking as InDevelop, please fix if I'm mistaken.
