### ISSUE TITLE
Some KokkosBlas kernels assume default execution space

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos-kernels#14]
The implementation of KokkosBlas::dot incorrectly assumes the default execution space, by using expressions like `Kokkos::parallel_reduce(numRows, op);`, instead of an explicit `Kokkos::RangePolicy<execution_space, ...>`.  Check other KokkosBlas kernels as well.

**Comment by crtrott** [comment]
Can someone check whether this is still an issue.

**Comment by lucbv** [comment]
@crtrott this has been fixed in `KokkosBlas::dot` and it does not appear in other Blas functions.

**Comment by ndellingwood** [comment]
Marking as bug fixed and in develop.
