### ISSUE TITLE
`KokkosGraph_Distance1Color_impl.hpp` variable `total` set but not used

### ISSUE THREAD

**Issue by Jacobfaib** [kokkos/kokkos-kernels#1400]
```
KokkosGraph_Distance1Color_impl.hpp:414:15: warning: variable 'total' set but not used [-Wunused-but-set-variable]
    double t, total = 0.0;
              ^
1 warning generated.
```

**Comment by lucbv** [comment]
@brian-kelley can you have a quick look?

**Comment by brian-kelley** [comment]
The fix is in #1403 . I couldn't replicate this on my machine with ``-Wunused-but-set-variable``, even though it's clear from the code that the variable really is unused. This warning flag is included in ``-Wall`` which we do PR testing with, so it seems like those builds didn't catch it either, weird.

**Comment by Jacobfaib** [comment]
> I couldn't replicate this on my machine with -Wunused-but-set-variable

What machine/compiler are you using? Apple `clang`'s unused variable tracker appears to have gotten a major -- though undocumented -- uplift in latest release (13.1.6) which has shaken out a lot of these set-but-unused "bugs"...

**Comment by brian-kelley** [comment]
@Jacobfaib I used GCC 9.1.0. Anyway, thanks for reporting this and maybe we can get testing on newer compilers so we don't introduce new warnings like this. But it's probably a good sign if this was the only one the new Clang found.

**Comment by brian-kelley** [comment]
I'm looking through some old issues, and closing since the fix has long been in develop and the last couple release versions.
