### ISSUE TITLE
batched gesv: Bugs, Output, and Documentation

### ISSUE THREAD

**Issue by jennloe** [kokkos/kokkos-kernels#1409]
Hi, I am having issues with the serial batched gesv solve as follows:

1. Solver fails and returns Nans for the simple test (full code below):  A = [0 2; -3 0], b = [1; -4].  Soln is x = [1/2; 4/3]. (This is without pivoting.  For the Newton solve context where I am trying to use gesv, we canNOT afford to assume that A has at least one nonzero on the diagonal. This is from a real test case. )
2. The matrix from the problem above should be added to the unit tests for this kernel. :)
3. Solver return status output is 0 (success) for that case.  Solver should output 1 or some error upon failure.  (What if it encounters a singular linear system?)
4. Please fix headers so that we do not have to use ```  #include "KokkosBatched_LU_Decl.hpp" #include "KokkosBatched_LU_Serial_Impl.hpp" ``` with this function.
5. Documentation states that solver takes 3D and 2D views for A and b respectively.  Reality is that it takes 2D and 3D views.  Please make this consistent.  

Thanks! 

Related: #1349 
Minimal example:

```#include "KokkosBatched_LU_Decl.hpp"
#include "KokkosBatched_LU_Serial_Impl.hpp"
#include "KokkosBatched_Gesv.hpp"

using matrix_type    = Kokkos::View<double**,  Kokkos::DefaultExecutionSpace>;
using vector_type    = Kokkos::View<double*,  Kokkos::DefaultExecutionSpace>;

template<class MatrixType, class VectorType>
struct GesvFunctor{
  
  MatrixType A, tmp;
  VectorType b, x;

  GesvFunctor(MatrixType A_, VectorType b_, VectorType x_, MatrixType tmp_):
    A(A_), b(b_), x(x_), tmp(tmp_) {}

  KOKKOS_INLINE_FUNCTION
    void operator()(int /* idx */) const {
      const int N = 2;
      A(0,0) = 0;
      A(0,1) = 2;
      A(1,0) = -3; 
      A(1,1) = 0;

      b(0) = 1;
      b(1) = -4; 

      int linSolveStat = KokkosBatched::SerialGesv<KokkosBatched::Gesv::NoPivoting>::invoke(A, x, b, tmp);
      KOKKOS_IMPL_DO_NOT_USE_PRINTF("Print linear solve solution: \n");
      for( int k = 0; k < N; k++){
        KOKKOS_IMPL_DO_NOT_USE_PRINTF("%f \n", x(k));
      }   
      KOKKOS_IMPL_DO_NOT_USE_PRINTF("Print linear solve return status: %d \n", linSolveStat);
    }   
};

int main (int /*argc*/, char** /* argv[]*/) {
  Kokkos::initialize();
  {
    const int N = 2;
    matrix_type A("matrix A", N, N); 
    vector_type b("rhs vec", N); 
    vector_type x("soln vec", N); 
    matrix_type tmp("gesv tmp", N, N+4);
    GesvFunctor<matrix_type,vector_type> myFunctor(A,b,x,tmp);
    Kokkos::parallel_for("testing", 1, myFunctor);
  }
  Kokkos::finalize();
}

**Comment by jennloe** [comment]
@lucbv This is where I ended up trying to verify the Newton solve with a simple example... Guess I'll work around it for now with a different nonlinear system.

**Comment by kliegeois** [comment]
Hi @jennloe the GESV (without pivoting) as it relies on a LU factorization cannot work if there is at least one zero on the diagonal.
If you have at least one potential zero on the diagonal there is no way around using a static pivoting approach as our LU factorization has not pivoting in it.
Your example work with the currently available static pivoting.

I will create a PR asap with 4 and 5.

For 3 it is less straightforward, I am thinking about it.

**Comment by jennloe** [comment]
For #3, the MKL gesv outputs an int called "info" which gives pass/fail info. https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-fortran/top/lapack-routines/lapack-linear-equation-routines/lapack-linear-equation-driver-routines/gesv.html

**Comment by jennloe** [comment]
Kim and I talked about this offline.  A few notes:
a) Number 3 is particularly hard to address because it will create measurable overhead for these small batched systems. 
b) One option is to add a "debug" variable that, when turned on, will perform extra checks. If we take this route, we need to make sure that the option is consistent with similar code in KK.
c) For the time being, I will modify my code to perform an internal residual check after calling the gesv to make sure it is not getting erroneous solve solutions.

**Comment by kliegeois** [comment]
@jennloe can we close this issue?

**Comment by jennloe** [comment]
@kliegeois Yes, I think that is fine.
