### ISSUE TITLE
Possible typo in non-TriBITS config scripts

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos-kernels#142]
In the Trilinos source directory:
```
$ git grep KOKKOS_ARCHS *
packages/kokkos-kernels/example/buildlib/compileKokkosKernels.sh:KOKKOS_ARCHS=Pascal60,Power8
packages/kokkos-kernels/example/buildlib/compileKokkosKernels.sh: ... 
packages/kokkos-kernels/example/buildlib/compileKokkosKernelsSimple.sh:KOKKOS_ARCHS=KNL ...
packages/kokkos-kernels/example/buildlib/compileKokkosKernelsSimple.sh:...
```
Is this supposed to be `KOKKOS_ARCH`?

**Comment by mndevec** [comment]
@mhoemmen,

Yeah I can change the name, but this script is independent from the rest of the code. It shows an example of how to use generate makefile. All variable names are local to this script.

**Comment by mhoemmen** [comment]
@mndevec Ah OK, never mind then :-) .  I just saw that when I was searching for `KOKKOS_ARCH` examples.  Please feel free to close if you wish.
