### ISSUE TITLE
Low performance of SpMV on AMD Epyc 7402

### ISSUE THREAD

**Issue by pmpakos** [kokkos/kokkos-kernels#1432]
Hello
I have compiled the 'kokkos' project for AMD ZEN2 architecture (as reported [here](https://en.wikichip.org/wiki/amd/epyc/7402)) (-DKokkos_ARCH_ZEN2=On) and with OpenMP enabled (-DKokkos_ENABLE_OPENMP=On)
After building successfully, I compiled the 'kokkos-kernels' project too, with MKL Third-party library enabled (-DKokkosKernels_ENABLE_TPL_MKL=On)

However, when running the spmv test (./perf_test/sparse/sparse_spmv) [linked here](https://github.com/kokkos/kokkos-kernels/blob/master/perf_test/sparse/KokkosSparse_spmv.cpp), I get lower performance, to what was expected.
(number of iterations is set to 128, and the examined matrix is [scircuit](https://www.cise.ufl.edu/research/sparse/matrices/Hamm/scircuit.html)

For example, when running the omp-static test average performance that is reported is **1.836 GFLOPs** (for 24 threads), while a naive-csr openmp implementation that was handwritten achieves **10.5 GFLOPs** !
Additionally, when MKL is examined, average performance through kokkos-spmv is reported as **1.76 GFLOPs**, while an equivalent handwritten MKL call achieves **31 GFLOPs**.

I would like to kindly ask you if any configuration of 'kokkos' and 'kokkos-kernels' projects is done wrong. Thank you

**Comment by cwpearson** [comment]
Hi @pmpakos, thanks for bringing this to our attention. Could you let me know
* which version of Kokkos Kernels you're using
* which MKL you are using
* Which system you are testing on (e.g. if it's a particular supercomputer, we may have access as well)

**Comment by cwpearson** [comment]
Notes on reproducing:

Internally Kokkos MKL TPL uses:
* `mkl_scsrmv(&mode, &m, &n, &alpha, "G**C", Avalues, Aentries, Arowptrs, Arowptrs + 1, x, &beta, y);`
* `mkl_dcsrmv(&mode, &m, &n, &alpha, "G**C", Avalues, Aentries, Arowptrs, Arowptrs + 1, x, &beta, y);`

Built on perlmutter as follows:
```
$ module list

Currently Loaded Modules:
  1) craype-x86-milan                       8) Nsight-Compute/2022.1.1  15) craype/2.7.15
  2) libfabric/1.11.0.4.114                 9) Nsight-Systems/2022.2.1  16) gcc/10.3.0
  3) craype-network-ofi                    10) cudatoolkit/11.5         17) perftools-base/22.04.0
  4) xpmem/2.3.2-2.2_7.5__g93dd7ee.shasta  11) PrgEnv-gnu/8.3.3         18) cpe-cuda/22.04
  5) xalt/2.10.2                           12) cray-dsmml/0.2.2         19) fast-mkl-amd/fast-mkl-amd
  6) darshan/3.3.1                         13) cray-libsci/21.08.1.2
  7) cmake/3.22.0                          14) cray-mpich/8.1.15
```

```
export MKLROOT=$HOME/intel/oneapi/mkl/2022.0.2
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/intel/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64_lin"
```

```
cmake .. \
-DCMAKE_CXX_COMPILER=g++ \
-DCMAKE_BUILD_TYPE=Release \
-DKokkos_ENABLE_HWLOC=ON \
-DKokkos_ARCH_ZEN3=ON \
-DKokkosKernels_INST_COMPLEX_FLOAT=OFF \
-DKokkosKernels_INST_DOUBLE=ON \
-DKokkosKernels_INST_FLOAT=ON \
-DKokkosKernels_INST_OFFSET_INT=ON \
-DKokkosKernels_INST_OFFSET_SIZE_T=OFF \
-DKokkosKernels_INST_ORDINAL_INT=ON \
-DKokkosKernels_ENABLE_TESTS=ON \
-DKokkos_ENABLE_OPENMP=ON \
-DTPL_ENABLE_MKL=ON \
-DCMAKE_CXX_FLAGS="-I$HOME/intel/oneapi/mkl/2022.0.2/include -DHAVE_MKL" \
-DCMAKE_CXX_LINK_FLAGS="-L$HOME/intel/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64_lin -liomp5"
```
