### ISSUE TITLE
Small error in KokkosBatched_Gemm_Serial_Imp.hpp with SerialGemm<Trans::Transpose,*,*>

### ISSUE THREAD

**Issue by kliegeois** [kokkos/kokkos-kernels#147]
It seems that in kokkos-kernels/src/batched/KokkosBatched_Gemm_Serial_Impl.hpp, when the matrix A is transposed, the code is currently using A.dimension_1() to get the number k instead of A.dimension_0().

The error seems to be in all the different combinations of the other template arguments (i.e. whether or not B is transposed and for CompactMKL, Blocked, and Unblocked).

@kyungjoo-kim

**Comment by kyungjoo-kim** [comment]
@kliegeois Thanks. You are right. The code is tested and used only for square blocks. So, the error does not pop up so far. I will fix it soon.

**Comment by srajama1** [comment]
Ping

**Comment by kyungjoo-kim** [comment]
#258 fixed this. done.

**Comment by srajama1** [comment]
Reopening it, and adding indevelop tag. We will close it when we do the master update. Otherwise it is hard to keep track of what are the fixes we did.
