### ISSUE TITLE
Github actions restart too often

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#1491]
Github actions are getting restarted when the `Pre-Test Inspection` inspection flag gets set in a PR which means more time waiting for an instance to pick up that job and also it just waste compute time.
It would be good to re-assess when the CI jobs need to be re-run.

**Comment by e10harvey** [comment]
@lucbv : Thanks for reporting this. Based on my understanding of:
https://github.com/kokkos/kokkos-kernels/blob/42c96f2304c4fe1d15aee407fb61f560dcc47a52/.github/workflows/osx.yml#L5

The behavior you describe should not be observed.

When this occurs again, would you please point me where this happens so I can gather more information?
