### ISSUE TITLE
Type-casting between bfloat and half precisions?

### ISSUE THREAD

**Issue by iyamazaki** [kokkos/kokkos-kernels#1500]
Right now, I get compiler errors like:

` no suitable user-defined conversion from "Kokkos::Experimental::Impl::floating_point_wrapper<Kokkos::Impl::half_impl_t::type>" to "Kokkos::Experimental::bhalf_t" exists`

**Comment by e10harvey** [comment]
@iyamazaki: We're not sure this is safe to do and need to think about this some more before supporting mixed precision in `half_t` and `bhalf_t` arithmetic operators. That being said, this could be supported by casting `T` to `float` and then to the kokkos half-precision type (`half_t` or `bhalf_t`). Nvidia does not provide bfloat casting intrinsics that convert directly to half nor mixed precision arithmetic involving bhalf and half: https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH____BFLOAT16__MISC.html. I suspect that other SDKs have similar limitations.

The current mixed precision operators that involve a half-precision type and float or double upcast for arithmetic and then cast the result to the return type. For mixing bfloat and half, what type would you like the arithmetic operands casted to? If we cast the half operator to bfloat, we loose bits in the mantissa. If we cast the bhalf operand to half, we loose bits in the exponent. Is either of those casting results really what you want?

For now, you can cast any HALF_SCALAR_TYPE to float and then to bfloat or half:
```
HALF_SCALAR_TYPE hval;
OTHER_HALF_SCALAR_TYPE ohval = static_cast<OTHER_HALF_SCALAR_TYPE>(static_cast<float>(hval));
```
