### ISSUE TITLE
Rocm/5.2.0 TPL test failure: error: use of undeclared identifier 'rocblasSetStream'

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1593]
rocm/5.2.0 builds (MI100 arch) with rocblas tpls enabled fail compilation with outputs of the type
```
06:48:10 /home/jenkins/caraway-new/workspace/KokkosKernels_CarawayMI100_Rocm520_HipSerial_RocBlas_RocSparse/kokkos-kernels/blas/tpls/KokkosBlas1_rotg_tpl_spec_decl.hpp:632:1: error: use of undeclared identifier 'rocblasSetStream'
06:48:10 KOKKOSBLAS1_DROTG_TPL_SPEC_DECL_ROCBLAS(Kokkos::LayoutLeft, Kokkos::HIP,
```

Reproducer:
```bash
module load cmake/3.19.3 rocm/5.2.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Hip,Serial --arch=VEGA908 --compiler=hipcc --cxxflags="-O3  " --cxxstandard="17" --with-hip --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=rocblas,rocsparse
```

**Comment by ndellingwood** [comment]
Replacing the `rocblasSetStream` with the API call `rocblas_set_stream` exposed more issues in the `blas/impl/KokkosBlas1_rotm_spec.hpp` and `blas/tpls/KokkosBlas1_rotm_tpl_spec_decl.hpp`
* The template parameters used with the `Rotm` struct partial specializations in `blas/tpls/KokkosBlas1_rotm_tpl_spec_decl.hpp` do not match those of the unification layer in `blas/impl/KokkosBlas1_rotm_spec.hpp`
* The arguments of the function signature of the `rotm` routines in `blas/tpls/KokkosBlas1_rotm_tpl_spec_decl.hpp` do not match those passed to `rocblas_*rotm` and the rocm API https://rocblas.readthedocs.io/en/rocm-4.3.0/functions.html#_CPPv413rocblas_drotm14rocblas_handle11rocblas_intPd11rocblas_intPd11rocblas_intPKd

@lucbv do you have time to take a look, or can you give some guidance on how the `rotm` input args should map to those of the `rocblas_*rotm` API and I can put in a PR with a fix? It's unclear to me if e.g. `d1` and `d2` should map to the `incx` and `incy` args, and such

**Comment by lucbv** [comment]
Yeah, I actually have changes for that in a branch but did not have time to push before going to SC
