### ISSUE TITLE
Timeouts with batched_dla_{cuda,hip} tests - reduce test time

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1595]
The `batched_dla` unit test runtime is consistently near or hitting timeout of 1500 seconds in Cuda and Hip nightly builds. This will need to be reduced before the 4.0 release to reliably pass CI with the Trilinos snapshot.
A couple options to reduce time include splitting the tests in the cpp file into separate cpp files and/or reducing problem sizes if feasible. Other thoughts?

This is also occurring with Trilinos e.g. https://github.com/trilinos/Trilinos/issues/11235 , though for those builds with 3.7.00 I hope the issue can be mitigated with the `RUN_SERIAL` option (assuming tests are run with parallelism)

**Reproducer** (Weaver rhel8 queue, Cuda build):
```bash
module load cuda/11.2.2/gcc/8.3.1 cmake/3.23.1

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-cuda --with-serial --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --arch=Volta70,Power9 --with-cuda-options=enable_lambda --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --cxxstandard=17
```

**Comment by e10harvey** [comment]
Aside from reducing the test input sizes or increasing the timeout, I think splitting the tests up is our only other option.

**Comment by lucbv** [comment]
I would be in favor of splitting the test as it would also reduce the compile/link time for parallel builds.
