### ISSUE TITLE
Why does `values_type` in `CrsMatrix` specify `LayoutRight` when it's a 1D view?

### ISSUE THREAD

**Issue by cwpearson** [kokkos/kokkos-kernels#1610]
https://github.com/kokkos/kokkos-kernels/blob/1efdeee44303910b4e3a64f21c902c7f0a407dc2/sparse/src/KokkosSparse_CrsMatrix.hpp#L429

**Comment by lucbv** [comment]
It's somewhat a mistake, it should really be a `default_layout` generated by our unification logic for ETI.
In practice it is a 1D view so that's not an issue really.

**Comment by jgfouca** [comment]
@lucbv , I fixed this in my recent GMRES PR but I forgot to close this issue, sorry!
