### ISSUE TITLE
Nightly cuda/11.2 test failures with cusparse enabled: sparse_cuda, graph_cuda, wiki_spgemm

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1627]
Test failures with the sparse_cuda, graph_cuda, wiki_spgemm began with cuda/11.2 builds on Power9+Volta70 with cusparse and cublas tpls enabled, some likely related to merge of #1618 

**Test failure snips**:
graph_cuda
```
03:41:57 [ RUN      ] cuda.graph_random_graph_coarsen_double_int_int_TestExecSpace
03:41:57 unknown file: Failure
03:41:57 C++ exception with description "cusparseSpGEMM_compute( h->cusparseHandle, h->opA, h->opB, &alpha, h->descr_A, h->descr_B, &beta, h->descr_C, h->scalarType, CUSPARSE_SPGEMM_DEFAULT, h->spgemmDescr, &h->bufferSize4, h->buffer4) error( CUSPARSE_STATUS_INSUFFICIENT_RESOURCES): insufficient resources /home/jenkins/weaver-new/workspace/KokkosKernels_Weaver_Cuda_Serial_cuda_1122_gcc_831_cusparse_cublas/kokkos-kernels/sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_decl.hpp:275" thrown in the test body.
03:41:57 [  FAILED  ] cuda.graph_random_graph_coarsen_double_int_int_TestExecSpace (1300 ms)
03:41:57 [ RUN      ] cuda.graph_grid_graph_coarsen_double_int_int_TestExecSpace
03:41:57 cudaFree(arg_alloc_ptr) error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/jenkins/weaver-new/workspace/KokkosKernels_Weaver_Cuda_Serial_cuda_1122_gcc_831_cusparse_cublas/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp:334
03:41:57 Backtrace:
03:41:57                       [0x10874964]
03:41:57                       [0x1086b804]
03:41:57                       [0x1086b8f8]
03:41:57                       [0x1087c7fc]
03:41:57                       [0x10877bc0]
03:41:57                       [0x10877cb0]
03:41:57                       [0x10877d50]
03:41:57                       [0x103e3560]
03:41:57                       [0x103e35b0]
03:41:57                       [0x103e3650]
03:41:57                       [0x10874674]
03:41:57                       [0x1008fde0]
03:41:57                       [0x1008fe34]
03:41:57                       [0x100a8e6c]
03:41:57                       [0x100a99fc]
03:41:57                       [0x10089314]
03:41:57                       [0x10015bac]
03:41:57                       [0x10833d40]
03:41:57                       [0x1082c670]
03:41:57                       [0x108073b0]
03:41:57                       [0x10807f14]
03:41:57                       [0x10808978]
03:41:57                       [0x10811ee0]
03:41:57                       [0x108356ac]
03:41:57                       [0x1082dcc8]
03:41:57                       [0x10810538]
03:41:57                       [0x100134dc]
03:41:57                       [0x100128f8]
03:41:57                   [0x200016684078]
03:41:57 __libc_start_main [0x200016684264]
```

sparse_cuda
```
03:43:56 [ RUN      ] cuda.sparse_spgemm_jacobi_double_int_int_TestExecSpace
03:43:56 cudaStreamSynchronize(stream) error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/jenkins/weaver-new/workspace/KokkosKernels_Weaver_Cuda_Serial_cuda_1122_gcc_831_cusparse_cublas/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:144
03:43:56 Backtrace:
03:43:56                       [0x11d7d1f4]
03:43:56                       [0x11d73ef4]
03:43:56                       [0x11d73fe8]
03:43:56                       [0x11d8508c]
03:43:56                       [0x11d86920]
03:43:56                       [0x11d86b18]
03:43:56                       [0x11503f30]
03:43:56                       [0x11500eac]
03:43:56                       [0x102d2880]
03:43:56                       [0x1017e178]
03:43:56                       [0x100cc8a8]
03:43:56                       [0x100233c4]
03:43:56                       [0x11d3cc74]
03:43:56                       [0x11d35b70]
03:43:56                       [0x11d10c00]
03:43:56                       [0x11d11764]
03:43:56                       [0x11d121c8]
03:43:56                       [0x11d1b730]
03:43:56                       [0x11d3e5e0]
03:43:56                       [0x11d370e0]
03:43:56                       [0x11d19d88]
03:43:56                       [0x1001db5c]
03:43:56                       [0x1001cf78]
03:43:56                   [0x200016684078]
03:43:56 __libc_start_main [0x200016684264]
```

wiki_spgemm
```
03:57:46 18/24 Test #18: wiki_spgemm ......................Subprocess aborted***Exception:   1.24 sec
03:57:46 terminate called after throwing an instance of 'std::runtime_error'
03:57:46   what():  cusparseSpGEMM_compute( h->cusparseHandle, h->opA, h->opB, &alpha, h->descr_A, h->descr_B, &beta, h->descr_C, h->scalarType, CUSPARSE_SPGEMM_DEFAULT, h->spgemmDescr, &h->bufferSize4, h->buffer4) error( CUSPARSE_STATUS_INTERNAL_ERROR): internal error /home/jenkins/weaver-new/workspace/KokkosKernels_Weaver_Cuda_Serial_cuda_1122_gcc_831_cusparse_cublas/kokkos-kernels/sparse/tpls/KokkosSparse_spgemm_numeric_tpl_spec_decl.hpp:180
```

**Reproducer** (weaver rhel8 queue):
```bash
module load cuda/11.2.2/gcc/8.3.1 cmake/3.23.1

cm_generate_makefile.bash --with-cuda --with-serial --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --arch=Volta70,Power9 --with-cuda-options=enable_lambda --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=cusparse,cublas --cxxstandard=17
```

@brian-kelley are you able to take a look?

**Comment by brian-kelley** [comment]
Fix is ready in #1628

**Comment by ndellingwood** [comment]
@brian-kelley there are also failures in Stokhos with Cuda builds using CuSparse following merge of #1618 . I tested with #1628 but the failures resume. I'll open a separate issue for that, but listing the tests here for quick reference:

```
   44 - Stokhos_KokkosCrsMatrixUQPCEUnitTest_Cuda_MPI_1 (Failed)
   45 - Stokhos_TpetraCrsMatrixUQPCEUnitTest_Cuda_MPI_4 (Failed)
   52 - Stokhos_KokkosCrsMatrixMPVectorUnitTest_Cuda_MPI_1 (Failed)
```

**Comment by brian-kelley** [comment]
@ndellingwood Could you push a Trilinos branch (to your fork or wherever) that has the needed changes to use KokkosKernels with these patches? I tried applying #1618 as a patch to 3.7.1, but that'll be a pain because it's from before the directory structure change.

Then I tried dropping just KokkosKernels develop into Trilinos develop, but got:
```
/ascldap/users/bmkelle/TrilinosWork/Trilinos/packages/tpetra/core/src/Tpetra_LocalCrsMatrixOperator_decl.hpp:45:10: fatal error: KokkosSparse_CrsMatrix.hpp: No such file or directory
   45 | #include "KokkosSparse_CrsMatrix.hpp"
```
so I assume that you had to work through some CMake changes in KokkosKernels to export the new include directories?

**Comment by ndellingwood** [comment]
@brian-kelley I was using source override to test with kokkos and kokkos-kernels develop branches and Trilinos kokkos-promotion branch, for example these steps to setup

```
git clone -b kokkos-promotion https://github.com/trilinos/Trilinos.git
git clone -b develop https://github.com/kokkos/kokkos.git
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
# Symbolic link to your kokkos and kokkos-kernels repos in Trilinos source directory for source override
cd Trilinos
ln -s <path-to-your-repo>/kokkos kokkos
ln -s <path-to-your-repo>/kokkos-kernels kokkos-kernels
```

and I add these options to my cmake line:
```
  -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
  -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
```

I posted a reproducer script in #1631 for weaver that is hopefully helpful

If you prefer, I can push a temp branch to Trilinos with the develop branches of kokkos and kokkos-kernels snapshot, let me know.


Regarding the error message `fatal error: KokkosSparse_CrsMatrix.hpp: No such file or directory`, you'll need to include the following extra options to your configure:
```
  -DKokkosKernels_ENABLE_SPARSE=ON \
  -DKokkosKernels_ENABLE_GRAPH=ON \
  -DKokkosKernels_ENABLE_BLAS=ON \
  -DKokkosKernels_ENABLE_BATCHED=ON \
```

I talked with Luc a bit about this after triaging, there is some issue with KokkosKernels_ENABLE_BLAS=ON being set in Trilinos outside of kokkos-kernels that messes up the cmake logic to turn on all components by default, we'll get this resolved soon

**Comment by brian-kelley** [comment]
@ndellingwood Little update, I did replicate this but it seems to predate the merge of #1618 (I tried the version right before and it still failed). It's just regular old KokkosSparse::spmv (but with scalar being sacado PCE) giving the wrong answer. I'm going back to a version of develop near 3.7.1 to try to find a working version so I can bisect.

**Comment by ndellingwood** [comment]
@brian-kelley thanks for the update, I must have made a mistake when chasing down the failing commit, sorry for the false alarm regarding #1618

**Comment by ndellingwood** [comment]
@brian-kelley when I was testing, I saw tests pass with this SHA of kokkos-kernels: 93478738cfe5f2ee0c850e59ad678a679ae31ac7 , though I'm second-guessing myself now
That was the last merge commit I saw (via `git log --merges`) prior to the tpl refactor work going in and seeing the failures; a couple other commits on top of that merge commit were 4c06b6cbd14114aee9db80de84d32019236e4d7d and 61ff6a3d14648cc2aa6cd63250bbc1159d581b86
I'm not sure if that is helpful, sorry again for any confusion or noise I added toward triaging this

**Comment by ndellingwood** [comment]
@brian-kelley here's some added info to hopefully help bissect, this is the nightly build when the Stokhos failures began
https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA112_opt/91/
(the previous night failed but that was a spurious occasional kokkos test failing, no source code changes)

The kokkos-kernels changes that went in were https://github.com/kokkos/kokkos-kernels/commit/4c06b6cbd14114aee9db80de84d32019236e4d7d and https://github.com/kokkos/kokkos-kernels/commit/61ff6a3d14648cc2aa6cd63250bbc1159d581b86

I had also rebased the kokkos-promotion branch of Trilinos to bring up-to-date with the develop branch, though there weren't any Stokhos changes in that time frame; the Sacado change was minor api-related (replace use of a static concurrency call with member of default instance, only affecting perf tests though I think)
