### ISSUE TITLE
develop and main have mismatching name for cmake option

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos-kernels#1629]
In the CMake list inside perf_test in **develop** [(see here)](https://github.com/kokkos/kokkos-kernels/blob/develop/perf_test/CMakeLists.txt) I see this: 

```
if(Kokkos_ENABLE_TESTS_AND_PERFSUITE)
```  

while in the same file in the **main** branch [(see here)](https://github.com/kokkos/kokkos-kernels/blob/master/perf_test/CMakeLists.txt) I see this: 
```
if (KokkosKernels_ENABLE_TESTS_AND_PERFSUITE)
```

is that on purpose ?

**Comment by fnrizzi** [comment]
@lucbv

**Comment by lucbv** [comment]
It looks deliberate but I have not read all the details of that code path.
@e10harvey can you recall why we check for `Kokkos_ENABLE_TESTS_AND_PERFSUITE` before enabling performance test in Kokkos Kernels? Do we depend on Kokkos in some way?

**Comment by e10harvey** [comment]
> It looks deliberate but I have not read all the details of that code path.
> @e10harvey can you recall why we check for `Kokkos_ENABLE_TESTS_AND_PERFSUITE` before enabling performance test in Kokkos Kernels? Do we depend on Kokkos in some way?

I do not. Sorry. I remember looking through this once before and being confused.
