### ISSUE TITLE
Potential use of uninitialized memory in KokkosGraph

### ISSUE THREAD

**Issue by jhux2** [kokkos/kokkos-kernels#1646]
The Trilinos nightly valgrind tests show warnings of the type `Conditional jump or move depends on uninitialised value` in 

   - `KokkosGraph::Impl::GraphColor_EB`
   - `KokkosGraph::Impl::GraphColor_EBUMC`, and
   - `KokkosGraph::Impl::D2_MIS_AggregationUMC`.

Here's the dashboard link:  https://testing.sandia.gov/cdash/viewDynamicAnalysis.php?buildid=11440619

**Comment by jhux2** [comment]
@brian-kelley

**Comment by jhux2** [comment]
@brian-kelley Thank you!

**Comment by ndellingwood** [comment]
Cherry-picks of #1528 and #1530 were added to the 3.7.01 fixup PR #1640

**Comment by ndellingwood** [comment]
Thanks @brian-kelley for re-patching to Trilinos; kokkos-kernels changes are merged to develop and updated to master, marking as InDevelop
