### ISSUE TITLE
Nightly compilation errors with OpenMP builds, spmv impl

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1669]
Nightly builds with OpenMP enabled began failing to compile with error:

```
kokkos-kernels/sparse/impl/KokkosSparse_spmv_impl.hpp:522:69: error: cannot call member function ‘int Kokkos::OpenMP::impl_thread_pool_size() const’ without object
```

This is the list of commits from the previous passing state:

## Kokkos:
Git (git https://github.com/kokkos/kokkos.git)

    Restrict KOKKOS_IMPL_SYCL_DEVICE_GLOBAL_SUPPORTED feature macro detection to static libraries ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    CRS: Use Kokkos device function macros rather than duplicating code when compiling for GPU targets ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    CUDA: Convert simple value macro to constexpr ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    CUDA: Fix up comment ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    OpenMPTarget: Be scrupulous about macro naming and undefining ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    ViewLayoutTiled: Be scrupulous about macro naming and undefining ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    HIP: Drop obsolete macro definition ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    Try using oneAPI 2023.0.0 in SYCL+Cuda CI (#5813) ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    Add non-standard `rsqrt` math function (#5644) ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    Fix unprefixed macros on KokkosExp_Host_IterateTile.hpp ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    Refactor OpenMPTarget backend (#5726) ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    Fixup typo `#ifdef KOKKOS_ENABLE_DEPRECA{R -> T}ED_CODE_3` ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    Set native flags according to CMAKE_SYSTEM_PROCESSOR (#5831) ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    Fix flag passed to NVHPC when `Kokkos_ARCH_NATIVE` is `ON` ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    Make OpenMP::concurrency and impl_thread_pool_size non-static (#5836) ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))

## KokkosKernels:
Git (git https://github.com/kokkos/kokkos-kernels.git)

    Do not use Kokkos::Impl::clock_tic, prefer std::chrono to get a random seed ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    Drop pre Kokkos 3.6 workaround ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    Add Impl::are_integral_v helper variable template ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))
    Hands off Kokkos::Impl::are_integral ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc820_OpenMP_Threads_Serial-dbg/113/changes#detail))

Possibly a change in this PR created an incompatibility?  Make OpenMP::concurrency and impl_thread_pool_size non-static (#5836)

**Reproducer** (Blake):
```bash
module load cmake/3.19.3 gcc/8.2.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=OpenMP --arch=SKX --compiler=g++ --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17"  --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --debug
```

**Comment by lucbv** [comment]
PR #1666 is actually looking into this and should provide a fix

**Comment by ndellingwood** [comment]
Thanks @lucbv ! I hadn't caught up on github notifications to see that
