### ISSUE TITLE
KokkosGraph_Distance2Color_impl.hpp warning

### ISSUE THREAD

**Issue by vbrunini** [kokkos/kokkos-kernels#1682]
I'm seeing this warning with recent clang versions (as well as rocm compilers based on recent clang versions):
```
/path/to/include/KokkosGraph_Distance2Color_impl.hpp:262:12: warning: variable 'total_time' set but not used [-Wunused-but-set-variable]
    double total_time = 0.0;
```

**Comment by lucbv** [comment]
@vbrunini the line of code the compiler is complaining about does not appear to be the same as what I can see [here](https://github.com/kokkos/kokkos-kernels/blob/747bb9303cb978339f717c4c3bddfa05ce5a519c/graph/impl/KokkosGraph_Distance2Color_impl.hpp#L262).
I see on the other hand that the version in Trilinos might have the issue you are pointing at but this should disappear with the release of Kokkos Kernels 4.0.0

**Comment by ndellingwood** [comment]
This should be resolved, please reopen if needed
