### ISSUE TITLE
The KokkosGraph_triangle.cpp of perf_test is not working for OPENMP

### ISSUE THREAD

**Issue by HanjiangWu313** [kokkos/kokkos-kernels#1684]

**Comment by lucbv** [comment]
Hi @HanjiangWu313, can you be a little more descriptive in your issue?
What versions of Kokkos and Kokkos Kernels are you using?
How did you configure them?
What compiler did you use?
What input parameters did you run the test with?
What output did you get on screen, if any?

**Comment by HanjiangWu313** [comment]
Thank you for the immediate response! I just git the repo from master branch today and follow the wiki and the previous issues to setup the run for kokkos-kernel. Everything is working smoothly until I found there is a comment in:  perf_test/graph/CMakeLists.txt saying that the triangle counting might be working for GPUs. However, I uncommented it (because I just want to use it for CPUs) and "make" all the files and found it was not able to compile successfully. 
![Capture](https://user-images.githubusercontent.com/118569970/218939599-bf0f1063-fe4e-47b4-b203-8bfba2b04d5c.PNG)

**Comment by HanjiangWu313** [comment]
@lucbv could you help me on this? Thank you so much.

**Comment by HanjiangWu313** [comment]
@lucbv Thank you. I will track the issue on that thread.

**Comment by brian-kelley** [comment]
@HanjiangWu313 Now that PR #1752 is merged, this performance test is re-enabled in CMake and it behaves correctly on all non-GPU backends, including OpenMP.
