### ISSUE TITLE
Batched BLAS enhancement

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#170]
As worked on by @kyungjoo-kim and submitted in PR #160 

Added features:

    remove AVX tags and unify with SIMD only
    reduce the number of subviewing and use assign_data
    performance test on gpus
    relation, logical, math operators enhancement

**Comment by kyungjoo-kim** [comment]
@ndellingwood Is this for a tracking purpose ? Do I need to provide any additional things ?
