### ISSUE TITLE
Nightly build failures in blas1 unit tests: error: cannot convert ‘Kokkos::complex<double>’ to ‘const mag_type’ {aka ‘const double’} in initialization

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1708]
Nightly build failures began to occur in blas1 unit tests with message `error: cannot convert ‘Kokkos::complex<double>’ to ‘const mag_type’ {aka ‘const double’} in initialization`

**Error snip**:
```
In file included from <https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/ws/kokkos-kernels/blas/unit_test/Test_Blas.hpp>:57,
                 from <https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/ws/kokkos-kernels/blas/unit_test/backends/Test_Serial_Blas.cpp>:20:
<https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/ws/kokkos-kernels/blas/unit_test/Test_Blas1_team_mult.hpp>: In instantiation of ‘void Test::impl_test_team_mult_mv(int, int) [with ViewTypeA = Kokkos::View<Kokkos::complex<double>*, Kokkos::LayoutLeft, Kokkos::Serial>; ViewTypeB = Kokkos::View<Kokkos::complex<double>**, Kokkos::LayoutLeft, Kokkos::Serial>; ViewTypeC = Kokkos::View<Kokkos::complex<double>**, Kokkos::LayoutLeft, Kokkos::Serial>; Device = Kokkos::Serial]’:
<https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/ws/kokkos-kernels/blas/unit_test/Test_Blas1_team_mult.hpp>:368:39:   required from ‘int test_team_mult_mv() [with ScalarA = Kokkos::complex<double>; ScalarB = Kokkos::complex<double>; ScalarC = Kokkos::complex<double>; Device = Kokkos::Serial]’
<https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/ws/kokkos-kernels/blas/unit_test/Test_Blas1_team_mult.hpp>:453:61:   required from here
<https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/ws/kokkos-kernels/blas/unit_test/Test_Blas1_team_mult.hpp>:252:29: error: cannot convert ‘Kokkos::complex<double>’ to ‘const mag_type’ {aka ‘const double’} in initialization
  252 |       a * max_val * max_val * eps;
      |       ~~~~~~~~~~~~~~~~~~~~~~^~~~~
      |                             |
      |                             Kokkos::complex<double>
```

Failure began following merge of one of these commits:

**kokkos:**
Unwire initializing/finalizing Kokkos lock arrays — [dalg24](https://jenkins-son.sandia.gov/user/dalg24/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail0)
Remove Cuda and HIP lock arrays altogether — [dalg24](https://jenkins-son.sandia.gov/user/dalg24/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail1)
Implement `rot{l,r}` function templates — [dalg24](https://jenkins-son.sandia.gov/user/dalg24/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail2)
Do not bother with sycl::rotate — [dalg24](https://jenkins-son.sandia.gov/user/dalg24/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail3)
Drop (unused) HBW lock array — [dalg24](https://jenkins-son.sandia.gov/user/dalg24/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail4)
Drop host lock array — [dalg24](https://jenkins-son.sandia.gov/user/dalg24/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail5)
Remove misplaced and commented host lock array code in OpenMPTarget backend — [dalg24](https://jenkins-son.sandia.gov/user/dalg24/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail6)

**kokkos-kernels:**
Test mixed scalars: more fixes related to mixed scalar tests — [Luc Berger-Vergiat (-EXP)](https://jenkins-son.sandia.gov/user/lberge/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail7)
Tested mixed scalars: removing temporary output — [Luc Berger-Vergiat (-EXP)](https://jenkins-son.sandia.gov/user/lberge/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail8)
View::Rank -> View::rank — [pearson](https://jenkins-son.sandia.gov/user/pearson/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail9)
test mixed scalars: incorporate Evan's comments — [Luc Berger-Vergiat (-EXP)](https://jenkins-son.sandia.gov/user/lberge/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail10)
test mixed scalars: adding more comments and sending msg to cerr — [Luc Berger-Vergiat (-EXP)](https://jenkins-son.sandia.gov/user/lberge/) / [detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Blake_Gcc920_OpenMP_Threads_Serial-dbg/62/changes#detail11)

**Reproducer (Blake)**:
```bash
source /etc/profile.d/modules.sh
module purge
module load cmake/3.19.3 gcc/9.2.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Serial --arch=SKX --compiler=g++ --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --no-examples   --debug
```

**Comment by ndellingwood** [comment]
@lucbv was there a change with the mixed scalar testing PR that may have tripped this?

**Comment by ndellingwood** [comment]
Looks like a PR is in: #1706

**Comment by lucbv** [comment]
Correct, I'm waiting for the osx-ci to return clean and I can merge that PR, sorry for the temporary bug introduction x)

**Comment by ndellingwood** [comment]
Thanks @lucbv ! Closing this issue
