### ISSUE TITLE
batched_gemm_cuda test frequent timeouts

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1730]
The `batched_gemm_cuda` is more frequently hitting the timeout threshold of 1500 sec (the test has always been a long test but stayed just below the timeout threshold), for example in release builds with cuda/11.2+gcc/8.3.0 on Volta70+Power9 arch

Can problem size(s) be reduced to cut the test time down?

**Comment by e10harvey** [comment]
@ndellingwood: I am seeing runtimes of ~282 s via:
```
$ time ./batched/dense/unit_test/KokkosKernels_batched_gemm_cuda
<snip>
[----------] 88 tests from Cuda (282513 ms total)

[----------] Global test environment tear-down
[==========] 88 tests from 1 test case ran. (282514 ms total)
[  PASSED  ] 88 tests.

real	4m43.221s
user	171m23.001s
sys	7m5.391s
```

I built this binary via:
```
../scripts/cm_test_all_sandia --spot-check cuda/11.2.2 --kokkos-path=../../kokkos --kokkoskernels-path=../ --arch=Volta70 --cxxstandard=17
```

I opened #1737 in an effort to reduce this tests runtime.

In doing this, I noticed that the target `Test_Cuda_Batched_GEMM.cpp.o` is taking >= 10 minutes to compile (perhaps mostly during the link stage)! @ndellingwood: do you have experience triaging and improving compile times? I suspect that ETI-ing this host-level batched function could help. Is there anything else that could be done to reduce the compile time?

**Comment by ndellingwood** [comment]
Thanks for the update @e10harvey !

Yeah, that file does take quite a bit of time to compile and link, some of the perf tests are quite expensive as well (`KokkosBlas3_gemm_perf_test` in particular). I don't have any definite guidance at the moment to improve the compile and link times (minus splitting apart tests into separate compilation units when applicable), sorry, I'll get back to you if I find something helpful

**Comment by e10harvey** [comment]
@ndellingwood: Were the timeouts reported here resolved?

**Comment by ndellingwood** [comment]
@e10harvey yes, thanks! This is resolved, I'll drop the BlocksPromotion label and mark InDevelop

**Comment by e10harvey** [comment]
Closing as complete.
