### ISSUE TITLE
BatchedTeamGemv fails with ViewType = Kokkos::DynRankView<>

### ISSUE THREAD

**Issue by japlews** [kokkos/kokkos-kernels#1764]
BatchedTeamGemv is now incompatible with `Kokkos::DynRankView<>` because of static assertions on View rank. See [KokkosBatched_Gemv_Team_Impl.hpp:48](https://github.com/kokkos/kokkos-kernels/blob/b9c1bab7a8ae7c9413ad09f612f9011ff04a819e/batched/dense/impl/KokkosBatched_Gemv_Team_Impl.hpp#L48):

```
    static_assert(AViewType::Rank == 3,
                  "Batched TeamGemv requires rank-3 A matrix (use "
                  "KokkosBlas::TeamGemv for regular rank-2 matrix)");
```

I can work around this issue by using the `Batched_Gemm` interface instead (which does not require compile-time View dimensions for some reason), but I'm wondering if there are plans to continue support for `DynRankView`?

Thanks!
Julia

**Comment by kliegeois** [comment]
@lucbv do you have an opinion about this support? I don't have experience with DynRankView.

**Comment by e10harvey** [comment]
@japlews: While the functor-level interfaces (https://kokkos-kernels.readthedocs.io/en/latest/developer/apidocs/batched_dense.html#gemm) do not check the compile-time View dimensions, our host-level BatchedGemm function does:
[/// \brief Non-blocking solve of general matrix multiply on a batch of](https://github.com/kokkos/kokkos-kernels/blob/1491bd433323ec9a8e1e9626adcc9e0fed6a301a/batched/dense/src/KokkosBatched_Gemm_Decl.hpp#L324-L381)

**Comment by japlews** [comment]
Thanks for the information. Would it be possible to support an API with conditional compile- and run-time checks based on the existence of a compile-time View rank? The Trilinos/Intrepid2 library is the use case in question here, where the API-level array types they rely on are almost all Kokkos::DynRankViews... Or otherwise something more complex that is duck-typed like a Kokkos::DynRankView.

**Comment by e10harvey** [comment]
@japlews: For this use-case, `Rank` in `ViewType::Rank` would not exist? If so, I think this can be supported via sizeof and SFINAE.

**Comment by japlews** [comment]
@e10harvey, exactly. DynRankViews have a method called `ViewType::rank()` rather than a `ViewType::Rank` based on template parameters. It seems in principle like this would be tractable using `constexpr if` rather than SFINAE. See, for example, the free functions defined at https://github.com/kokkos/kokkos/blob/aa1f48f3172069f212ed2c97b74b786999b26f17/core/src/Kokkos_View.hpp#L1690 and https://github.com/kokkos/kokkos/blob/aa1f48f3172069f212ed2c97b74b786999b26f17/containers/src/Kokkos_DynRankView.hpp#L1302

**Comment by lucbv** [comment]
I am thinking something like this:
```
if constexpr (Kokkos::is_dyn_rank_view<user_type>::value) {
   // runtime check of view.rank();
} else {
   static_assert(user_type::rank == 3)
}
```

**Comment by e10harvey** [comment]
Nice!

**Comment by e10harvey** [comment]
@japlews: A fix for this was merged into `develop` last week, can you please check if that fix resolve this issue?

**Comment by japlews** [comment]
@e10harvey, I was able to confirm that my code builds and runs with the fixes. Thanks!

**Comment by e10harvey** [comment]
Closing as complete.
