### ISSUE TITLE
Nightly builds with intel/19.1 on KNL fail in sparse_par_ilut_precond test

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1775]
The nightly intel/19.1.3 build on Voltrino (KNL arch )build began failing in test ` openmp.sparse_par_ilut_precond_double_int_size_t_TestExecSpace` after merge of #1755 

```
02:13:40 [ RUN      ] openmp.sparse_par_ilut_precond_double_int_size_t_TestExecSpace
02:13:40 unknown file: Failure
02:13:40 C++ exception with description "gmres: Relative residual is nan. Terminating solver." thrown in the test body.
02:13:40 [  FAILED  ] openmp.sparse_par_ilut_precond_double_int_size_t_TestExecSpace (1680 ms)
```

**Reproducer** (voltrino, knl queue):
A couple notes:
* Load modules, configure and compile on the login node to avoid potential license issues on the compute node
* Run tests on the knl queue (e.g. `salloc -N 1 -p knl` to grab interactive node)
```
module purge
module load PrgEnv-intel
module load craype-mic-knl
module load eproxy #for srun
module load cmake/3.16.2

${KOKKOSKERNELS_PATH}/cm_generate_makefile.bash --with-openmp --compiler=icpc --arch=KNL --kokkos-path=${KOKKOS_PATH} --kokkoskernels-path=${KOKKOSKERNELS_PATH} --cxxstandard=17 --cxxflags="-diag-disable=1011,-diag-disable=869" --disable-perftests

```

@jgfouca can you investigate?

**Comment by jgfouca** [comment]
@ndellingwood , ah, i bet the high thread count on KNL is exposing the same issue I saw on GPU, which is obv very high thread count. I will look.

**Comment by jgfouca** [comment]
@ndellingwood , ouch, I just requested voltrino access and:

```
The following resources require additional approvals (up to two weeks):

Activate
VOLTRINO
```

Is this issue urgent?

**Comment by ndellingwood** [comment]
@jgfouca thanks for taking a look when the access is approved! This isn't urgent, so the potential timeframe for approval isn't an issue.

**Comment by ndellingwood** [comment]
@jgfouca the failure appears to be random; last night the test on Voltrino passed with KNL, but failed on HSW. I wanted to let you know so that when you get access to investigate, the test failure may not occur with every run

**Comment by jgfouca** [comment]
@ndellingwood , yes, the async update issue is random (involves race conditions when team count is large).
