### ISSUE TITLE
Nightly test timeout sparse_spgemm_kokkos_complex_double_int_int: cuda/11.2 with cusparse and cublas tpls enabled

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1777]
The cuda/11.2 nightly build on Power9+Volta70 with cusparse and cublas tpls failed with timeout in the `Cuda.sparse_spgemm_kokkos_complex_double_int_int_TestExecSpace` unit test.

The only change from the previous night was merge of #1742 . @brian-kelley can you investigate? 

**Reproducer** (weaver rhel8 queue):
```
module load cuda/11.2.2/gcc/8.3.1  cmake/3.23.1

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-cuda --with-serial --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --arch=Volta70,Power9 --with-cuda-options=enable_lambda --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=cusparse,cublas --cxxstandard=17
```

**Comment by brian-kelley** [comment]
@ndellingwood I'm able to replicate this, and it seems to be somewhat random. For some reason the debugger can't give me a backtrace at the point where it hangs, but I'm looking into it.
