### ISSUE TITLE
KokkosKernels Unit Test Teuchos Dependency

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos-kernels#18]
I removed most of the Teuchos dependencies that are related to UnitTestHarness, and replaced them with gtest. 

However, MV unit tests depend on Teuchos MPI. Are they supposed to move to Tpetra? They are the last bits before removing the Teuchos dependency.

**Comment by crtrott** [comment]
I think we should get rid of the MPI part. Kokkos Kernels is not supposed to know about MPI.

**Comment by mhoemmen** [comment]
> However, MV unit tests depend on Teuchos MPI. Are they supposed to move to Tpetra? They are the last bits before removing the Teuchos dependency.

Do they actually use MPI, or do they just take a comm?  If the latter, we can get rid of that.  If the former, we'll have to decide whether we want them to use MPI directly (and thus making KokkosKernels have an optional MPI dependency) or just strip out those tests.

**Comment by mndevec** [comment]
They create their own Comm. It should be easy to remove all Comm related stuff.
I wanted to bring to your attention as there won't be any test running MV with MPI, which I assumed the intended case. We can remove Teuchos Comm from those tests, but still we need to add tests with MPI to Tpetra.

**Comment by mhoemmen** [comment]
@mndevec wrote:
> ... but still we need to add tests with MPI to Tpetra.

Those tests exist, insofar as Tpetra tests CrsMatrix's sparse matrix-vector multiply.  Thus, I think it's fair to remove the MPI dependency from those tests in KokkosKernels, if @crtrott agrees.
