### ISSUE TITLE
Document that `RandCsMatrix::{get_vals, get_ids}` need to be coupled with a `get_nnz`-long subview

### ISSUE THREAD

**Issue by cwpearson** [kokkos/kokkos-kernels#1802]
https://github.com/kokkos/kokkos-kernels/blob/4b731c4fb1753f525515590ca60f7ca20edba545/test_common/KokkosKernels_TestUtils.hpp#L690-L691

If you use these directly, they provide the wrong number of non-zeros. You need to get a subview of the appropriate length.

**Comment by e10harvey** [comment]
@cwpearson: I also discovered this and addressed it in https://github.com/kokkos/kokkos-kernels/pull/1686/files#diff-4b273c749247dc0f15e60c360e769521bd0b7f754338dab3e6cd15f1dd900fffR687.

**Comment by cwpearson** [comment]
Resolved in https://github.com/kokkos/kokkos-kernels/pull/1686
