### ISSUE TITLE
github-DOCS: Improve output

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos-kernels#1804]
Right now the github-DOCS CI check uses the default doxygen output. Warnings get placed where they appear in the output and tend to get lost in the many lines of output. At the bottom of the output (which is immediately visible to the PR author when trying to find the error) there is a generic `Error 1`. This makes it difficult to parse and locate the culprit of the failure. To resolve this issue:

1. Summarize the relevant warnings and errors at the bottom on console
2. Note that warnings as errors is enabled.

**Comment by cwpearson** [comment]
This has annoyed me more than once!

**Comment by e10harvey** [comment]
Closing as complete.
