### ISSUE TITLE
Disable ETI during TPL builds?

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos-kernels#1846]
Currently, ETI is enabled by default. If a tpl is enabled for CI or nightly testing, all ETI object files are created but many of the ETI'd symbols are never linked against. Looking at the kernels logger shows that some ETI'd functions are still called by the tests, for example:
```
$ grep 'ETI' armpl-21.1.0-OpenMP-release.test.log  | grep Entering | sort | uniq
5: KokkosP: Entering profiling region: KokkosBlas::abs[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::axpby[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::dot[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::gemv[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::iamax[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::mult[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::nrm1[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::nrm2[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::nrm2w[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::nrminf[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::reciprocal[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::rot[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::rotmg[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::scal[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::sum[ETI]
5: KokkosP: Entering profiling region: KokkosBlas::update[ETI]
7: KokkosP: Entering profiling region: KokkosBlas::axpby[ETI]
7: KokkosP: Entering profiling region: KokkosBlas::dot[ETI]
7: KokkosP: Entering profiling region: KokkosBlas::mult[ETI]
7: KokkosP: Entering profiling region: KokkosBlas::scal[ETI]
```

The above functions evidently do not support armpl TPL invocations. After disabling both eti and test eti only, these functions would be inlined into the unit tests and `noETI` rather than `ETI` would be seen above; this should reduce build times.

Despite all the functions being ETI'd, only the TPL specializations (for functions that supports TPLs) are invoked at runtime since the linker finds those symbols first in the `Test*.o` files before searching `libkokkoskernels.a`. The symbols do not conflict with the ETI'd symbols in `libkokkoskernels.a` since the template specializations specify `<...tpl_spec_avail = true, eti_spec_avail = false>` and `<...tpl_spec_avail = true, eti_spec_avail = true>` in Test*.o and only `<...tpl_spec_avail = false, eti_spec_avail = true>` in `libkokkoskernels.a`.

**Comment by e10harvey** [comment]
@lucbv: this was discussed during the meeting last week. Would you please weigh in here?

**Comment by lucbv** [comment]
I am against that mostly because I would like to support runtime dispatch to TPL/native implementation which will require to have both version compiled.

**Comment by e10harvey** [comment]
Closing as complete.
