### ISSUE TITLE
Possible error in ParILUT documentation

### ISSUE THREAD

**Issue by jhux2** [kokkos/kokkos-kernels#1851]
In the read-the-docs [documentation for ParILUT](https://kokkos-kernels.readthedocs.io/en/latest/developer/apidocs/sparse.html#par-ilut), there's this warning:

> doxygenclass: Cannot find class “KokkosSparse::PAR_ILUTHandle” in doxygen xml output for project “KokkosKernels” from directory: /home/docs/checkouts/readthedocs.org/user_builds/kokkos-kernels/checkouts/latest/docs/doxygen//xml

If this is fixed, would there then be a description of the options exposed to a downstream user of ParILUT?

@jgfouca

**Comment by jgfouca** [comment]
Hi @jhux2 , sorry about that warning. I've pinged @e10harvey to look at the RTD generator.

If you look at the handle header, you will see all the doxygen for this file. The header lives here:
`sparse/src/KokkosSparse_par_ilut_handle.hpp`

The only stuff you need worry about as a user are these settings:

```
  // User inputs                                                                                                                                                                                                                
  size_type max_iter;  /// Hard cap on the number of par_ilut iterations                                                                                                                                                        
  float_t residual_norm_delta_stop;  /// When the change in residual from                                                                                                                                                       
                                     /// iteration to iteration drops below                                                                                                                                                     
                                     /// this, the algorithm will stop (even if                                                                                                                                                 
                                     /// max_iters has not been hit)                                                                                                                                                            
  float_t fill_in_limit;             /// The threshold for the ILU factorization                                                                                                                                                
  bool async_update;  /// Whether compute LU factors should do asychronous                                                                                                                                                      
                      /// updates. When ON, the algorithm will usually converge                                                                                                                                                 
                      /// faster but it makes the algorithm non-deterministic.                                                                                                                                                  
  bool verbose;       /// Print information while executing par_ilut 
```

All of those are settable via handle creator:
`kh.create_par_ilut_handle(...)`

And via setters on the handle, e.g. `set_max_iter`.

**Comment by jhux2** [comment]
@jgfouca Thanks for the quick response.

> If you look at the handle header, you will see all the doxygen for this file. The header lives here:
sparse/src/KokkosSparse_par_ilut_handle.hpp

To simplify maintenance, I'd prefer the Ifpack2 interface and doxygen to direct a user to the Kokkos-Kernels documentation for the individual options.  Otherwise, the Ifpack2 documentation might quickly get out-of-date.

**Comment by e10harvey** [comment]
I see that the CD automation published the fix: https://kokkos-kernels.readthedocs.io/en/latest/developer/apidocs/sparse.html#_CPPv4I000000EN12KokkosSparse12Experimental14PAR_ILUTHandleE.

Closing as complete.
