### ISSUE TITLE
Batched Sparse perf tests write to the source tree during build

### ISSUE THREAD

**Issue by cwpearson** [kokkos/kokkos-kernels#1898]
https://github.com/kokkos/kokkos-kernels/blob/3dce1e3558c6efa1c1083d8cb3172813ab1e50bf/perf_test/batched/sparse/CMakeLists.txt#L6-L8

The source tree should be read-only during a build.
The purpose of this seems to be to tell a couple of scripts where the binary tree is so they can find the perf test executables.

**Comment by lucbv** [comment]
Resolved with #1904
