### ISSUE TITLE
Linking error in unit-test when compiling with Kokkos_ENABLE_CUDA_UVM=ON

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#1910]
@ndellingwood this seem to be related to how the unit-test are handling execution space/memory space/device and what was enabled by our ETI.
This could be fixed with some macros and std::conditional so not too hard to fix but requires to check every individual unit-test until all the linking errors are gone : (

**Comment by ndellingwood** [comment]
@lucbv this follows from the changes in #1835 . When setting `Kokkos_ENABLE_CUDA_UVM=ON ` we now need to explicitly set `KokkosKernels_INST_MEMSPACE_CUDAUVMSPACE=ON` (before #1835 this was set by default for UVM=ON)

**Comment by lucbv** [comment]
I think there is a fix that we can do internally that would avoid link time errors for users, we should try to implement it until Kokkos fully removes `Kokkos_ENABLE_CUDA_UVM`. Let's talk about it tomorrow at the stand-up
