### ISSUE TITLE
Add jenkins test with KOKKOS_DEBUG is turned on

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos-kernels#196]
We seem to miss couple failures when Kokkos Debug is on: https://github.com/trilinos/Trilinos/issues/2471

That would be better if we have jenkins test with Kokkos Debug.

**Comment by ndellingwood** [comment]
Added this [Cuda_OpenMP debug Jenkins job](https://jenkins-son.sandia.gov/view/KokkosKernels/job/KokkosKernels_White_CudaOpenMP_cuda_92_gcc_720-debug/)
