### ISSUE TITLE
Generated CPP files moving includes inside the ifdef's

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos-kernels#199]
As suggested by @ibaned : many of the generated cpp files are not compiled, yet they have includes that are not protected by the ifdef macros.

For example: 
https://github.com/kokkos/kokkos-kernels/blob/master/src/impl/generated_specializations_cpp/abs/KokkosBlas1_abs_eti_spec_inst_Kokkos_complex_double__LayoutLeft_Cuda_CudaSpace.cpp

Moving "#ifdef" macros outside so that they wrap "#include ..."  might reduce the compile time further.

**Comment by srajama1** [comment]
Can we change the generator too ?

**Comment by crtrott** [comment]
Yeah we should change the generator. I look into it.

**Comment by ndellingwood** [comment]
PR #203
