### ISSUE TITLE
Nightly Blas unit test failures with llvm/14, llvm/15

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#2005]
The following Blas unit tests fail in Serial builds with debugging when compiled with llvm/15.0.7, openblas/0.3.23 

**KokkosKernels_blas_serial**
```
./blas/unit_test/KokkosKernels_blas_serial --gtest_filter=serial.asum_complex_double
[ RUN      ] serial.asum_complex_double
/home/ndellin/kokkos-kernels/test_common/KokkosKernels_TestUtils.hpp:159: Failure
Expected: ((double)AT1::abs(val1 - val2)) <= ((double)AT3::abs(tol)), actual: 119.541 vs 1.19541e-05
/home/ndellin/kokkos-kernels/test_common/KokkosKernels_TestUtils.hpp:159: Failure
Expected: ((double)AT1::abs(val1 - val2)) <= ((double)AT3::abs(tol)), actual: 119.541 vs 1.19541e-05
[  FAILED  ] serial.asum_complex_double (54 ms)

...

./blas/unit_test/KokkosKernels_blas_serial --gtest_filter=serial.nrm1_complex_double
[ RUN      ] serial.nrm1_complex_double
/home/ndellin/kokkos-kernels/test_common/KokkosKernels_TestUtils.hpp:159: Failure
Expected: ((double)AT1::abs(val1 - val2)) <= ((double)AT3::abs(tol)), actual: 119.541 vs 1.19541e-05
/home/ndellin/kokkos-kernels/test_common/KokkosKernels_TestUtils.hpp:159: Failure
Expected: ((double)AT1::abs(val1 - val2)) <= ((double)AT3::abs(tol)), actual: 119.541 vs 1.19541e-05
[  FAILED  ] serial.nrm1_complex_double (8 ms)
```

**Reproducer** (blake "all" queue):
```bash
salloc -N 1 -p all

module purge
module load cmake llvm openblas/0.3.23

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-serial --compiler=clang++ --with-tpls=blas,lapack --debug --with-scalars=complex_double,double
```

llvm/15.0.7 is the only version available on blake, but I'll test with different versions on another machine

**Comment by ndellingwood** [comment]
I tested and reproduced this with the following in debug builds:

* llvm/15.0.7 + openblas/0.3.23 (blake)
* llvm/15.0.7 + openblas/0.3.20 (blake)
* sems-clang/14.0.6 + sems-openblas/0.3.21 (kokkos-dev-2)
* sems-clang/14.0.6 , no tpls

The tests pass with sems-clang/11.0.1

The tests also pass in the cases above with debugging disabled

**Comment by ndellingwood** [comment]
For reference, the test seems to fail for non-power-of-two cases, https://github.com/kokkos/kokkos-kernels/blob/f26fbca1b3f0543516f972010bae2f35f00adb4f/blas/unit_test/Test_Blas1_asum.hpp#L66 ; I modified the test to run with 14 (fail) and 16 (pass); for the failing cases `asum` returned a value of 0

**Comment by cwpearson** [comment]
I have reproduced thin on blake - vectors of length `[1, 15]` fail. Everything else (`0`, `16` and larger) work.

I can't reproduce it on my workstation with the same LLVM and OpenBLAS.

**Comment by lucbv** [comment]
Maybe try the latest OpenBLAS to see if the test passes with it? Alternatively you can try BLIS

**Comment by ndellingwood** [comment]
I noticed the test failures with sems-clang/14.0.6 without use of tpls (in addition to failures with various versions of openblas pre-0.3.25), just in case OpenBlas is a red herring

**Comment by ndellingwood** [comment]
Also, building with debug mode was a common factor, the tests passed for me with release mode with sems-clang/14.0.6 and llvm/15.0.7
The tests were not problematic with older clang e.g. sems-clang/11.0.1 (the tests passed in release and debug mode)

**Comment by cwpearson** [comment]
I compiled a few of my own OpenBLAS on Blake (`TARGET=SKYLAKEX`, I couldn't use Sapphire Rapids due to the compiler being too old, I think).

| Version | Tests Passed? |
|-|-|
| 0.3.23 | No |
| 0.3.25 | No |
| 0.3.28 | Yes | 

I couldn't get the tests to fail with TPLs disabled.

**Comment by cwpearson** [comment]
Openblas does define a version macro in `openblas_config.h` (only if it's installed, not just built). However, the version macro is like this...

```c++
#define OPENBLAS_VERSION " OpenBLAS 0.3.26 "
```

It's possible to write a compile-time string parsing thing in C++ 17 to make a constexpr comparison with this version:

```c++
struct OpenBlasVersion {
    int major;
    int minor;
    int patch;
};

// std::from_chars not constexpr until C++23
constexpr int parse_int(std::string_view sv) {
    int result = 0;
    for (char c : sv) {
        if (c >= '0' && c <= '9') {
            result = result * 10 + (c - '0');
        } else {
            break;
        }
    }
    return result;
}

constexpr Version parse_version(std::string_view sv) {
    Version v{0, 0, 0};
    size_t start = sv.find_first_of("0123456789");
    if (start == std::string_view::npos) return v;

    size_t end = sv.find_first_not_of("0123456789", start);
    v.major = parse_int(sv.substr(start, end - start));

    start = sv.find_first_of("0123456789", end);
    if (start == std::string_view::npos) return v;

    end = sv.find_first_not_of("0123456789", start);
    v.minor = parse_int(sv.substr(start, end - start));

    start = sv.find_first_of("0123456789", end);
    if (start == std::string_view::npos) return v;

    end = sv.find_first_not_of("0123456789", start);
    v.patch = parse_int(sv.substr(start, end - start));

    return v;
}

constexpr bool operator>=(const Version& lhs, const Version& rhs) {
    return std::tie(lhs.major, lhs.minor, lhs.patch) >= std::tie(rhs.major, rhs.minor, rhs.patch);
}

template <size_t N>
constexpr bool check_openblas_version_gte(const char (&version)[N], const Version& min_version) {
    return parse_version(std::string_view(version, N - 1)) >= min_version;
}

// used  like this
if constexpr (check_openblas_version_gte(OPENBLAS_VERSION, Version{0.3.26})) {}
```

However, I think we'd have to have a separate configure-time check to see if our host blas is OpenBLAS or not

**Comment by cwpearson** [comment]
And/or a workaround like this:

```c++
template <>
double HostBlas<std::complex<double> >::asum(KK_INT n, const std::complex<double>* x, KK_INT x_inc) {

  // workaround for clang 15.0.7 + openblas 0.3.23 + sapphire rapids
  // this combo doesn't work for vectors < 16 long, so copy into a vector of length 16
  // and put zeros in the rest
  thread_local static std::complex<double> scratch[16];

  const std::complex<double> *p;

  if (n > 0 && n < 16) {
    for (int i = 0; i < 16; ++i) {
      if (i < n) {
        scratch[i] = x[i];
      } else {
        scratch[i] = std::complex<double>{0,0};
      }
    }
    p = scratch;
    n = 16;
  } else {
    p = x;
  }

  std::cerr << __FILE__ << ":" << __LINE__ << " " << n << " " << x << " " << x_inc
            << " real="<< x->real() << " imag=" << x->imag()
            << "\n";
  return F77_FUNC_DZASUM(&n, p, &x_inc);

}
```
