### ISSUE TITLE
Sycl nightly build fails to configure - Cannot find source file: backends/Test_SYCL_Lapack.cpp

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#2022]
The nightly Sycl build is failing to configure following merge of #1985 , with output:

```
23:30:21 CMake Error at cmake/kokkoskernels_tribits.cmake:154 (ADD_EXECUTABLE):
23:30:21   Cannot find source file:
23:30:21 
23:30:21     backends/Test_SYCL_Lapack.cpp
23:30:21 
23:30:21   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
23:30:21   .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
23:30:21 Call Stack (most recent call first):
23:30:21   cmake/kokkoskernels_tribits.cmake:232 (KOKKOSKERNELS_ADD_EXECUTABLE)
23:30:21   cmake/kokkoskernels_tribits.cmake:172 (KOKKOSKERNELS_ADD_EXECUTABLE_AND_TEST)
23:30:21   lapack/unit_test/CMakeLists.txt:39 (KOKKOSKERNELS_ADD_UNIT_TEST)
23:30:21 
23:30:21 
23:30:21 CMake Error at cmake/kokkoskernels_tribits.cmake:154 (ADD_EXECUTABLE):
23:30:21   No SOURCES given to target: KokkosKernels_lapack_sycl
23:30:21 Call Stack (most recent call first):
23:30:21   cmake/kokkoskernels_tribits.cmake:232 (KOKKOSKERNELS_ADD_EXECUTABLE)
23:30:21   cmake/kokkoskernels_tribits.cmake:172 (KOKKOSKERNELS_ADD_EXECUTABLE_AND_TEST)
23:30:21   lapack/unit_test/CMakeLists.txt:39 (KOKKOSKERNELS_ADD_UNIT_TEST)
```

https://jenkins-son.sandia.gov/job/KokkosKernels_Nightly_Blake_OneAPI_2023_1_0_Sycl_PV/54/consoleFull

@lucbv or @eeprude can you advise on the update needed here?

**Reproducer** (Blake PV queue):
```bash
# Interactive node on PV queue for Intel GPU
salloc -N 1 - p PV

mkdir -p Build
cd Build

# Modules - the source line should no longer be necessary, but I add it just in case
# source /projects/x86-64-icelake-rocky8/spack-config/blake-setup-user-module-env.sh
module purge
module load cmake intel-oneapi-compilers/2023.1.0 intel-oneapi-dpl/2022.1.0 git

# Required for the hashmap accumulator
export ZES_ENABLE_SYSMAN=1

# Configuration
$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-sycl --arch=INTEL_PVC --compiler=/projects/x86-64-icelake-rocky8/compilers/intel-oneapi-compilers/2023.1.0/gcc/8.5.0/base/6g2jkiv/compiler/2023.1.0/linux/bin-llvm/clang++ --cxxflags="-fp-model=precise" --shared --kokkos-cmake-flags=-DKokkos_ENABLE_ONEDPL=OFF -kokkos-path=$KOKKOS_PATH

```

**Comment by eeprude** [comment]
Hi Nathan. I will take a look this afternoon. I should be able to fix it today already.

Best,

Ernesto.

From: Nathan Ellingwood ***@***.***>
Date: Friday, October 27, 2023 at 11:18 AM
To: kokkos/kokkos-kernels ***@***.***>
Cc: Prudencio, Ernesto Esteves ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [kokkos/kokkos-kernels] Sycl nightly build fails to configure - Cannot find source file: backends/Test_SYCL_Lapack.cpp (Issue #2022)

The nightly Sycl build is failing to configure following merge of #1985<https://github.com/kokkos/kokkos-kernels/pull/1985> , with output:

23:30:21 CMake Error at cmake/kokkoskernels_tribits.cmake:154 (ADD_EXECUTABLE):

23:30:21   Cannot find source file:

23:30:21

23:30:21     backends/Test_SYCL_Lapack.cpp

23:30:21

23:30:21   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h

23:30:21   .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

23:30:21 Call Stack (most recent call first):

23:30:21   cmake/kokkoskernels_tribits.cmake:232 (KOKKOSKERNELS_ADD_EXECUTABLE)

23:30:21   cmake/kokkoskernels_tribits.cmake:172 (KOKKOSKERNELS_ADD_EXECUTABLE_AND_TEST)

23:30:21   lapack/unit_test/CMakeLists.txt:39 (KOKKOSKERNELS_ADD_UNIT_TEST)

23:30:21

23:30:21

23:30:21 CMake Error at cmake/kokkoskernels_tribits.cmake:154 (ADD_EXECUTABLE):

23:30:21   No SOURCES given to target: KokkosKernels_lapack_sycl

23:30:21 Call Stack (most recent call first):

23:30:21   cmake/kokkoskernels_tribits.cmake:232 (KOKKOSKERNELS_ADD_EXECUTABLE)

23:30:21   cmake/kokkoskernels_tribits.cmake:172 (KOKKOSKERNELS_ADD_EXECUTABLE_AND_TEST)

23:30:21   lapack/unit_test/CMakeLists.txt:39 (KOKKOSKERNELS_ADD_UNIT_TEST)

https://jenkins-son.sandia.gov/job/KokkosKernels_Nightly_Blake_OneAPI_2023_1_0_Sycl_PV/54/consoleFull

@lucbv<https://github.com/lucbv> or @eeprude<https://github.com/eeprude> can you advise on the update needed here?

Reproducer (Blake PV queue):

# Interactive node on PV queue for Intel GPU

salloc -N 1 - p PV



mkdir -p Build

cd Build



# Modules - the source line should no longer be necessary, but I add it just in case

# source /projects/x86-64-icelake-rocky8/spack-config/blake-setup-user-module-env.sh

module purge

module load cmake intel-oneapi-compilers/2023.1.0 intel-oneapi-dpl/2022.1.0 git



# Required for the hashmap accumulator

export ZES_ENABLE_SYSMAN=1



# Configuration

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-sycl --arch=INTEL_PVC --compiler=/projects/x86-64-icelake-rocky8/compilers/intel-oneapi-compilers/2023.1.0/gcc/8.5.0/base/6g2jkiv/compiler/2023.1.0/linux/bin-llvm/clang++ --cxxflags="-fp-model=precise" --shared --kokkos-cmake-flags=-DKokkos_ENABLE_ONEDPL=OFF -kokkos-path=$KOKKOS_PATH

**Comment by ndellingwood** [comment]
Thanks @eeprude !

**Comment by eeprude** [comment]
You are very welcome, Nathan!

I just created the PR 2024 in order to fix the issue.

I don’t know if Luc (copied) will be able to approve it until Monday morning, or if someone else could approve it before that.

If someone approves the PR soon, but the night error with Trilinos still continues, please just ping me, and I will work on the issue during the weekend.

Best,

Ernesto.

From: Nathan Ellingwood ***@***.***>
Date: Friday, October 27, 2023 at 1:44 PM
To: kokkos/kokkos-kernels ***@***.***>
Cc: Prudencio, Ernesto Esteves ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [kokkos/kokkos-kernels] Sycl nightly build fails to configure - Cannot find source file: backends/Test_SYCL_Lapack.cpp (Issue #2022)

Thanks @eeprude<https://github.com/eeprude> !

**Comment by eeprude** [comment]
Hi Nathan. Do I have to do something extra in order to close this issue @2022? I appears 'open' to me. Who should close it? I am ignorant on how to proceed here. Thanks.

**Comment by eeprude** [comment]
@ndellingwood I just added the 2 quick questions above. Tks.

**Comment by ndellingwood** [comment]
Hi @eeprude , this is resolved, thanks for your fix. I mark the issue as InDevelop once the fixing PR is merged, and we are safe to close.

**Comment by eeprude** [comment]
Great, Nathan! Thanks for the update.

Ernesto.

From: Nathan Ellingwood ***@***.***>
Date: Wednesday, November 1, 2023 at 10:46 AM
To: kokkos/kokkos-kernels ***@***.***>
Cc: Prudencio, Ernesto Esteves ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [kokkos/kokkos-kernels] Sycl nightly build fails to configure - Cannot find source file: backends/Test_SYCL_Lapack.cpp (Issue #2022)

Hi @eeprude<https://github.com/eeprude> , this is resolved, thanks for your fix. I mark the issue as InDevelop once the fixing PR is merged, and we are safe to close.
