### ISSUE TITLE
Possible bug in "native-merge" SpMV algorithm

### ISSUE THREAD

**Issue by cwpearson** [kokkos/kokkos-kernels#2033]
https://github.com/kokkos/kokkos-kernels/issues/2010 was caused by the merge-based SpMV algorithm being selected in Tpetra for this specific mini-em case. The merge-based SpMV was incorrectly re-using the `"merge"` algorithm name, and the fix was to change it to "native-merge" so that the merge-based implementation is no longer used.

It's not clear whether something is not quite right with the matrix, or if there is a bug in the merge-based SpMV implementation.

- [ ] modify the reproducer to dump the local matrix on each rank
- [ ] test the "native-merge" SpMV algorithm on the dumped matrices
  - see what there is to see

**Comment by brian-kelley** [comment]
@cwpearson I think this is actually the same issue as #2166?
