### ISSUE TITLE
Cannot find TPL CUBLAS in a separate directory

### ISSUE THREAD

**Issue by vqd8a** [kokkos/kokkos-kernels#2046]
I see the following CMake error when configuring Kokkos Kernels on Perlmutter:
```
-- Found CUDA: /opt/nvidia/hpc_sdk/Linux_x86_64/22.7/cuda/11.7 (found version "11.7")
CMake Error at /global/common/software/nersc/pm-2022q4/spack/linux-sles15-zen/cmake-3.24.3-k5msymx/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find TPLCUBLAS (missing: CUDA_CUBLAS_LIBRARIES)
Call Stack (most recent call first):
  /global/common/software/nersc/pm-2022q4/spack/linux-sles15-zen/cmake-3.24.3-k5msymx/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindTPLCUBLAS.cmake:13 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/kokkoskernels_tpls.cmake:380 (FIND_PACKAGE)
  cmake/kokkoskernels_tpls.cmake:506 (KOKKOSKERNELS_IMPORT_TPL)
  CMakeLists.txt:222 (INCLUDE)
```
On Perlmutter, CUDA core libraries and CUDA's math libraries are installed in separate directories, such as
```CUDA_HOME=/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/cuda/11.7```, while the ```CUBLAS``` libraries are in ```/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/math_libs/lib64```. This could be the cause of this error.

I tried setting an environment variable ```CUBLAS_ROOT``` to the above path but it does not work.
Is there anything that I missed?

My Kokkos cmake command:

```cmake /global/homes/d/dang15/Kokkos/kokkos -DCMAKE_CXX_COMPILER=/global/homes/d/dang15/Kokkos/kokkos/bin/nvcc_wrapper -DCMAKE_BUILD_TYPE:STRING=RELEASE -DCMAKE_INSTALL_PREFIX=/global/homes/d/dang15/Kokkos/kokkos-install-cuda-perlmutter -DKokkos_ENABLE_OPENMP:BOOL=ON -DKokkos_ARCH_ZEN3=ON -DKokkos_ENABLE_CUDA:BOOL=ON -DKokkos_ENABLE_CUDA_LAMBDA:BOOL=ON -DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON -DKokkos_ARCH_AMPERE80=ON```

My Kokkos Kernels cmake command:

```cmake /global/homes/d/dang15/Kokkos/kokkos-kernels -DCMAKE_CXX_COMPILER=/global/homes/d/dang15/Kokkos/kokkos/bin/nvcc_wrapper -DCMAKE_BUILD_TYPE:STRING=RELEASE -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/global/homes/d/dang15/Kokkos/kokkoskernels-install-cuda-cublason-perlmutter -DKokkos_DIR=/global/homes/d/dang15/Kokkos/kokkos-install-cuda-perlmutter/lib64/cmake/Kokkos -DKokkosKernels_ENABLE_TPL_CUBLAS:BOOL=ON -DKokkosKernels_ENABLE_TPL_CUSPARSE:BOOL=OFF -DKokkosKernels_ENABLE_TPL_CUSOLVER:BOOL=OFF```

Currently Loaded Modules:
  1) craype-x86-milan                        6) cray-dsmml/0.2.2       11) perftools-base/23.03.0   16) cudatoolkit/11.7
  2) libfabric/1.15.2.0                      7) cray-libsci/23.02.1.1  12) cpe/23.03                17) craype-accel-nvidia80
  3) craype-network-ofi                      8) cray-mpich/8.1.25      13) xalt/2.10.2              18) gpu/1.0
  4) xpmem/2.6.2-2.5_2.27__gd067c3f.shasta   9) craype/2.7.20          14) Nsight-Compute/2022.1.1  19) cmake/3.24.3          (buildtools)
  5) PrgEnv-gnu/8.3.3                       10) gcc/11.2.0             15) Nsight-Systems/2022.2.1

**Comment by lucbv** [comment]
Can you try setting: `-D KokkosKernels_CUBLAS_LIBRARY_DIRS=...` and potentially `-D KokkosKernels_CUBLAS_LIBRARIES=...`

**Comment by lucbv** [comment]
Nvidia changed how libraries are packaged in their nvhpc toolkit and we are not supporting it in CMake at the moment, if you want to look at it that would be great...

**Comment by vqd8a** [comment]
> Can you try setting: `-D KokkosKernels_CUBLAS_LIBRARY_DIRS=...` and potentially `-D KokkosKernels_CUBLAS_LIBRARIES=...`

@lucbv Setting these does not work either.

Looking at the ```cmake/Modules/FindTPLCUBLAS.cmake```, I see it finds CUBLAS just via CUDA, which is from ```CUDA_HOME```.

Probably, we need to add some extra logics to locate CUBLAS from ```KokkosKernels_CUBLAS_ROOT``` or something like that. I can look at this issue.

**Comment by lucbv** [comment]
Can you try this, that's what I have in a script:
```
      -D KokkosKernels_ENABLE_TPL_CUBLAS:BOOL=ON \
      -D   TPLCUBLAS_ROOT:PATH="/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/math_libs" \
      -D KokkosKernels_ENABLE_TPL_CUSPARSE:BOOL=ON \
      -D   TPLCUSPARSE_ROOT:PATH="/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/math_libs"
```

**Comment by vqd8a** [comment]
It works. But, this has not been documented. Am I correct? Is this similar to when we build Kokkos Kernels within Trilinos and enable CUBLAS at the Trilinos level?

**Comment by vqd8a** [comment]
Thanks @lucbv . I looked at it. But the page only mentions about ```CUBLAS_LIBRARIES``` and ```CUBLAS_LIBRARY_DIRS, not about ```TPLCUBLAS_ROOT```.

**Comment by lucbv** [comment]
Yeah, it actually refers to the following variable: `KokkosKernels_CUBLAS_ROOT:PATH` which is close but not correct I believe... let us raise this tomorrow and see if anyone else knows the details of this?

**Comment by cwpearson** [comment]
I think`TPL{NAME}_ROOT` works because `FIND_PACKAGE` by default searches in the `{PACKAGE}_ROOT` CMake variable, and we call `FIND_PACKAGE(TPLCUBLAS, ...)` in `kokkoskernels_import_tpl`, and then in conjunction with the `CUDA_CUBLAS_LIBRARIES` variable set by a `FIND_PACKAGE(CUDA)` call, CMake knows what libraries make up the TPLCUBLAS library.

I'm a bit uncertain about the interaction of `FIND_PACKAGE_HANDLE_STANDARD_ARGS`, the `FindTPLCUBLAS.cmake` file, and what happens when you call `FIND_PACKAGE(TPLCUBLAS), so it's possible this is not quite right.

**Comment by cwpearson** [comment]
`CUDA_CUBLAS_LIBRARIES` doesn't work (probably) because it's a documented output variable of `FIND_PACKAGE(CUDA)`

**Comment by cwpearson** [comment]
`CUBLAS_LIBRARIES`, `CUBLAS_LIBRARY_DIRS`, and `CUBLAS_INCLUDE_DIRS` are created in `kokkoskernels_import_tpl`, so those are supposed to work, but I think we just don't use them at all since we basically defer to FIND_CUDA to do it for us in `FindTPLCUBLAS.cmake`.

**Comment by cwpearson** [comment]
Probably there is a similar problem for all CUDA libraries and all ROCm libraries

**Comment by cwpearson** [comment]
Okay I figured it out.

Deep in CMake's FindCUDA.cmake, there is basically the following call:

```cmake
    find_library(cublas
      NAMES ...
      PATHS ...
      DOC ...
      )
```

This kind of call to `find_library` allows CMake to search in the "default locations".

According to https://cmake.org/cmake/help/latest/command/find_library.html, if `find_library` is called from a

> find module or any other script loaded by a call to `find_package`

then it searches in 

> `<PACKAGENAME>_ROOT`

and furthermore

> The package root variables are maintained as a stack

So, basically, because we call `FIND_PACKAGE(TPLCUBLAS)` somewhere above this call to `find_library`, it will search in `TPLCUBAS_ROOT`

**Comment by cwpearson** [comment]
I've overhauled parts of our build instructions and this is corrected there now: https://github.com/kokkos/kokkos-kernels/wiki/Building

**Comment by vqd8a** [comment]
@cwpearson Thanks for looking at this and for updating the wiki page. The wiki page looks to me that different TPLs have different CMake options to specify their ROOT directory. Can we have a consistent way to do this?

**Comment by cwpearson** [comment]
We can, I think we run the risk of breaking a lot of Trilinos stuff. We'd need to be disciplined about deprecation. This may be a worthwhile topic for the next meeting

**Comment by cwpearson** [comment]
Closing after communication on slack
