### ISSUE TITLE
One-based-ness of coloring is undocumented

### ISSUE THREAD

**Issue by pauleonix** [kokkos/kokkos-kernels#2088]
I learned the hard way that colors from `color_view_type GraphColorDistance2Handle::get_vertex_colors();` are one-based, i.e. there is no color zero and the highest value is equal to the output from `nnz_lno_type GraphColorDistance2Handle::get_num_colors();` instead of `num_colors - 1`. I would be in favor of starting at zero because that would be least surprising, but as you might not want to make such a breaking change, it should at least be clearly documented.

**Comment by brian-kelley** [comment]
@pauleonix Sorry this gave you trouble. We do use 0 to represent "uncolored" in some contexts like distributed coloring, so it would be tricky to change this behavior.

But I agree this should definitely be documented, so I just added this fact to the wiki pages for D1 and D2 coloring:
https://github.com/kokkos/kokkos-kernels/wiki/Graph-Coloring
https://github.com/kokkos/kokkos-kernels/wiki/D2-Graph-Coloring
