### ISSUE TITLE
Replace KOKKOS_HAVE_* FLAGS with KOKKOS_ENABLE_*

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos-kernels#219]
KOKKOS_HAVE_* flags are deprecated in kokkos. Every where it appears as MACRO should be replaced with KOKKOS_ENABLE_*

**Comment by ndellingwood** [comment]
Addressed (partially) by #218, thanks @mndevec !

**Comment by kyungjoo-kim** [comment]
Batch functions (src, unit_test, perf_test) in kokkos kernels does not use the macro ``KOKKOS_HAVE``.

**Comment by ndellingwood** [comment]
Updated in PR #227
