### ISSUE TITLE
Multithreaded Gauss-Seidel does not support damping

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos-kernels#221]
See https://github.com/trilinos/Trilinos/issues/2665

**Comment by pwxy** [comment]
I tried MTGS and MTSGS with damping, and it ignores the ifpack2 damping parameter (never even uses it)

**Comment by srajama1** [comment]
@pwxy We will prioritize this.

**Comment by srajama1** [comment]
#255 fixes these
