### ISSUE TITLE
Make KokkosKernels work without KOKKOS_ENABLE_DEPRECATED_CODE

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-kernels#223]

**Comment by ndellingwood** [comment]
See kokkos/kokkos#1277

**Comment by ndellingwood** [comment]
PR #227 is a start on this for search/replace changes needed.

**Comment by ndellingwood** [comment]
PR #228 issued separately to handle the initialize and finalize calls in perf_tests.
