### ISSUE TITLE
team_spmv should be compatible with non-square matrices

### ISSUE THREAD

**Issue by blegouix** [kokkos/kokkos-kernels#2271]
The operation performed by spmv is:

```
y = beta*y + alpha*A*x
```

But the following assertion:

https://github.com/kokkos/kokkos-kernels/blob/8130cf9ab45db5b2bebad4586c9827a18b2f6bcb/sparse/src/KokkosSparse_spmv_team.hpp#L65

Imposes `x` and `y` to have same number of rows, and thus `A` to be squared. Then, this is not a general `spmv`. The way it is written in https://github.com/kokkos/kokkos-kernels/blob/8130cf9ab45db5b2bebad4586c9827a18b2f6bcb/sparse/impl/KokkosSparse_spmv_team_impl.hpp#L66 seems to be completly compatible with non-square `A` (but `numRows` has to be number of rows of `y`, not `x`as it is currently written in `KokkosSparse_spmv_team_spec.hpp`).

If you agree with this statements I can start a PR.

**Comment by lucbv** [comment]
Hi @blegouix, if you could start a PR for this that would be nice.
Thanks for offering to do so!
