### ISSUE TITLE
Not-yet-exposed GEMM interface uses "old" cuBLAS API

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos-kernels#23]
See https://github.com/trilinos/Trilinos/issues/1194 for discussion.

**Comment by crtrott** [comment]
Can we close this?

**Comment by mhoemmen** [comment]
@crtrott Yes, this has been fixed in Trilinos.  Thanks!  Just watch out for this "old" vs. "new" cuBLAS issue in KK.
