### ISSUE TITLE
Unit test headers are installed

### ISSUE THREAD

**Issue by tpadioleau** [kokkos/kokkos-kernels#2332]
Hi,

I noticed that headers from some `unit_test` directories are installed. I suspect it is a mistake ?

The command `grep -R "APPEND KK_INCLUDE_DIRS .*unit_test"` from the top-level directory returns:
```cpp
common/CMakeLists.txt:LIST(APPEND KK_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/common/unit_test)
ode/CMakeLists.txt:LIST(APPEND KK_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/ode/unit_test)
batched/CMakeLists.txt:LIST(APPEND KK_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/batched/dense/unit_test)
batched/CMakeLists.txt:LIST(APPEND KK_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/batched/sparse/unit_test)
```

**Comment by lucbv** [comment]
Okay, thanks for reporting this @tpadioleau 
I suspect we rarely install the library ourselves so we did not notice, if you want to create a PR with these changes that would be kind!

**Comment by tpadioleau** [comment]
Yes i will have a deeper look.
