### ISSUE TITLE
More Kernel Labels for KokkosBlas

### ISSUE THREAD

**Issue by csiefer2** [kokkos/kokkos-kernels#239]
Some of the kernels in KokkosBlas have labels (e.g. "KokkosBlas::update<0,b,c>") but some do not (e.g. the stuff in V_MultFunctor), leaving downstream developers stuck with staring at the mangled names and guessing.

Can somebody do a pass over the KokkosBlas and ensure that these commonly use functions have kernel labels?  Thanks!

**Comment by srajama1** [comment]
I don't want to block 2.7 promotion for this (assuming this is not such a pain), we will take care of this in 2.8.

**Comment by csiefer2** [comment]
No objections here.

**Comment by kyungjoo-kim** [comment]
All routines in KokkosKernels now have profiling labels #359

**Comment by ndellingwood** [comment]
PR #359 merged with added labels.
