### ISSUE TITLE
Add L1 variant to multithreaded Gauss-Seidel

### ISSUE THREAD

**Issue by jhux2** [kokkos/kokkos-kernels#240]
L1 Gauss-Seidel* has proved to be useful as a parallel smoother in multigrid.  I'd like to request that this option be added to the multithreaded Gauss-Seidel kernel.

* "Multigrid Smoothers for Ultraparallel Computing", doi 10.1137/100798806.

**Comment by jhux2** [comment]
@csiefer2 @pwxy

**Comment by mhoemmen** [comment]
@jhux2 Just curious -- is that an option that MueLu normally exercises by default?

**Comment by jhux2** [comment]
@mhoemmen By default, no.  But it's used in the exawind project, and I think in Alegra (@csiefer?).

**Comment by srajama1** [comment]
@jhux2: Any deadlines that I should be aware of ?

**Comment by csiefer** [comment]
Funny jhux2 added me here but GitHub confused my with siefer2 (?)

**Comment by mhoemmen** [comment]
@csiefer I think you are correct; sorry to bother you!  GitHub autocomplete sometimes causes issues; poor jhux got bothered a lot before we realized this ;-) .  @csiefer2 is the person @jhux2 meant to tag.

**Comment by csiefer2** [comment]
At medium-to-large core counts, you really want to use l1...

**Comment by mhoemmen** [comment]
@csiefer2 Nobody does!!! It frustrates me :(

**Comment by srajama1** [comment]
#255 adds these feature.
