### ISSUE TITLE
TPL Support for all BLAS functions using CuBLAS

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-kernels#247]

**Comment by vqd8a** [comment]
@crtrott Could you please send me some examples of using ```singleton``` for defining cuBLAS ```handle```? It would be helpful. Thanks.

**Comment by ndellingwood** [comment]
Cross referencing PR #262

**Comment by mhoemmen** [comment]
@vqd8a When you create the cuBLAS handle (be sure only to create it once -- don't recreate it each time!), set up a Kokkos::finalize hook to free it.

**Comment by vqd8a** [comment]
Thanks @mhoemmen . ```cublasCreate``` and ```cublasDestroy``` are called only once.

**Comment by srajama1** [comment]
@vqd8a : Please create a wiki page with all the functions we support.

**Comment by vqd8a** [comment]
@srajama1 I added a wiki page for these.
