### ISSUE TITLE
Pthread ETI error

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos-kernels#25]
I get below error when I enable Kokkos::Pthread. 

In file included from /home/mndevec/work/trilinoses/Trilinos/packages/kokkos-kernels/src/impl/Kokkos_Blas1_MV_impl_abs.hpp(339),
                 from /home/mndevec/work/trilinoses/Trilinos/packages/kokkos-kernels/src/impl/generated_specializations_cpp/abs/KokkosBlas1_impl_MV_abs_inst_specialization_Kokkos_complex_double__LayoutLeft_Cuda_CudaSpace.cpp(45):
/home/mndevec/work/trilinoses/Trilinos/packages/kokkos-kernels/src/impl/generated_specializations_hpp/KokkosBlas1_impl_MV_abs_decl_specializations.hpp(67): error: namespace "Kokkos" has no member "Pthread"
   KOKKOSBLAS1_IMPL_MV_ABS_DECL(double, Kokkos::LayoutLeft, Kokkos::Pthread, Kokkos::HostSpace)
   ^
....

**Comment by mhoemmen** [comment]
It's called `Kokkos::Thread`

**Comment by mndevec** [comment]
Sorry for the confusion. I am enabling Pthreads simply using the Kokkos_ENABLE_Pthread:BOOL within Trilinos configure. I am not referring it as Kokkos::Pthread in my code.

It seems that the problem is in the KokkosBlas1_impl_MV_abs_decl_specializations.hpp, that refers it as Pthreads in several lines.
