### ISSUE TITLE
KokkosBatched contraction length bug

### ISSUE THREAD

**Issue by huttered40** [kokkos/kokkos-kernels#258]
In the partial specialization of the TeamGemm class template located in src/batched/KokkosBatched_Gemm_Team_Impl.hpp, for Trans::Transpose and a Trans::NoTranspose template parameters, the 3rd argument to the TeamGemmInternal<..>::invoke(..) method is A.extent(1), which is used as the contraction length (parameter k) in TeamGemmInternal<..>::invoke(..). I suspect this code has been used primarily for square matrices arising from finite element discretizations, so this bug has gone unnoticed. When calling this routine with unfolded tensors, however, it appears.

For example, in this specialization, A is transposed, so if A is passed in as a 100 x 4 View, then the contraction length will be 100, not 4. A.extent(1) is 4 here, however.

This same issue might be in the Gemm_Serial class template as well.

**Comment by srajama1** [comment]
@kyungjoo-kim 

@huttered40 : If you have already fixed it then you can put in a pull request to Kokkos-kernels.

**Comment by srajama1** [comment]
PR #261 fixed this. Batched GEMM supports rectangular matrices now.

**Comment by srajama1** [comment]
Reopened. @crtrott likes to close it with master update.
