### ISSUE TITLE
KokkosBatched warnings

### ISSUE THREAD

**Issue by srajama1** [kokkos/kokkos-kernels#259]
Number of warnings in KokkosBatched 

KokkosBatched_LU_Serial_Internal.hpp(59) (col. 22): warning: calling a __host__ function("KokkosBatched::Experimental::RealPart<double> ") from a __host__ __device__ function("KokkosBatched::Experimental::SerialLU_Internal< ::KokkosBatched::Experimental::Algo::Level3::Unblocked> ::invoke<double> ") is not allowed

....................../KokkosBatched_AddRadial_Internal.hpp(58): warning: calling a __host__ 
function("KokkosBatched::Experimental::RealPart<double> ") from a __host__ __device__ function("Kokkos::parallel_for<int,  ::> ") is not allowed

**Comment by kyungjoo-kim** [comment]
What is the context ? We cannot push a code if we have warnings as we use "Werror". Is this come from kokkoskernels compiling ? Or from some other compiling ?

**Comment by crtrott** [comment]
The Werror only applies to the host compilation part. I.e. warnings issued by the device side will not trigger a failure.

**Comment by kyungjoo-kim** [comment]
I also think that you use an outdated code. RealPart should not be used as @vqd8a fixes in pr #236

**Comment by kyungjoo-kim** [comment]
Anyway, I confirmed that those warnings are generated from our testing code. I will fix them soon. It is interesting that device code warnings are not considered as failures. Good to know.

**Comment by ndellingwood** [comment]
Assuming this was fixed with #243

**Comment by srajama1** [comment]
Is this in master ? If not can we leave it open with InDevelop tag till we do a master update ?
