### ISSUE TITLE
Spotcheck on white does not configure it correctly. 

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos-kernels#260]
@crtrott I use the following spotcheck on white (P100).
```
../../master/scripts/test_all_sandia \
--kokkos-path=/home/kyukim/Work/lib/kokkos/master \
--kokkoskernels-path=/home/kyukim/Work/lib/kokkoskernels/master \
--spot-check cuda/8.0.44   
```
This is what I got. It is configured with Kepler37 not Pascal60. Something is wrong. 
```
[kyukim @white11] Cuda_OpenMP-release > cat cuda-8.0.44-Cuda_OpenMP-release.configure.log 
Loading module cuda/8.0.44
Loading module gcc/5.4.0
RUNNING: /home/kyukim/Work/lib/kokkoskernels/master/scripts/generate_makefile.bash --with-devices=Cuda_OpenMP --arch=Power8,Kepler37 --compiler=/home/kyukim/Work/lib/kokkos/master/bin/nvcc_wrapper --cxxflags="-O3 -Werror -Wall -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized " --ldflags="-O3 " --kokkos-path=/home/kyukim/Work/lib/kokkos/master --kokkoskernels-path=/home/kyukim/Work/lib/kokkoskernels/master --with-tpls=
Generating Makefiles with options  CXX=/home/kyukim/Work/lib/kokkos/master/bin/nvcc_wrapper KOKKOS_DEVICES=Cuda_OpenMP KOKKOS_ARCH=Power8,Kepler37 CXXFLAGS="-O3 -Werror -Wall -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized " LDFLAGS="-O3 " GTEST_PATH=/home/kyukim/Work/lib/kokkos/master/tpls/gtest KOKKOSKERNELS_OPTIONS=eti-only KOKKOS_PATH=/home/kyukim/Work/lib/kokkos/master KOKKOSKERNELS_PATH=/home/kyukim/Work/lib/kokkoskernels/master
[kyukim @white11] Cuda_OpenMP-release > 
```

**Comment by crtrott** [comment]
Uhm you did not say Kepler in your configure line up there. You need to add '--arch="Power8,Kepler37"'

**Comment by kyungjoo-kim** [comment]
Isn't that automatically detected from machine configuration ?

**Comment by kyungjoo-kim** [comment]
BTW, Kepler37 is a wrong one. It should be Pascal60.

**Comment by crtrott** [comment]
Oh right thats what I meant. Pascal60. And no its not automatically deferred. It knows it is on white but not which queue you are in.

**Comment by crtrott** [comment]
Thats why I somewhere stated that the script is set up to run on the Kepler queue on white.

**Comment by kyungjoo-kim** [comment]
Oh........... Okay I see what you intended. It might be possible that a testbed has a different queue. I think that it would be more make sense if the script tests a representative case by default e.g., white P100, apollo V100, hansen K80, bowman KNL, blake SKX, etc.

**Comment by crtrott** [comment]
The default value is for what we run the most tests on right now. And we are running more tests on the K80s since they are less heavily used.

**Comment by kyungjoo-kim** [comment]
Okay. I see the point. Thanks.
