### ISSUE TITLE
graph_color_symbolic on directed graphs

### ISSUE THREAD

**Issue by LucasBondDavis** [kokkos/kokkos-kernels#266]
I have a few tests written that use graph_color_symbolic shown in the repo below. The tests on undirected graphs don't fail while any directed graphs seem to be assigned an invalid coloring (ignoring the assert I now have for directed graphs).

https://github.com/LucasBondDavis/EnGPar/blob/89126a0c787ad813db39f7c86807748696c60bc3/test/kokkosColoring.cpp#L51-L89

**Comment by srajama1** [comment]
The graph coloring assumes a symmetric (undirected) graph for now. You can symmetrize the graph as shown in https://github.com/kokkos/kokkos-kernels/blob/master/src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp#L585 before calling coloring. We are considering coloring unsymmetric problems without symmetrizing it. But it is not there yet.

**Comment by LucasBondDavis** [comment]
Thanks for the quick response. Also, is there a way I could contribute to the documentation of this?

**Comment by srajama1** [comment]
Yes, of course ! Thanks for offering to help. Can you see if you can edit this page ?

https://github.com/kokkos/kokkos-kernels/wiki/Graph-Coloring

I am not sure how the permissions are going to work.

**Comment by LucasBondDavis** [comment]
I don't have permission to edit the page, let me know if this changes.

**Comment by srajama1** [comment]
Thanks ! Let me fiddle with the permissions and see.

**Comment by srajama1** [comment]
Git doesn't seem to give an option to easily change it without giving you write access to the entire repo. Can you clone https://help.github.com/articles/adding-and-editing-wiki-pages-locally/ and submit a PR with the changes ? The one thing is we need this PR to be on master apparently.

**Comment by LucasBondDavis** [comment]
I wrote up a usage page for graph color, only problem is I don't think it's possible to fork a wiki. How would you like to to deliver this update to you?

**Comment by srajama1** [comment]
I sent a collaborator request to you. Let us see if that allows you to edit. Note it also allows you to push code for which we would require the pull request model.

**Comment by srajama1** [comment]
Thanks for adding the documentation.
