### ISSUE TITLE
Run graph Coloring algorithm with no output

### ISSUE THREAD

**Issue by pkuwalter** [kokkos/kokkos-kernels#270]
I can not find the coloring result. Below is the cout information. Do I need to comfire all the parameters????

-bash-4.2$ ./KokkosGraph_color.exe  --cuda --amtx ../../../dataset/IPDPS_data/dblp_88M.txt --algorithm COLORING_EB
Sizeof(idx):4 sizeof(size_type):4
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
Compiler:
  KOKKOS_COMPILER_GNU: 485
Architecture:
  KOKKOS_ENABLE_ISA_KNC: no
  KOKKOS_ENABLE_ISA_POWERPCLE: no
  KOKKOS_ENABLE_ISA_X86_64: no
Devices:
  KOKKOS_ENABLE_CUDA: no
  KOKKOS_ENABLE_OPENMP: yes
  KOKKOS_ENABLE_THREADS: no
  KOKKOS_ENABLE_QTHREADS: no
  KOKKOS_ENABLE_SERIAL: no
Default Device:
  KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_CUDA: no
  KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_OPENMP: yes
  KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_THREADS: no
  KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_QTHREADS: no
  KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_SERIAL: no
Atomics:
  KOKKOS_ENABLE_CUDA_ATOMICS: no
  KOKKOS_ENABLE_GNU_ATOMICS: yes
  KOKKOS_ENABLE_INTEL_ATOMICS: no
  KOKKOS_ENABLE_OPENMP_ATOMICS: no
  KOKKOS_ENABLE_WINDOWS_ATOMICS: no
  KOKKOS_ENABLE_SERIAL_ATOMICS: no
Vectorization:
  KOKKOS_ENABLE_PRAGMA_IVDEP: no
  KOKKOS_ENABLE_PRAGMA_LOOPCOUNT: no
  KOKKOS_ENABLE_PRAGMA_SIMD: no
  KOKKOS_ENABLE_PRAGMA_UNROLL: no
  KOKKOS_ENABLE_PRAGMA_VECTOR: no
Memory:
  KOKKOS_ENABLE_HBWSPACE: no
  KOKKOS_ENABLE_INTEL_MM_ALLOC: no
  KOKKOS_ENABLE_POSIX_MEMALIGN: no
Options:
  KOKKOS_ENABLE_ASM: yes
  KOKKOS_ENABLE_CXX1Z: no
  KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK: no
  KOKKOS_ENABLE_HWLOC: no
  KOKKOS_ENABLE_LIBRT: no
  KOKKOS_ENABLE_MPI: no
  KOKKOS_ENABLE_PROFILING: yes

Runtime Configuration:
Kokkos::OpenMP thread_pool_topology[ 1 x 0 x 1 ]

**Comment by srajama1** [comment]
It appears you are running with --cuda but you haven't enabled CUDA in your compilation "KOKKOS_ENABLE_CUDA: no"

**Comment by pkuwalter** [comment]
thanks srajama, but how can I enable CUDA? I have added my CUDA path to the configure file.

**Comment by srajama1** [comment]
If you are using the scripts in example/buildlib then something like
KOKKOS_DEVICES=OpenMP,Cuda  #we need both cuda and openmp/serial execution space.
KOKKOS_ARCHS=Pascal60,Power8

will help to build for P100. The ARCHS flags is a Kokkos option that is dependent on your GPU. What is your GPU ?

**Comment by pkuwalter** [comment]
yes, I also used the NVIDIA P100 GPU card. In the script file, I enabled both OpenMP and Cuda with the KOKKOS_ARCHS=Pascal60,Power8

**Comment by srajama1** [comment]
If both those lines for KOKKOS_ARCHS and KOKKO_DEVICES are there then I am surprised why you would see "KOKKOS_ENABLE_CUDA: no" in your build. Some times the build system acts weird especially when configure options are changed. Can you try a clean version ?

**Comment by srajama1** [comment]
@pkuwalter : Did this work ? Can we close this ?

**Comment by euler314** [comment]
FWIW, I seem to be struggling with the same issue: there is no output regarding the coloring. I'm not compiling with CUDA, but my only device is OpenMP, i.e.,:

KOKKOS_ENABLE_OPENMP: yes

(others are no).

One suggestion would be to make it clear what the input matrix should be. Currently, even if I give --amtx foo, where foo is a non-sense file, there is no error from the program. Concretely, instead of printing "Provide a matrix file", the printout could be "Provide a matrix file (switch --amtx)", because there only way to find this out is to go look into the source code.

Currently, I'm trying to run the program with a .crs input matrix obtained via KokkosKernels_MatrixConverter.exe.

What should be the minimum requirement in terms of command line arguments to see a resulting coloring?

**Comment by srajama1** [comment]
@william76 fixed this in #405
