### ISSUE TITLE
Distance-1 graph coloring segfault

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#275]
The graph coloring done when initializing MT Gauss-Seidel sometimes segfaults when processing a graph from Drekar (24K rows/cols, 5.6M entries), especially with a high number of OpenMP threads (seems to happen about 80% of the time with 64 threads on a KNL with this particular graph). [The graph and a unit test to replicate the crash are here](https://github.com/brian-kelley/kokkos-kernels/tree/ColoringCrash) - coloring is run in unit_test/KokkosKernels_graph_openmp.exe by the test called "BMK_replicate_color_crash". The test verifies that the graph is actually symmetric and that all entries are in the valid range 0...numRows-1. When the test succeeds, the graph is colored using around 96 colors.

 I'm using kokkos d6e8d32 and kokkos-kernels e463b6e (both up-to-date from develop branches). The graph coloring handle is created with all default settings.

**Comment by lucbv** [comment]
@brian-kelley is this still happening?

**Comment by brian-kelley** [comment]
@lucbv I just ran the crash replication test with the newest kokkos/kokkos-kernels and it's still happening. Also, the crash replication branch is now rebased on the current kokkos-kernels develop.

**Comment by srajama1** [comment]
@lucbv : Do you have time to look at this. It would be nice to fix it before next update.

**Comment by srajama1** [comment]
We don't close till the changes are in master, when we do the master + Trilinos integration we will close all "InDevelop" issues.
