### ISSUE TITLE
White Cuda Runtime Failure

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#280]
On White with a Cuda/9.2 bulid the following test failure occurs:

```
[ RUN      ] cuda.gemm_double
unknown file: Failure
C++ exception with description "Kokkos::Impl::ParallelFor< Cuda > requested too large team size.
Traceback functionality not available
" thrown in the test body.
[  FAILED  ] cuda.gemm_double (104 ms)
[ RUN      ] cuda.sparse_spgemm_double_int_int_TestExecSpace
Segmentation fault (core dumped)
```

Modules loaded:
```
Currently Loaded Modulefiles:
  1) git/2.10.1        2) cmake/3.9.6       3) binutils/2.30.0   4) gcc/7.2.0         5) cuda/9.2.88       6) ibm/xl/16.1.1

```

Queue and Arch:
rhel7F queue (Kepler K80 GPUs)
Power8,Kepler37 archs

Edit: Adding SHAs and script for generating makefiles

Kokkos SHA: kokkos/kokkos@5fe980f4b6d672cd58aab0e8685d8e1dfc9f809e
KokkosKernels SHA: 9a9845e14234eb8f8edb7c1331c9a228eb24048d

Script:
```
KOKKOS_PATH=${HOME}/kokkos #path to kokkos source
KOKKOSKERNELS_SCALARS=double #the scalar types to instantiate =double,float...
KOKKOSKERNELS_LAYOUTS=LayoutLeft #the layout types to instantiate.
KOKKOSKERNELS_ORDINALS=int #ordinal types to instantiate
KOKKOSKERNELS_OFFSETS=int #offset types to instantiate
KOKKOSKERNELS_PATH=../.. #path to kokkos-kernels top directory.
CXX=${KOKKOS_PATH}/bin/nvcc_wrapper #icpc #
KOKKOSKERNELS_OPTIONS=eti-only #options for kokkoskernels
KOKKOS_DEVICES="Cuda,Serial"
KOKKOS_ARCHS="Power8,Kepler37"
CXXFLAGS="-pedantic -O3 -g -Wshadow -Wsign-compare -Wtype-limits -Wuninitialized"

../../scripts/generate_makefile.bash --kokkoskernels-path=${KOKKOSKERNELS_PATH} --with-scalars=${KOKKOSKERNELS_SCALARS} --with-ordinals=${KOKKOSKERNELS_ORDINALS} --with-offsets=${KOKKOSKERNELS_OFFSETS} --kokkos-path=${KOKKOS_PATH} --with-devices=${KOKKOS_DEVICES} --arch=${KOKKOS_ARCHS} --compiler=${CXX} --with-options=${KOKKOSKERNELS_OPTIONS}  --cxxflags="${CXXFLAGS}"
```

Reproducing instructions:
1. Created testing sub-directory within KokkosKernels
kokkos-kernels/testing/White-Cuda9.2

2. make install-lib -j16

3. cd unit_test

4. make -j32

5. run tests
./KokkosKernels_UnitTest_Cuda

**Comment by srajama1** [comment]
Does it change based on Cuda version ? We have nightlies on white that don't have this problem.

**Comment by ndellingwood** [comment]
@srajama1 I'll check with cuda/9.0 and hop over to the pascal queue and do some testing there.

**Comment by ndellingwood** [comment]
@srajama1 same error using cuda/9.0.176 + gcc/6.4.0 (gcc/7.2.0 is not compatible with our cuda/9.0.x compilers).

```
[ RUN      ] cuda.gemm_double
unknown file: Failure
C++ exception with description "Kokkos::Impl::ParallelFor< Cuda > requested too large team size.
Traceback functionality not available
" thrown in the test body.
[  FAILED  ] cuda.gemm_double (110 ms)
[ RUN      ] cuda.sparse_spgemm_double_int_int_TestExecSpace
Segmentation fault (core dumped)
```

**Comment by ndellingwood** [comment]
@srajama1 The description:

> C++ exception with description "Kokkos::Impl::ParallelFor< Cuda > requested too large team size.

possibly suggests that a team_size is hard-coded too large for the hardware, which currently should silently adjust to the max possible team_size unless deprecated code is disabled in which case this behavior is not masked, but I did not pass a flag to disable deprecated code... maybe the switch was flipped in the kokkos develop branch to disable deprecated code by default. If so I can start looking at that as the cause, though I thought I caught all these cases in KokkosKernels awhile back...

**Comment by ndellingwood** [comment]
Update:
In `src/blas/impl/KokkosBlas3_gemm_impl.hpp` there is a `GEMMImpl<...>::run(...)` method that takes team_size as a runtime argument and then uses this to construct a `team_policy`.

`src/blas/impl/KokkosBlas3_gemm_spec.hpp` contains the `GEMM<...>::gemm(...)` calls the above `run` method where the following info is used to set the team_size:

line 138:
` static constexpr int blockA0 = 24;`
`...`
line 154:
```
  // Figure out Team Sizes
  int team_size = 1;
  #if defined(KOKKOS_ENABLE_CUDA)
  if(std::is_same<typename CViewType::execution_space,Kokkos::Cuda>::value)
    team_size = blockA0;
  #endif
```

@srajama1 @crtrott does this algorithm require that the team_size be hard coded to a particular value, or is this value chosen based on performance? I don't want to blindly replace the team size with `Kokkos::AUTO` without knowing better how it is used by the algorithm.

**Comment by ndellingwood** [comment]
This is a verbose message but reference step info from cuda-gdb the last point in `GEMMImpl` until the code fails:

```
(cuda-gdb)
KokkosBlas::Impl::GEMMImpl<Kokkos::Cuda, Kokkos::View<double const**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<double const**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Kokkos::MemoryTraits<1u> >, 24, 16, 64, 0, 0>::run (scr_level=0,
    vector_length=16, team_size=24, this=0x7fffffffc378) at /ascldap/users/ndellin/kokkos-kernels/src/blas/impl/KokkosBlas3_gemm_spec.hpp:167
167	    gemm.run(team_size,vector_length,scratch_level);
(cuda-gdb)
Kokkos::TeamPolicy<Kokkos::Cuda, Kokkos::LaunchBounds<384u, 2u> >::TeamPolicy (vector_length_request=16, team_size_request=24,
    league_size_request=<optimized out>, this=0x7fffffffc410)
    at /ascldap/users/ndellin/kokkos-kernels/testing/White-Cuda9.0-Kepler/kokkos/install/include/Kokkos_ExecPolicy.hpp:541
541	  TeamPolicy( int league_size_request , int team_size_request , int vector_length_request = 1 )
(cuda-gdb)
Kokkos::Impl::TeamPolicyInternal<Kokkos::Cuda, Kokkos::Cuda, Kokkos::LaunchBounds<384u, 2u> >::TeamPolicyInternal (this=0x7fffffffc410, league_size_=1,
    team_size_request=24, vector_length_request=16)
    at /ascldap/users/ndellin/kokkos-kernels/testing/White-Cuda9.0-Kepler/kokkos/install/include/Cuda/Kokkos_Cuda_Parallel.hpp:284
284	            , int vector_length_request = 1 )
(cuda-gdb)
282	  TeamPolicyInternal( int league_size_
(cuda-gdb)
293	      if ( ! Kokkos::Impl::is_integral_power_of_two( vector_length_request ) ) {
(cuda-gdb)
Kokkos::Impl::is_integral_power_of_two (N=<optimized out>)
    at /ascldap/users/ndellin/kokkos-kernels/testing/White-Cuda9.0-Kepler/kokkos/install/include/impl/Kokkos_Traits.hpp:393
393	{ return ( 0 < N ) && ( 0 == ( N & ( N - 1 ) ) ); }
(cuda-gdb)
Kokkos::Impl::TeamPolicyInternal<Kokkos::Cuda, Kokkos::Cuda, Kokkos::LaunchBounds<384u, 2u> >::TeamPolicyInternal (this=0x7fffffffc410, league_size_=1,
    team_size_request=24, vector_length_request=16)
    at /ascldap/users/ndellin/kokkos-kernels/testing/White-Cuda9.0-Kepler/kokkos/install/include/Cuda/Kokkos_Cuda_Parallel.hpp:282
282	  TeamPolicyInternal( int league_size_
(cuda-gdb)
284	            , int vector_length_request = 1 )
(cuda-gdb)
293	      if ( ! Kokkos::Impl::is_integral_power_of_two( vector_length_request ) ) {
(cuda-gdb)
Kokkos::Impl::is_integral_power_of_two (N=16)
    at /ascldap/users/ndellin/kokkos-kernels/testing/White-Cuda9.0-Kepler/kokkos/install/include/impl/Kokkos_Traits.hpp:393
393	{ return ( 0 < N ) && ( 0 == ( N & ( N - 1 ) ) ); }
(cuda-gdb)
Kokkos::Impl::TeamPolicyInternal<Kokkos::Cuda, Kokkos::Cuda, Kokkos::LaunchBounds<384u, 2u> >::TeamPolicyInternal (this=0x7fffffffc410,
    league_size_=<optimized out>, team_size_request=<optimized out>, vector_length_request=<optimized out>)
    at /ascldap/users/ndellin/kokkos-kernels/testing/White-Cuda9.0-Kepler/kokkos/install/include/Cuda/Kokkos_Cuda_Parallel.hpp:298
298	      if(league_size_ >= int(Impl::cuda_internal_maximum_grid_count()))
(cuda-gdb)
Kokkos::Impl::cuda_internal_maximum_grid_count () at /ascldap/users/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:707
707	{ return CudaInternal::singleton().m_maxBlock ; }
(cuda-gdb)
Kokkos::Impl::CudaInternal::singleton () at /ascldap/users/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:366
366	  static CudaInternal self ;
(cuda-gdb)
Kokkos::Impl::cuda_internal_maximum_grid_count () at /ascldap/users/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:707
707	{ return CudaInternal::singleton().m_maxBlock ; }
(cuda-gdb)
Kokkos::Impl::CudaInternal::singleton () at /ascldap/users/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:366
366	  static CudaInternal self ;
(cuda-gdb)
Kokkos::Impl::cuda_internal_maximum_grid_count () at /ascldap/users/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:707
707	{ return CudaInternal::singleton().m_maxBlock ; }
(cuda-gdb)
Kokkos::Impl::CudaInternal::singleton () at /ascldap/users/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:366
366	  static CudaInternal self ;
(cuda-gdb)
Kokkos::Impl::cuda_internal_maximum_grid_count () at /ascldap/users/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:707
707	{ return CudaInternal::singleton().m_maxBlock ; }
(cuda-gdb)
Kokkos::Impl::TeamPolicyInternal<Kokkos::Cuda, Kokkos::Cuda, Kokkos::LaunchBounds<384u, 2u> >::TeamPolicyInternal (this=0x7fffffffc410,
    league_size_=<optimized out>, team_size_request=<optimized out>, vector_length_request=<optimized out>)
    at /ascldap/users/ndellin/kokkos-kernels/testing/White-Cuda9.0-Kepler/kokkos/install/include/Cuda/Kokkos_Cuda_Parallel.hpp:302
302	      if ( m_team_size * m_vector_length > 1024 ) {
(cuda-gdb)
305	    }
```

**Comment by ndellingwood** [comment]
@srajama1 the spgemm segfault was an artifact of the gemm test failure, probably the GPU memory was corrupted:
```

bash-4.2$ ./KokkosKernels_UnitTest_Cuda --gtest_filter=cuda.sparse_spgemm_double_int_int_TestExecSpace
Note: Google Test filter = cuda.sparse_spgemm_double_int_int_TestExecSpace
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from cuda
[ RUN      ] cuda.sparse_spgemm_double_int_int_TestExecSpace
[       OK ] cuda.sparse_spgemm_double_int_int_TestExecSpace (2792 ms)
[----------] 1 test from cuda (2792 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2792 ms total)
[  PASSED  ] 1 test.
```

So we can just focus on the gemm test.

**Comment by srajama1** [comment]
@ndellingwood : Thanks for checking. @crtrott : What is with this team size 24 ?

**Comment by crtrott** [comment]
I think it was an optimization choice. Need to check what valid options are.

**Comment by ndellingwood** [comment]
FWIW if I replace the team_size in the `GEMMImpl<...>::run(team_size,vector_length,src_level)` with `Kokkos::AUTO` the unit test passes. 
@crtrott why is the team_size hard-coded to 24 at line 138 of `src/blas/impl/KokkosBlas3_gemm_spec.hpp`? I'm assuming prior to disabling deprecated code in Kokkos that this worked because the team_size was silently modified to the smaller max value that was allowed. 
Is it okay that I use `Kokkos::AUTO` as above as the fix? 
Alternatively, we could do a check similar to Kokkos' check during construction of the ParallelFor and reset the team_size if it is too large.

**Comment by ndellingwood** [comment]
For reference from `src/blas/impl/KokkosBlas3_gemm_spec.hpp`:
The `team_size` is set to `blockA0` https://github.com/kokkos/kokkos-kernels/blob/1a7b524ba38fdfab6c1058065af06cbcb4a2ce6f/src/blas/impl/KokkosBlas3_gemm_spec.hpp#L157

where `blockA0` is hard-coded to 24 https://github.com/kokkos/kokkos-kernels/blob/1a7b524ba38fdfab6c1058065af06cbcb4a2ce6f/src/blas/impl/KokkosBlas3_gemm_spec.hpp#L138 
and used after for determining the size of `blockA1`.

I added this info to track two possible changes that get unit tests passing:

1. Replace `team_size` with `Kokkos::AUTO` when creating the team policy used in `run` method of `GEMMImpl`

2. Reduce the `blockA0` size from 24 to 16. 

I'm assuming prior to disabling deprecated code that Kokkos acted in a way similar to 1, but wonder if option 2 is more important for the algorithm to keep team_size in some synchronization with the blockA0 and blockA1 values.

**Comment by srajama1** [comment]
What does Kokkos::AUTO actually pick for this case ? Is this the recommended way to do this ?

**Comment by kyungjoo-kim** [comment]
@crtrott I think that CUDA 9.2 is very problematic and we may need to downgrade it. 
@mperego trilinos/Trilinos#3340 also reports some scheduling issues which have not happend in the previous version of CUDA.

**Comment by crtrott** [comment]
Ok this is actually an issue in Kokkos since it only tests block sizes of power of two. For this kernel 32 is too large but 24 would fix, but Kokkos said 16 is the max. I improved the Kokkos max-block-size functionality to make this work again.

**Comment by crtrott** [comment]
Yeah so now the answer for max team size is 24 ...

**Comment by srajama1** [comment]
Closing it as it is fixed in Kokkos.
