### ISSUE TITLE
Failing spgemm unit test with MKL

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#289]
Sample output with either intel/17 or intel/18.2.199 on Bowman with OpenMP backend:

```
[ RUN      ] openmp.sparse_spgemm_double_int_int_TestExecSpace
/home/ndellin/kokkos-kernels/unit_test/sparse/Test_Sparse_spgemm.hpp:366: Failure
Value of: (failed == is_expected_to_fail)
  Actual: false
Expected: true
[  FAILED  ] openmp.sparse_spgemm_double_int_int_TestExecSpace (9309 ms)
[----------] 1 test from openmp (9309 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (9311 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] openmp.sparse_spgemm_double_int_int_TestExecSpace
```

**Comment by ndellingwood** [comment]
Think I have this chased down, looks like there is a macro defined in the config file `HAVE_KOKKOSKERNELS_MKL` that never gets set but is expected in the failing unit test at this line: 
[line 311](https://github.com/kokkos/kokkos-kernels/blob/f1f6a21475b99a2f6be096d75c6bdb0ed5285dab/unit_test/sparse/Test_Sparse_spgemm.hpp#L311)

**Comment by ndellingwood** [comment]
Updating that line to instead check that 
`#if !defined(HAVE_KOKKOSKERNELS_MKL) && !defined(KOKKOSKERNELS_ENABLE_TPL_BLAS)`
seems to fix it, will put in PR shortly. Will probably combine with update requested by #268

**Comment by srajama1** [comment]
I don't think  !defined(KOKKOSKERNELS_ENABLE_TPL_BLAS) is needed for this test.

**Comment by ndellingwood** [comment]
@srajama1  To have the expected setting for `is_expected_to_fail` the `HAVE_KOKKOSKERNELS_MKL` should be defined. Since it is never set in the CMakeLists.txt file I thought adding the check for `!defined(KOKKOSKERNELS_ENABLE_TPL_BLAS)` was the right thing to do. Should the CMakeLists.txt file be changed to define `HAVE_KOKKOSKERNELS_MKL`  when `KOKKOSKERNELS_ENABLE_TPL_BLAS` is defined?

**Comment by ndellingwood** [comment]
The change above fixes the failing tests for intel/18.2.199 and intel/17.

**Comment by srajama1** [comment]
Is there something wrong in setting HAVE_KOKKOSKERNELS_MKL in the CMakeLists.txt when MKL is enabled ? TPL_BLAS could be enabled even if cuBLAS is enabled, right ?

**Comment by ndellingwood** [comment]
Also, the logic in the config file never does anything with `HAVE_KOKKOSKERNELS_MKL`; the CMakeLists.txt would only have an affect if building with Trilinos I spose, I'll add an update to the macro logic in the config file to set `HAVE_KOKKOSKERNELS_MKL` when `KOKKOSKERNELS_ENABLE_TPL_BLAS` is defined; then this should work either as stand-alone kokkos-kernels or within Trilinos, I think...

**Comment by ndellingwood** [comment]
@srajama1 pointed out I used the wrong macro above (and in my sandbox), should have used `KOKKOSKERNELS_ENABLE_TPL_MKL`. Made the change and retested, things are passing :)

**Comment by ndellingwood** [comment]
Issue PR #290 with fix

**Comment by ndellingwood** [comment]
@kyungjoo-kim which version of intel were you using? We can add the correct if-guards to protect against this.

**Comment by kyungjoo-kim** [comment]
intel/compilers/18.2.199

**Comment by ndellingwood** [comment]
Huh, that's the one I'm using...
I've only been testing the unit_test directory for now, did this show up with the perf_tests?

**Comment by kyungjoo-kim** [comment]
no.... this shows up in eti compiling

**Comment by kyungjoo-kim** [comment]
```
../../master/scripts/test_all_sandia --kokkos-path=/home/kyukim/Work/lib/kokkos/master --kokkoskernels-path=/home/kyukim/Work/lib/kokkoskernels/master --spot-check --with-tpls=mkl  
```

**Comment by kyungjoo-kim** [comment]
@ndellingwood if you cannot reproduce the same error, let me know when you are available in your office. I will come by. Lately I figured out that my custum bash environement can generate some errors that others cannot see.

**Comment by ndellingwood** [comment]
Looked at the other include issue with @kyungjoo-kim, we believe the issue is with using `test_all_sandia` which automatically loads modules but does not set `MKL_PATH`, and thus it defaults to expecting a default path associated with that set in a SEMS environment (see Makefile.kokkos-kernels). I'm going to mark this issue as in develop, we can fix the test_all_sandia testing issue with MKL on non_SEMS machines in a separate issue.
