### ISSUE TITLE
Trilinos/KokkosKernels reports no ETI in almost any circumstance

### ISSUE THREAD

**Issue by csiefer2** [kokkos/kokkos-kernels#29]
I looked through a few of the dashboard tests and they all report KokkosKernels as not ETI-ing anything.

e.g.:
```

Processing ETI support: KokkosKernels
-- KokkosKernels: Processing ETI / test support
-- Enabled Scalar types:       
-- Enabled LocalOrdinal types: 
-- Enabled Device types:       
-- Set of enabled types, before exclusions: 
```

Is this to be expected?

**Comment by mhoemmen** [comment]
@csiefer2 I'm not quite sure, but when @crtrott finished redoing KokkosKernels' ETI a little while ago, he replaced use of TriBITS' ETI system with an offline script.  It should tie into TriBITS' macros, though, so I'm not sure what's going on here.  Have you noticed a large build time inflation?

**Comment by mhoemmen** [comment]
I'm getting this:
```
=======================
KokkosKernels ETI Types
   Devices: <OpenMP,HostSpace>;<Serial,HostSpace>
   Scalars: double
=======================
```
as well as this:
```
Processing ETI support: KokkosKernels
-- KokkosKernels: Processing ETI / test support
-- Enabled Scalar types:
-- Enabled LocalOrdinal types:
-- Enabled Device types:
-- Set of enabled types, before exclusions:
```
Did you see something like the former?  Perhaps we should relabel this issue "Make KokkosKernels ETI only print once, correctly" :)

**Comment by crtrott** [comment]
KokkosKernels does not utilize the Tribits ETI system. So I am not sure why it does print that thing out. It should print its own ETI support stuff out though.

**Comment by mhoemmen** [comment]
@crtrott KokkosKernels currently still opts into Trilinos' ETI system.  It looks like we should take that out, since KK ignores all that stuff anyway and uses different CMake options to drive its instantiations.
