### ISSUE TITLE
warning error

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos-kernels#291]
I am not sure if I need to put this issue on kokkos or kokkoskernels. I decided to post for both. 

gcc 7.2.0 and cuda 9.2.88. While compiling kokkoskernels with ``-Werror``,  I got the following warning error. Removing compiler warnings is quite annoying. In our build system, do we want to keep werror including ``int-in-bool-context`` ? I believe that we use this things many many places and it is legal anyway.

```
/home/kyukim/Work/lib/kokkoskernels/master/src/impl/generated_specializations_cpp/spgemm_numeric/KokkosSparse_spgemm_numeric_eti_spec_inst_doub$
/ascldap/users/kyukim/Work/lib/kokkoskernels/build/white/release/kokkos/install/include/Cuda/Kokkos_CudaExec.hpp:267:42:                        
error: ‘*’ in boolean context, suggest ‘&&’ instead [-Werror=int-in-bool-context]                                                               
     if ( grid.x && ( block.x * block.y * block.z ) ) {   
```

**Comment by ndellingwood** [comment]
This should be fixed in the kokkos develop branch by PR kokkos/kokkos#1739

**Comment by ndellingwood** [comment]
Issue kokkos/kokkos#1796 @kyungjoo-kim  points out extra warnings needing fixed in Kokkos, we can track this there.

**Comment by ndellingwood** [comment]
Fixed in kokkos develop branch, just a couple copy/pastes of a fix Dan put in prior.
