### ISSUE TITLE
Batched getri need

### ISSUE THREAD

**Issue by vqd8a** [kokkos/kokkos-kernels#305]
Implement batched serial and team getri.

**Comment by dholladay00** [comment]
Does `getri` internally use `getrf`? It sounds like this is very close to fulfilling https://github.com/kokkos/kokkos-kernels/issues/9#issuecomment-284473508 and #39!

**Comment by vqd8a** [comment]
@dholladay00 ```getri``` computes the inverse of LU factorization resulted from ```getrf```
and yes it does.

**Comment by vqd8a** [comment]
@dholladay00 ```getri``` internally uses ```trsm```

**Comment by dholladay00** [comment]
Oh right, it assumes `getrf` has already been called. Thanks for the info.

**Comment by srajama1** [comment]
@dholladay00 : supporting getrs with these options are also possible. I think it meets all the requirements you put in.

**Comment by ndellingwood** [comment]
PR #306 merged with @vqd8a 's implementation.
