### ISSUE TITLE
simple test program fails using 3rdparty Eigen library

### ISSUE THREAD

**Issue by finkandreas** [kokkos/kokkos-kernels#309]
I'm trying to compile this:
```
#include "KokkosBatched_Vector_SIMD.hpp"
#include "Eigen/Core"

int main() {
  return 0;
} 
```

The problem here is that KokkosBatched_Vector_SIMD.hpp moves a `#include <immintrin.h>` inside the `KokkosBatched::Experimental` namespace. Thus the include of Eigen/Core will result in an error, because it's also using intrinsic functions (which are now inside the namespace).
I would suggest that you move the include of the intrinsic functions outside of the namespace.

**Comment by hcedwar** [comment]
re #310, oops
