### ISSUE TITLE
findRelOffset test assumes UVM

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos-kernels#32]
According to @crtrott , KokkosKernels is *not* allowed to assume UVM.

**Comment by mndevec** [comment]
I am rolling back on this. As I notice that not only the test, but also the implementation itself is sequential, as a result, the implementation itself is assuming UVM on GPU side. 

@mhoemmen, is this the only intended use of findRelOffset? Does this require a GPU implementation, or does it make sense to have a GPU implementation?

**Comment by mhoemmen** [comment]
@mndevec findRelOffset should be callable on the GPU too.  It's meant to be called by a single thread, but could be called on device.  Thus, I don't think the function assumes UVM, but it does look like the test assumes UVM.

**Comment by mndevec** [comment]
Thanks Mark. So, is it a function that should only be called in the parallel region?

**Comment by mhoemmen** [comment]
@mndevec wrote:
> Thanks Mark. So, is it a function that should only be called in the parallel region?

No, not necessarily.  It _may_ be called on device, but it may also be called on host.  `KOKKOS_FUNCTION` means `__host__ __device__`, not just `__device`.

**Comment by mndevec** [comment]
Okay thanks. In this case, 
Unit tests should call this function 
  1- in a parallel region for all execution spaces.
  2- directly from host, only if the view is not in Device Memory.
Right?

**Comment by mhoemmen** [comment]
@mndevec Yes, that's correct.  Thanks!

**Comment by crtrott** [comment]
May want add new unit test to call in CUDA.
