### ISSUE TITLE
Fix code to compile with Kokkos deprecated code disabled

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#333]

**Comment by ndellingwood** [comment]
This blocks promotion. 

Issues so far:

- [ ] Use of deprecated `team_size_max` and `team_size_recommended` static member functions must be replaced with call to member function of a constructed team policy.
- [ ] spmv test failing when Cuda_Serial enabled - a team_size is chosen that is too large and previously was silently reset to the max size allowable.

**Comment by ndellingwood** [comment]
PR #334 is a first go at addressing the issues above. That PR allowed me to build Trilinos in Cuda_Serial configuration with deprecated code disabled and Tpetra, Stokhos, Sacado packages enabled when using the PR Trilinos/trilinos#3682 and kokkos/kokkos#1860

**Comment by ndellingwood** [comment]
Adding a note on extra fix required exposed by testing Tpetra with deprecated code disabled during integration testing:

`src/sparse/impl/KokkosSparse_spgemm_impl_def.hpp` was creating View's with an empty string and no dimensions, which is no longer allowed. Fixed in PR #334 as part of cleanup with deprecated code disabled. 

Cross-referencing issue #345

**Comment by mhoemmen** [comment]
FYI @rrdrake
