### ISSUE TITLE
Create wiki pages for all the features

### ISSUE THREAD

**Issue by srajama1** [kokkos/kokkos-kernels#337]
I am creating this as a master issue for populating the wiki. Let us create both an interface documentation and a user focused documentation.

My tentative plan

Will and Luc - Coloring 
Kyungjoo - Compact APIs
Nathan, (Kyungjoo ?) and Siva - Sparse APIs
Michel - Performance benchmark usage
Nathan, Will - Testbed builds, spotchecks
Christian , Vinh - BLAS calls
Overall - Siva

 Let us all plan to complete this by the end of Q1.  My guess this is probably a day's work in each one of the areas.

**Comment by srajama1** [comment]
Also please get the documentation that you create reviewed by someone else. There is no good way to do this in a wiki like a PR, so please get this done informally. I am happy to review as many pages as you want.

**Comment by kyungjoo-kim** [comment]
I put some documentation in the following link to get an R&A. Please review and let me know if you find unclear things. As I am already familiar with the functions, I might presume many things. 

https://github.com/kokkos/kokkos-kernels-private/wiki/Batched-BLAS-and-LAPACK

**Comment by ndellingwood** [comment]
The private repo completed R&A and the public wiki has been updated.

**Comment by srajama1** [comment]
Just marking InDevelop so we update the change logs right during next release.
