### ISSUE TITLE
static asserts on blas functions

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos-kernels#339]
Particularly in batched/experimental. As far as I can tell, there's no check that the Kokkos views passed in are actually two-dimensional before calling, e.g. 

````
SerialLU_Internal<Algo::LU::Blocked>::invoke(A.extent(0), A.extent(1),
````

It's an unlikely user error, but probably good practice to check preconditions.

**Comment by kyungjoo-kim** [comment]
Batched functions are intended to perform in the functor level and it does not perform any error checking. Adding static asserts does not harm but as we have a dynrankview use case (a rank is given by ``rank()``, we cannot check the rank with static assert.
