### ISSUE TITLE
spgemm OpenMP issue, now fixed

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos-kernels#345]
@trilinos/muelu @tgvoskuilen 

Line 183 of "KokkosSparse_spgemm_impl_def.hpp" used to create owning Kokkos::View with an empty string and no dimensions.  @tgvoskuilen found this the hard way, while debugging a hang in MueLu with OpenMP.  The bug has since been fixed in both this repo and the Trilinos repo, and Tyler and I developed a hot patch for the version of Trilinos that he needs to use.  However, other users might encounter this if they haven't updated their Trilinos or kokkos-kernels repos in a while, so I'm filing it for their reference.

**Comment by mhoemmen** [comment]
Closing because this is fixed in both develop and master, and in Trilinos.

**Comment by ndellingwood** [comment]
@mhoemmen for reference (in case this is helpful) this was fixed by PR #334 during the last round of promotion testing. The bug was exposed when testing with deprecated code disabled, not sure why the code did the weird thing with empty string with no dims prior to the fix.

**Comment by mhoemmen** [comment]
Thanks @ndellingwood ! :D  

> ... not sure why the code did the weird thing with empty string with no dims prior to the fix.

@tgvoskuilen found out that it used a macro as a default value in that case, since it matched the `View(string, dim0, dim1, dim2, dim3, dim4, dim5, dim6, dim7)` constructor.  The macro evaluated to `size_t (-1)`, that is, `std::numeric_limits<size_t>::max()`.  ViewFill then used that as an upper loop bound, which I think we figured out would take about a millennium to finish ;-) .
