### ISSUE TITLE
HashmapAccumulator needs a header guard

### ISSUE THREAD

**Issue by william76** [kokkos/kokkos-kernels#367]
HashmapAccumulator doesn't have a header guard in the file.

https://github.com/kokkos/kokkos-kernels/blob/194f0f5be9117b0f1a646af783e4c79f8355fde6/src/common/KokkosKernels_HashmapAccumulator.hpp#L38-L52

**Comment by srajama1** [comment]
@william76 I assumed you are going to add it :)
