### ISSUE TITLE
  'KokkosKernels_FortranMangling.h' file not found

### ISSUE THREAD

**Issue by spdomin** [kokkos/kokkos-kernels#372]
All of my Trilinos develop nightly tests failed due to the error below.

In file included from /Users/naluIt/gitHubWork/nightlyBuildAndTest/Nalu/src/AssembleContinuityEdgeOpenSolverAlgorithm.C:13:
In file included from /Users/naluIt/gitHubWork/nightlyBuildAndTest/Nalu/include/LinearSystem.h:12:
In file included from /Users/naluIt/gitHubWork/nightlyBuildAndTest/Nalu/include/LinearSolverTypes.h:14:
In file included from /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/Tpetra_CrsMatrix.hpp:1:
In file included from /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/Tpetra_CrsMatrix_decl.hpp:64:
In file included from /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/KokkosSparse.hpp:58:
In file included from /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/KokkosSparse_spmv.hpp:51:
In file included from /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/KokkosSparse_spmv_spec.hpp:53:
In file included from /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/KokkosSparse_spmv_impl.hpp:48:
In file included from /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/KokkosBlas1_scal.hpp:47:
In file included from /Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/KokkosBlas1_scal_spec.hpp:357:
/Users/naluIt/gitHubWork/packages/install/Trilinos_nightly_release/include/KokkosBlas1_scal_tpl_spec_decl.hpp:50:10: fatal error: 
      'KokkosKernels_FortranMangling.h' file not found
#include "KokkosKernels_FortranMangling.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by mhoemmen** [comment]
https://github.com/trilinos/Trilinos/issues/4237

**Comment by mhoemmen** [comment]
Other kokkos-kernels developers: These changes were a patch to Trilinos.  I was about to add them to the kokkos-kernels repo as well, but these build errors show that we also need to test with Fortran disabled.  I think I know what to do (extra header file with "if Fortran enabled" macro to decide whether to include the Fortran mangling header file that CMake generates).

**Comment by spdomin** [comment]
As per @mhoemmen's comment above, I am closing this and referring to:

https://github.com/trilinos/Trilinos/issues/4235
