### ISSUE TITLE
linking against blas on power9 with XL

### ISSUE THREAD

**Issue by cwsmith** [kokkos/kokkos-kernels#385]
I'm attempting to build kokkos and kokkos-kernels via Trilinos and hit blas symbol mangling issues.

Trilinos: `develop` cf8101d
System: Power9 with Volta70
Compiler: XL 16.1.0 
CUDA: 10 

Similar problems with the Xl compiler have been raised a handful of times:
https://github.com/kokkos/kokkos-kernels/issues/369
https://github.com/trilinos/Trilinos/pull/4228

My environment settings and cmake command are below:

```
module load xl_r cuda/10.0 cmake mpich
export NVCC_WRAPPER_DEFAULT_COMPILER=$CXX
export NVCC=/gpfs/u/barn/ITAP/ITAPsmth/trilinos/packages/kokkos/bin/nvcc_wrapper
```

```
TRILSRCDIR=/gpfs/u/home/ITAP/ITAPsmth/barn/trilinos
blas=/gpfs/u/software/ppc64le-rhel7/blas//3.8.0_1/blas_LINUX.a

cmake \
-D CMAKE_CXX_COMPILER=${NVCC} \
-D CMAKE_C_COMPILER=xlc_r \
-D CMAKE_Fortran_COMPILER=xlf2008_r \
-D CMAKE_BUILD_TYPE:STRING=None \
-D CMAKE_INSTALL_PREFIX:PATH=$PWD/install \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D BUILD_SHARED_LIBS:BOOL=ON \
\
-D TPL_ENABLE_MPI:BOOL=ON \
-D MPI_BASE_DIR:PATH=${MPICH_ROOT} \
-D MPI_EXEC_MAX_NUMPROCS:STRING=16 \
\
-D TPL_ENABLE_BinUtils:BOOL=OFF \
-D TPL_ENABLE_Pthread:BOOL=OFF \
\
-D Trilinos_ENABLE_DEBUG:BOOL=${1} \
-D Trilinos_ENABLE_Fortran:BOOL=OFF \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
\
-D Trilinos_ENABLE_Kokkos:BOOL=ON \
-D Trilinos_ENABLE_KokkosKernels:BOOL=ON \
-D KOKKOS_ARCH:STRING="Power9;Volta70" \
-D Trilinos_ENABLE_OpenMP:BOOL=OFF \
-D TPL_ENABLE_CUDA:BOOL=ON \
-D TPL_ENABLE_BLAS:BOOL=ON \
-D TPL_BLAS_LIBRARIES:PATH=${blas} \
\
-D Trilinos_ENABLE_EXPORT_MAKEFILES:BOOL=OFF \
-D Trilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF \
\
$TRILSRCDIR
```

Running `make` produces the following output with undefined blas symbols:

```
[ 89%] Linking CXX executable KokkosKernels_matrix_converter.exe
../src/libkokkoskernels.so.12.13: undefined reference to `zgemm_'
../src/libkokkoskernels.so.12.13: undefined reference to `cgemv_'
../src/libkokkoskernels.so.12.13: undefined reference to `sdot_'
../src/libkokkoskernels.so.12.13: undefined reference to `zherk_'
../src/libkokkoskernels.so.12.13: undefined reference to `daxpy_'
../src/libkokkoskernels.so.12.13: undefined reference to `zgemv_'
../src/libkokkoskernels.so.12.13: undefined reference to `idamax_'
../src/libkokkoskernels.so.12.13: undefined reference to `ctrsm_'
../src/libkokkoskernels.so.12.13: undefined reference to `icamax_'
../src/libkokkoskernels.so.12.13: undefined reference to `isamax_'
<snip>
../src/libkokkoskernels.so.12.13: undefined reference to `ddot_'
../src/libkokkoskernels.so.12.13: undefined reference to `snrm2_'
../src/libkokkoskernels.so.12.13: undefined reference to `caxpy_'
../src/libkokkoskernels.so.12.13: undefined reference to `dtrsv_'
../src/libkokkoskernels.so.12.13: undefined reference to `zscal_'
../src/libkokkoskernels.so.12.13: undefined reference to `sscal_'
make[2]: *** [packages/kokkos-kernels/test_common/KokkosKernels_matrix_converter.exe] Error 1
```

I can work around this by making the following edits to `CMakeCache.txt`:

`F77_BLAS_MANGLE:STRING=(name,NAME) name ## _` 
changed to 
`F77_BLAS_MANGLE:STRING=(name,NAME) name ` 

and adding xlf libraries to the linking command:

`CMAKE_EXE_LINKER_FLAGS:STRING='/opt/ibm/xlf/16.1.0/lib/libxlf90_r.so /opt/ibm/xlf/16.1.0/lib/libxlfmath.so'`

Enabling fortran via the `-DTrilinos_ENABLE_Fortran:BOOL=ON` flag will fix the blas mangling but leaves the following undefined references:

```
[ 89%] Linking CXX executable KokkosKernels_matrix_converter.exe
../src/libkokkoskernels.so.12.13: undefined reference to `_xlfEndIO'
../src/libkokkoskernels.so.12.13: undefined reference to `_xlfStop'
../src/libkokkoskernels.so.12.13: undefined reference to `_xliltrm'
../src/libkokkoskernels.so.12.13: undefined reference to `_xlfBeginIO'
../src/libkokkoskernels.so.12.13: undefined reference to `_xlfWriteFmt'
```

which requires telling C++ about the fortran libraries (e.g., setting `CMAKE_EXE_LINKER_FLAGS` as done above).

On this platform, is there a cleaner way to build kokkos and kokkos-kernels via Trilinos?

**Comment by kyungjoo-kim** [comment]
This is weird. KokkosKernels cmake follows the F77_BLAS_MANGLE which is detected from Trilinos. This means that Trilinos detects a wrong mangling rule. From my test on white (our power8 and p100 testbed), I get the right fortran mangling detected ``ibm/xl/16.1.0`` and ``cuda/9.2.88``. 

@nmhamster Is this something new from Volta and cuda 10 ?

**Comment by srajama1** [comment]
@kyungjoo-kim : @nmhamster doesn't check github updates often, you might want to send an email or walk to his office :)

**Comment by nmhamster** [comment]
@kyungjoo-kim - the Fortran libraries are required if linking against ESSL and/or OpenBLAS because the XLF compiler uses these functions. It sounds the name mangling test isn't applied if Fortran isn't enabled - is that correct?

**Comment by kyungjoo-kim** [comment]
@nmhamster I think that you are right. Fortran name mangling test is enabled with the fortran cmake flag.

**Comment by nmhamster** [comment]
Should we talk to @bartlettroscoe about having an option to enable the CMake query? Its likely this will come up on many BLAS installs.

**Comment by bartlettroscoe** [comment]
Don't have any experience with BLAS with XL on Power9.    You should be able to set `F77_BLAS_MANGLE`` on the CMake commandline like:

```
-D F77_BLAS_MANGLE=(name,NAME) name
```

What machine is this?

**Comment by kyungjoo-kim** [comment]
@bartlettroscoe  That is very convenient.  

@cwsmith This might be your solution. 
1. Fortran mangling detection: As @bartlettroscoe said, you can either explicitly define the mangling or enabling fortran compiler will find the right mangling scheme. 
2. Additional linker statement: I am not sure if the module system can provide this automatically. The module system append library path but you should define your linker statement manually. For instance, 
```
// control the optional parameter in the command line
if [ "${USE_XL}" == "ON" ]
  LDFLAGS = -L${LD_LIBRARY_PATH}  -lxlf90_r -lxlfmath 
fi
// then define it as the cmake option
-D CMAKE_EXE_LINKER_FLAGS:STRING=${LDFLAGS}
```

**Comment by cwsmith** [comment]
@bartlettroscoe This was on an in-house [IBM Power System AC922 node](https://secure.cci.rpi.edu/wiki/index.php?title=IBM_Power_9).  It is very similar to a Summit node.

@kyungjoo-kim Thank you.  I'll give this a closer look and try it.

**Comment by srajama1** [comment]
@cwsmith Did the change suggested by @kyungjoo-kim help ? I am checking to see if this issue still exists.

**Comment by cwsmith** [comment]
@srajama1 With kokkos 68783a8 I was able to build on the RPI AC922 system by setting `CMAKE_EXE_LINKER_FLAGS` and enabling ' Trilinos_ENABLE_Fortran`.

**Comment by srajama1** [comment]
Perfect, thanks ! We will add this to the wiki on compiling and close the issue.
