### ISSUE TITLE
GEMM has no CudaUVMSpace specializations for cuBLAS

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos-kernels#397]
Kokkos-kernels' GEMM struct, called by `KokkosBlas::gemm`, has no CudaUVMSpace specializations that call cuBLAS.  It has CudaSpace specializations:

https://github.com/kokkos/kokkos-kernels/blob/4ee5f3c6dbd0981f6d8c7a9b2b1763439cb56039/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_avail.hpp#L121

but no CudaUVMSpace specializations.  @vbrunini and I found this out by benchmarking Belos solves with Tpetra objects.  We found that the `X^T * Y` operation (`Tpetra::MultiVector::multiply`) for tall and skinny X and Y was _very_ slow compared to the CPU, even though the GPU solves as a whole were faster than the CPU solves.  Kokkos profiling led us to labels that only the default implementation of GEMM would use.

The logical fix would be to add CudaUVMSpace specializations to that file.  We're trying that now.  This shouldn't add too much code, since it just dispatches to cuBLAS.  Another approach would be to change how `gemm_tpl_spec_avail` works, so that the macros fill in ExecSpace and MemSpace, instead of just MemSpace.  Then, you would set `Cuda, AnonymousSpace` and thus have only one specialization.

**Comment by mhoemmen** [comment]
@vbrunini reports that adding CudaUVMSpace specializations improves radiosity solve time by 2x overall, and reduces `Tpetra::MultiVector::multiply` time from 23.7s to 1.2s.  I will implement this fix.

**Comment by mhoemmen** [comment]
- Kokkos-kernels PR: https://github.com/kokkos/kokkos-kernels/pull/399
- Trilinos PR (same changes): https://github.com/trilinos/Trilinos/pull/4649

**Comment by ndellingwood** [comment]
PR #399 merged with a fix, thanks @mhoemmen and @kyungjoo-kim !

**Comment by ndellingwood** [comment]
I labeled as Enhancement, but please re-label as Bug if I mis-diagnosed this.
