### ISSUE TITLE
KokkosBatched PerfTests need lambda guards

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#407]
PR #391 caused multiple Jenkins jobs to fail due to build errors. From a quick glance, it looks like there may be new performance tests using lambdas which cause the failure, sample snip from the Jenkins email:

`kokkos-kernels/perf_test/batched/KokkosBatched_Test_BlockTridiagDirect.cpp(237)`

[Link to one of the failing builds for reference: ](https://jenkins-son.sandia.gov/job/KokkosKernels_White_CudaOpenMP_cuda_10_gcc_740/106/)

@kyungjoo-kim do you have time to look at this? Kokkos and KokkosKernels don't enable lambda support by default because this is still marked as an "experimental" feature in Cuda, I don't think Christian is willing to change the default behavior until it is no longer considered experimental. However, Trilinos requires that lambda support is enabled while building with Cuda which is why this did not show up in the Trilinos PR.

The suggested fix (what I've done in Kokkos anyway) would be to guard the tests so that they don't build/run when lambdas are not explicitly enabled, using macro guards like this:

```
#if defined( KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA )
#if !defined(KOKKOS_ENABLE_CUDA) || ( 8000 <= CUDA_VERSION )
```

See for example this [unit test snip](https://github.com/kokkos/kokkos/blob/2a32d301cb07846f30722fa8de09f80c1ad272d7/core/unit_test/TestMDRange.hpp#L268-L285) 

Edit: The second macro guard is so the tests still build in non-Cuda builds regardless of the whether the enable_lambda option is set - that is required for Cuda builds specifically; the Cuda version >= 8 is because we still test Cuda 7.5 which has no lambda support.

**Comment by srajama1** [comment]
I don't like the suggested fix. This would disable the test on platforms of interest to us, it might be ok for others, but not for this test.

**Comment by ndellingwood** [comment]
@srajama1 The alternative is for the test to be rewritten using functors, then no disable based on configuration is necessary.

**Comment by srajama1** [comment]
Yep

**Comment by kyungjoo-kim** [comment]
I use lambda everywhere in trilinos, kokkoskernels, and whatever I am working on. kokkoskernels unit test also use labmda with ifdef guard. I think that the ifdef guard is enough.

**Comment by srajama1** [comment]
You mean you are disabling the tests everywhere in our nightly testing ?

**Comment by srajama1** [comment]
I suggest adding builds with lambda enabled then.

**Comment by ndellingwood** [comment]
@srajama1 I'll add a nightly test where we enable lambdas with a Cuda build. As far as the macro, it would disable the guraded tests in nightly Cuda builds (not host), so we the extra build with lambdas is a good idea.

**Comment by kyungjoo-kim** [comment]
This is not a unit test. So, correctness of the kokkoskernels is always checked by nightly tests. When we do perf test and if we do the perf test automatically, we can separately set up jenkins job script with enabling lambda. Practically, trilinos already uses lambda and I dont see any reason why we cannot set the jenkins tests with lambda.

**Comment by srajama1** [comment]
Alright, I am ok with using the ifdef if we setup a build with lambdas turned on.

**Comment by kyungjoo-kim** [comment]
@ndellingwood Sorry that my PR caused the failure. Do you want me to submit another PR or you can include the fix in your working PR if you have one ?

**Comment by ndellingwood** [comment]
@kyungjoo-kim no worries, could you submit a PR? I haven't started working on one, just did the starting triage work.

**Comment by kyungjoo-kim** [comment]
okay. see ya soon.

**Comment by ndellingwood** [comment]
Thanks!

**Comment by kyungjoo-kim** [comment]
@vqd8a BTW, team blas actually uses lambda in the unit testing and it also has the ifdef guard in the cuda tests, which means that these are not tested in our nightly tests although they are tested in Trilinos PR.

**Comment by kyungjoo-kim** [comment]
@ndellingwood done. plz, merge the PR with your super power.

**Comment by ndellingwood** [comment]
@kyungjoo-kim Merged, thanks for quick fix!

**Comment by ndellingwood** [comment]
Nightly Cuda build with lambdas enabled created:
[link](https://jenkins-son.sandia.gov/view/KokkosKernels/job/KokkosKernels_White_CudaSerial_cuda_92_gcc_720-enablelambda/)

**Comment by srajama1** [comment]
@ndellingwood : Thank you !
