### ISSUE TITLE
Create examples for Distance-1 and Distance-2 Graph Coloring

### ISSUE THREAD

**Issue by william76** [kokkos/kokkos-kernels#413]
Create examples for Distance-1 and Distance-2 graph coloring.

They should be put in: 
- `example/graph/KokkosKernels_Example_Distance1GraphColor.cpp`
- `example/graph/KokkosKernels_Example_Distance2GraphColor.cpp`

Requirements: 
- Basically do what the `perf_test` samples do but keep it as 'bare bones' as possible for an exmaple.
- Load MatrixMarket graphs.

**Comment by srajama1** [comment]
This is good to do ...

**Comment by srajama1** [comment]
@william76 Was this ever done ?

**Comment by william76** [comment]
@srajama1 I never did get a chance on that... I got buried with doing Xpetra ETI work this summer.  The distance-2 graph coloring perf test is actually a pretty good example... I'll see if I can strip it down a little and remove some dependencies from the `test_common/` files.  Do you know of any code infrastructure that's baked into Kokkos or Kokkos-Kernels to load MatrixMarket data into a CrsMatrix or StaticGraph?  The perf_test codes leverage `test_common/MyCRSMatrix.hpp` but for an example, I'd rather avoid relying on test headers if possible.

**Comment by ndellingwood** [comment]
@william76 - here is some glue for an internal impl matrix market reader that takes a filename and store as a CrsMatrix. It won't handle matrix market files of "pattern" type properly right now but I think @brian-kelley is working on a fix.

```
#include <KokkosKernels_IOUtils.hpp>
 
typedef KokkosSparse::CrsMatrix<scalar_t, lno_t, execution_space, void, size_type> crsmat_t;
crsmat_t triMtx = KokkosKernels::Impl::read_kokkos_crst_matrix<crsmat_t>(lfilename.c_str());
```

**Comment by mhoemmen** [comment]
@brian-kelley If you need an example of how to handle "pattern" matrices, check out the Tpetra Matrix Market reader.

**Comment by william76** [comment]
I put in a PR with a somewhat stripped down version of the D2GC code from the `perf_test` directory...

@brian-kelley the D2GC code is also used in the MueLu Aggregation routines. I think it's still using the `D2_SERIAL` algorithm but changing it there should be just a matter of changing which enum is passed in.

**Comment by brian-kelley** [comment]
@william76 KokkosKernels PR #466 with the full MatrixMarket support will probably be merged in the next few days. Then you don't even need to deal with CrsMatrix, you can just do
```
crsGraph_t graph = KokkosKernels:Impl::read_kokkos_crst_graph<crsGraph_t>("file.mtx");
```
and that will read a pattern file (or any matrix, and discard the scalar values).

**Comment by william76** [comment]
@brian-kelley ooh, cool!  I'll hold off mucking around with this D2GC example till that's in =)  When that's merged in can you shoot me a note?

**Comment by brian-kelley** [comment]
@william76 It was just merged.
