### ISSUE TITLE
KokkosKernels Trilinos Integration

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos-kernels#42]
This issue is for the kokkoskernels integration into trilinos. 

After commits : 
77a2fde5987c01723e327169397985703f9467d7 and f9b15595317af4f9990d95aaef79ffae4fe0c8fa
cmake files should be ready to configure and compile "only" kokkoskernels in trilinos.

Next steps are to adapt the changes in the namespaces and filenames to rest of trilinos that uses kokkoskernels directly. To my knowledge, we have ifpack2 and tpetra that use kokkoskernels directly. Please extend this list if there are more packages.

For changes to be done in Trilinos, I created the branch:
  https://github.com/mndevec/Trilinos/tree/kk_integration

**Comment by mndevec** [comment]
I made changes to Tpetra and Ifpack2 files in https://github.com/mndevec/Trilinos/tree/kk_integration

Tpetra multivector compilation was failing because of the issue:
https://github.com/kokkos/kokkos/issues/594

I turned off the static asserts in Kokkos to pass through that step. Other than that Ifpack2 and Trilinos compiled fine on my workstation (gcc-5.1.0). However, multivector tests fails. Hopefully this will go away with this issue. 

Another issue is: Tpetra multivector was using Impl:SquareRootFunctor which was functor in KokkosBlas Impl namespace. The file was removed after files are restructured. 
I put back the functor to KokkosKernels_Utils.hpp for now.

**Comment by mhoemmen** [comment]
@mndevec If you need to move `Impl::SquareRootFunctor` to Tpetra, please feel free to do so.

**Comment by mndevec** [comment]
Mark, for now I think we will leave it in the current way. It will be better to remove such dependencies in Tpetra in future. I opened the related issue in Trilinos repo.

**Comment by mndevec** [comment]
The compilation issues for the layoutleft/right conversions for rank=0 views are solved after Kokkos update: https://github.com/kokkos/kokkos/issues/594#issuecomment-320742183
