### ISSUE TITLE
Provide find modules for TPLs for standalone cmake

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos-kernels#429]
The current list of TPLs are:

* quadmath 
* MKL 
* BLAS LAPACK 
* CUSPARSE
* yaml-cpp

**Comment by mhoemmen** [comment]
quadmath is for `__float128`, which is attractive to keep around.  It should come with an installed GCC.

**Comment by jjwilke** [comment]
Decision to be made is how optional TPLS should be specified:

* Match Trilinos: -DTPL_ENABLE_<X>
* Match standalone Kokkos: -DKokkosKernels_ENABLE_<X>

**Comment by ndellingwood** [comment]
@jjwilke should this be closed since the first wave of TPL support went in for 3.0.00?

**Comment by ndellingwood** [comment]
Follow up requests like SuperLU have a separate issue.

**Comment by jjwilke** [comment]
Yep. Closing.
