### ISSUE TITLE
KokkosKernels Trilinos Integration Threads Compilation Failure

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos-kernels#43]
@crtrott @srajama1 
I am having some issues when I enable Threads in KokkosKernels. 

With standalone make:
 - if I enable serial and pthreads, it works fine. 
 - if I enable openmp,serial, and pthreads, the unit tests fail, because of kokkos::initialize initializes openmp, and then the initialization of pthreads fails. I don't know if that is a case we should support, but I do not know how to fix this issue. 

Within Trilinos cmake,
 - If I enable pthreads, the compilation fails because of undefined reference errors.

**Comment by mndevec** [comment]
Kokkos does not support 100% the use of OpenMP and Threads, therefore first problem is not a real issue. 

However, trilinos pthread compilation still remains to be problem for my workstation. @crtrott , could you have a look at this problem?

**Comment by hcedwar** [comment]
Kokkos specifically prohibits the simultaneous use of OpenMP and Threads (pthreads) back-ends due to a whole set of performance (even livelock) problems.  The error message should have said as much.  Perhaps the error message needs to be more clear about this restriction?

**Comment by mndevec** [comment]
The error messages I was getting are below. I don't know if there were more error messages about this, they might not be displayed as gtest emits standard output. 

In this unit test, Kokkos::initialize() initializes openmp, and then pthreads; and below error is thrown as a result of this. I was not getting this error if I specifically initialize execution spaces such as Kokkos::Threads::initialize() when all execution spaces are enabled in the compilation. 

Does kokkos prohibit the simultaneous use of them at runtime or compile time?

```
[ RUN      ] threads.common_ArithTraits
unknown file: Failure
C++ exception with description "ThreadsExec::resize_scratch FAILED : Threads not initialized.
Traceback functionality not available
" thrown in the test body.
[  FAILED  ] threads.common_ArithTraits (0 ms)
[ RUN      ] threads.graph_graph_color_double_int_int_TestExecSpace
unknown file: Failure
C++ exception with description "Constructing View and initializing data with uninitialized execution space
Traceback functionality not available
" thrown in the test body.
[  FAILED  ] threads.graph_graph_color_double_int_int_TestExecSpace (81 ms)
```


 prohibits the simultaneous use of OpenMP and Threads

**Comment by crtrott** [comment]
You are probably on an older version of Kokkos which didn't have the "I don't allow you to do this" in it.

**Comment by mndevec** [comment]
Closing the issue, rest can be followed in #46
