### ISSUE TITLE
Option names for standalone CMake: all caps vs. camel case

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos-kernels#433]
Kokkos also deals with this issue. Trilinos names are `-DKokkos` but CMake style guide is `-DKOKKOS`.  Kokkos does some magic to support either input, but all the internal logic is implemented in terms of `KOKKOS_X` variables.

There is a lot of `KokkosKernels_X` and `Kokkos_X` logic based on camel case in the current repo. Do we:

* Move everything to upper case to match Kokkos and do the same remapping trick?
* Keep everything as is, but break with CMake and Kokkos style

**Comment by mhoemmen** [comment]
Whatever you decide, could you please test with Trilinos and not break existing `-DKokkos` names?  Thanks!

**Comment by dalg24** [comment]
What CMake style guide are you referring to?

**Comment by jjwilke** [comment]
> What CMake style guide are you referring to?

Nothing in particular. The collective unconscious of CMake on the internet.

**Comment by dalg24** [comment]
I think the convention is to prefix variables with `<PackageName>_`

**Comment by jjwilke** [comment]
On various mailing lists, anyway (and didn't you say also in your presentation?) the convention is for cache variables to be all caps. I really don't care either way. Pre-dating my CMake changes, there's a bunch of logic around setting both <PackageName>_X and <PACKAGENAME_X>.

Either choice is fine with me. I can set the CMake warnings/errors to allow either one or declare either one as preferred.

**Comment by dalg24** [comment]
https://dalg24.github.io/kokkos/#/7/6

Yes kokkos/kokkos#2104 does clean things up :)

**Comment by ndellingwood** [comment]
@jjwilke I think this can be closed?
