### ISSUE TITLE
Kokkos Blas: gemv segfaults

### ISSUE THREAD

**Issue by cgcgcg** [kokkos/kokkos-kernels#443]
I am trying to use `KokkosBlas::gemv` in transpose mode, but I am getting segfaults. I also see that this case is not being tested. Does this mean that it should not be trusted and that I should not be using it?

**Comment by srajama1** [comment]
Let us fix it. More details please !

**Comment by cgcgcg** [comment]
I hacked the unit test to include the cases that segfault for me. Will send it to you.

**Comment by ndellingwood** [comment]
@iyamazaki also reported running into this issue

**Comment by srajama1** [comment]
Can we add a test for transpose ? Adding @kyungjoo-kim and @crtrott who lead all BLAS related stuff to keep them in the loop

**Comment by ndellingwood** [comment]
@cgcgcg I think this should have been fixed in PR #514 which made it into Trilinos release with 2.9.99 (3.0 minus copyright updates).
