### ISSUE TITLE
KokkosGraph: output colors assigned during graph coloring

### ISSUE THREAD

**Issue by rohit-mp** [kokkos/kokkos-kernels#444]
Currently, KokkosGraph coloring programs provide no option to output the colors assigned by it during its execution. It would be nice to have an option to output the colors to a file for later reference.

I tinkered with the source code a bit and got the feature running. So if it's fine, I'd like to create a PR for the same.

**Comment by srajama1** [comment]
@rohit-mp We will be happy to accept PRs for this. Just put me and @william76 on that PR, we can look at coloring related things.

**Comment by william76** [comment]
@rohit-mp @srajama1 

There is an interface in the distance-2 graph coloring handle to get the colors:
`KokkosGraph::GraphColorDistance2Handle::get_vertex_colors()` returns the graph colors into a view:
https://github.com/kokkos/kokkos-kernels/blob/d86db111124cea12e23dd3447b6c307f96ef7439/src/graph/KokkosGraph_Distance2ColorHandle.hpp#L325-L327

I did put in a function in the handle as well to dump out the coloring into a graphviz file.  You can find that routine here:
https://github.com/kokkos/kokkos-kernels/blob/d86db111124cea12e23dd3447b6c307f96ef7439/src/graph/KokkosGraph_Distance2ColorHandle.hpp#L376-L395

It does more in there than you might want but it might be useful as a guide.  An example of the graphviz writer being used lives in the distance-2 graph coloring perf test... if the graph has fewer than 1500 nodes, a .dot file will be output by the test application:
https://github.com/kokkos/kokkos-kernels/blob/d86db111124cea12e23dd3447b6c307f96ef7439/perf_test/graph/KokkosGraph_color_d2.cpp#L366-L388

It should be pretty easy to get the node to color mapping out by having a look at what the dump_graphviz() function is doing... it could be copied and modified pretty easily into something that just dumps out a CSV file containing the node/color pairs.

Hopefully this information is helpful...

**Comment by rohit-mp** [comment]
@william76 

Thanks for the information! What I've done now is kinda similar. I've used the same ```get_vertex_colors()``` interface to get a view and printed it out except that the function I've created lies in ```src/common/KokkosKernels_PrintUtils.hpp```

I've also added another option to possible argument ```--outputfile``` or ```-o``` since ```KokkoksKernels::Experiment::Parameters``` already had the option of a ```coloring_file_output``` but ```dump_graphviz``` uses the verbose argument.
https://github.com/kokkos/kokkos-kernels/blob/d86db111124cea12e23dd3447b6c307f96ef7439/test_common/KokkosKernels_TestParameters.hpp#L44-L64

Could you have a look at the PR and let me know if it's fine or if I should change it to be similar to ```dump_graphviz``` and not involve PrintUtils since the function might not be useful for all programs and doesn't make much sense to keep it in the common folder.

**Comment by srajama1** [comment]
@rohit-mp : We do not close the issue until we merge changes into master as that is what most users to see. Whoever does the master merge will close it at that time. Let us leave it open till then.

**Comment by rohit-mp** [comment]
Ah sorry, my bad.
