### ISSUE TITLE
Revamp the ETI system

### ISSUE THREAD

**Issue by srajama1** [kokkos/kokkos-kernels#460]
It is silly to generate 500 files for every new feature. We are going in a path that is not scalable, let us delete these files and add a configure option where we generate these on the fly.

**Comment by mhoemmen** [comment]
It would be nice, while we're at it, not to instantiate sparse matrix kernels for both offset types.

**Comment by srajama1** [comment]
@jjwilke Can this be the next after the spack, cmake work ?

**Comment by ndellingwood** [comment]
Cross-referencing #496
