### ISSUE TITLE
Kokkos Kernels tests uses `std::random_shuffle`, which is deprecated in C++17

### ISSUE THREAD

**Issue by dhollman** [kokkos/kokkos-kernels#463]
Thus, tests do not compile with `KOKKOS_ENABLE_CXX17`

**Comment by ndellingwood** [comment]
Occurs in `unit_test/sparse/Test_Sparse_spadd.hpp` at line 64.

**Comment by ndellingwood** [comment]
@dhollman PR #464 merged to address this, thanks for reporting.
