### ISSUE TITLE
"standard" install location

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos-kernels#467]
Install in the package name folder `lib/cmake/KokkosKernels`.

The discussion of lib vs lib64 is pending, but delayed for now. Related to https://github.com/kokkos/kokkos/issues/2283

**Comment by ndellingwood** [comment]
@jjwilke just to confirm, we are now using GNUInstallDirs in #491 and this is resolved?

**Comment by jjwilke** [comment]
Yes, this is resolved.

**Comment by ndellingwood** [comment]
Part of #491
