### ISSUE TITLE
test_all_sandia fails with missing kokkos/core/src/Makefile

### ISSUE THREAD

**Issue by vqd8a** [kokkos/kokkos-kernels#477]
Has anyone encountered this issue? When I run the KK spotcheck with the ```test_all_sandia``` script (against Kokkos develop branch), it fails because the ```kokkos/core/src/Makefile``` cannot be found. Message below:  
```make[2]: /ascldap/users/vqdang/Kokkos/kokkos/core/src/Makefile: No such file or directory```
```make[2]: *** No rule to make target `/ascldap/users/vqdang/Kokkos/kokkos/core/src/Makefile'.  Stop.```

If I remember correctly, this Makefile has recently been removed from ```kokkos/core/src/```. 

Please let me know how to run KK spotcheck.

**Comment by ndellingwood** [comment]
@vqd8a to run spot-checks use the master branch of Kokkos. Changes in Kokkos develop branch while working on CMake support resulted in removal of ability to install Kokkos using the Makefile build system, see kokkos/kokkos#2332 and kokkos/kokkos#2339 for details.

**Comment by ndellingwood** [comment]
Following completion/stabilization of kokkos/kokkos#2299 (updating of automated testing scripts) and merge of PR #471 we will need to do add similar new scripts for kokkos-kernels to regain ability to test against kokkos develop branch. This will be a requirement before the 3.0 release.

**Comment by ndellingwood** [comment]
cm_test_all_sandia and cm_generate_makefile.bash have been added, closing this issue.
