### ISSUE TITLE
SPMV Documentation Incomplete

### ISSUE THREAD

**Issue by csiefer2** [kokkos/kokkos-kernels#484]
Could we please put a formula on the page that says what this routine actually does, specifically what part of the calculation alpha and beta are applied to?

https://github.com/kokkos/kokkos-kernels/wiki/SPARSE-2%3A%3Aspmv

**Comment by csiefer2** [comment]
@ndellingwood

**Comment by ndellingwood** [comment]
@csiefer2 page updated, it computes

`y = beta*y + alpha*Op(A)*x`

**Comment by lucbv** [comment]
I feel this can be closed now...
