### ISSUE TITLE
Bug in test_all_sandia: Some complex_double tests are failing on white with "--with-tpls=cublas"  

### ISSUE THREAD

**Issue by seheracer** [kokkos/kokkos-kernels#489]
### Description

Some complex_double tests fail on white (Pascal60) when test_all_sandia script is used with the cublas option:

./test_all_sandia cuda --spot-check --with-cuda-options=enable_lambda --with-tpls=cublas --arch=Power8,Pascal60 

Output:
[----------] Global test environment tear-down
[==========] 365 tests from 1 test case ran. (108251 ms total)
[  PASSED  ] 341 tests.
[  FAILED  ] 24 tests, listed below:
[  FAILED  ] openmp.abs_complex_double
[  FAILED  ] openmp.team_abs_complex_double
[  FAILED  ] openmp.axpby_complex_double
[  FAILED  ] openmp.team_axpby_complex_double
[  FAILED  ] openmp.axpy_complex_double
[  FAILED  ] openmp.team_axpy_complex_double
[  FAILED  ] openmp.dot_complex_double
[  FAILED  ] openmp.mult_complex_double
[  FAILED  ] openmp.team_mult_complex_double
[  FAILED  ] openmp.reciprocal_complex_double
[  FAILED  ] openmp.scal_complex_double
[  FAILED  ] openmp.team_scal_complex_double
[  FAILED  ] openmp.update_complex_double
[  FAILED  ] openmp.team_update_complex_double
[  FAILED  ] openmp.gemv_complex_double
[  FAILED  ] openmp.team_gemv_complex_double
[  FAILED  ] openmp.sparse_gauss_seidel_kokkos_complex_double_int_int_TestExecSpace
[  FAILED  ] openmp.sparse_gauss_seidel_kokkos_complex_double_int64_t_int_TestExecSpace
[  FAILED  ] openmp.sparse_gauss_seidel_kokkos_complex_double_int_size_t_TestExecSpace
[  FAILED  ] openmp.sparse_gauss_seidel_kokkos_complex_double_int64_t_size_t_TestExecSpace
[  FAILED  ] openmp.sparse_block_gauss_seidel_kokkos_complex_double_int_int_TestExecSpace
[  FAILED  ] openmp.sparse_block_gauss_seidel_kokkos_complex_double_int64_t_int_TestExecSpace
[  FAILED  ] openmp.sparse_block_gauss_seidel_kokkos_complex_double_int_size_t_TestExecSpace
[  FAILED  ] openmp.sparse_block_gauss_seidel_kokkos_complex_double_int64_t_size_t_TestExecSpace

### Possible solution (by @vqd8a):
Changing line 299 of test_all_sandia from 
KOKKOS_OPTIONS="eti-only,blas-mangle_,blas-return-complex"
to
KOKKOS_OPTIONS="--with-options=eti-only,blas-mangle_,blas-return-complex"

**Comment by ndellingwood** [comment]
With the Makefile build system going away and testing now using the cm_test_all_sandia script for the CMake build system (where this isn't an issue) I'm going to close this.
