### ISSUE TITLE
Sequential SOR is not tested

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#494]
Tpetra uses our sequential SOR in ``CrsMatrix::localGaussSeidel()``, but it is not tested at all within KokkosKernels.

Make a simple test that generates a diagonally dominant matrix (like the parallel GS tests) and runs a few sweeps, then checks the residual.

**Comment by mhoemmen** [comment]
There should be a test already in Ifpack2 or Tpetra for this -- you could just copy-paste it.  It makes sense for there to be a test in each package, since Ifpack2 provides a global preconditioner and kokkos-kernels the local kernel.

**Comment by brian-kelley** [comment]
Fixed in #515

**Comment by mhoemmen** [comment]
@brian-kelley U ROCK :D
