### ISSUE TITLE
spgemm cuda build with complex_double: error( cudaErrorMisalignedAddress) with Kokkos develop branch

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#500]
The following spgemm unit test fails when building kokkos-kernels with the kokkos develop branch, detected during testing of PR #491 :

`cuda.sparse_spgemm_kokkos_complex_double_int_int_TestExecSpace`

With error message 

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaFuncGetAttributes( &attr, cuda_parallel_launch_local_memory<DriverType>) error( cudaErrorMisalignedAddress): misaligned address /home/ndellin/kokkos-kernels-stable/testing/Testing/kokkos-install/include/Cuda/Kokkos_Cuda_KernelLaunch.hpp:439
Traceback functionality not available
```

The failure follows from changes to `Kokkos::Complex` as discussed in kokkos/kokkos#2255. @jjwilke confirmed that removal of `alignas` from `Kokkos::Complex` returns the test to passing, mentioned [in this comment](https://github.com/kokkos/kokkos-kernels/pull/491#issuecomment-556058791)

----

Additional debug info:

Use of the kernel logger from kokkos-tools shows that the failure occurs in this kernel:
`KokkosP: KokkosSparse::NumericCMEM::KKSPEED::GPU`

Where the code where this is called can be seen [here](https://github.com/kokkos/kokkos-kernels/blob/327ca9f716ccf803154c66974c82d4cc67341248/src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp#L546-L551)

Defining `KOKKOSKERNELS_VERBOSE=true` and adding some print statements yields this output of sizes that may be relevant:

```
NumericCMEM -- thread_memory:2016 unit_memory:28 initial key size:71
NumericCMEM -- adjusted hashsize:64 shmem_key_size:72
GPU vector_size:32 team_size:8 chunk_size:16

a_row_cnt = 10000  team_row_chunk_size = 16
num_teams = 626
suggested_team_size = 8 
suggested_vector_size = 32
```

----

Reproducer instructions:

Building kokkos-kernels against kokkos' develop branch currently requires the `cmake-rebased` branch of kokkos-kernels from this [cmake PR](https://github.com/kokkos/kokkos-kernels/pull/491)

These instructions are based on a build on kokkos-dev-2 which has access to SEMS modules

```
module load sems-cmake/3.12.2 sems-cuda/9.2 sems-gcc/7.2.0

cd <KOKKOSPATH>/kokkos
git checkout develop

cd <KOKKOSKERNELSPATH>/kokkos-kernels
git checkout cmake-rebased

mkdir testing/cmake
cd testing/cmake

../../cm_generate_makefile.bash --kokkoskernels-path=${PWD}/../../ --kokkos-path=<KOKKOSPATH>/kokkos --with-serial --with-cuda --with-scalars=double,complex_double --with-ordinals=int --with-offsets=int --with-layouts=layoutleft --arch=SNB,Volta70 --compiler=<KOKKOSPATH>/kokkos/bin/nvcc_wrapper --with-tpls=cublas --kokkos-make-j=1

make -j12

cd unit_test

./KokkosKernels_sparse_cuda --gtest_filter=cuda.sparse_spgemm_kokkos_complex_double_int_int_TestExecSpace
```

**Comment by ndellingwood** [comment]
The failure occurs due to how the allocation of shared memory per team is split among various pointers into the allocation (e.g. begins, nexts, keys, vals used by the HashMapAccumulator) by a heuristic that does not account for alignment when accessing vals (hence the misaligned address error). I think I have the start of a fix.

**Comment by jjwilke** [comment]
@ndellingwood Ah, okay. Good catch. So this is almost certainly a KokkosKernels problem, not a Kokkos issue.

**Comment by srajama1** [comment]
@brian-kelley @seheracer

**Comment by crtrott** [comment]
Note you should fix this not just for complex, but you need to take alignment in general into account. We had the same mistake in our shared memory allocation before - shared memory on CUDA must be correctly aligned for the data type, other wise you get this access error.

**Comment by ndellingwood** [comment]
Similar shmem alignment issues in `PortableNumericCHASH` ctor. In part it requires a similar fix for shared mem like I'm doing in `NumericCMEM`, but also looks like adjustment of the memory pool's chunk size is needed to fix other alignment issues, working on this.
