### ISSUE TITLE
HashmapAccumulator has several unused members, misnamed parameters

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#508]
The HashmapAccumulator has three members (``hash_key_size``, ``max_value_size``, and ``used_size``) that are not used internally, but they are set by the constructors. ``used_size_`` and ``max_value_size_`` (with trailing underscores) are instead passed to the insert() routines. 

``hash_key_size_`` is not passed to any insert routines. It is the number of possible hash outputs, aka 1 plus the bit mask that forms the hash function: ``hash(value) = value & (hash_key_size - 1)``.

I think these changes would make sense and make things a lot more readable and debuggable:

- ``max_value_size`` is the length of the ``keys`` and ``nexts`` arrays, so it should be an immutable member. ``max_value_size_`` should not be passed into the insert routines. In fact, what SPGEMM symbolic does now is read out the member from the hashmap and pass it in.
- ``max_value_size`` should really be called ``capacity`` or something similar - it's meaning is the length of the two arrays (keys, nexts).
- ``used_size`` is an atomically incremented counter that measures how full the hashmap is. It is updated in parallel, so it usually lives in shared/global memory. It should either not be a member and just be passed by ref to insert, OR kept as a member, but be a pointer.
- 3 ways to deal with ``hash_key_size``:
  - Remove the member, since it is unused
  - Keep it as an immutable member, and have ``KOKKOS_FORCEINLINE_FUNCTION key_type hash()`` be a member of Hashmap. The SPGEMM code wouldn't need to keep the hash mask as a local variable anymore.
  - Keep as immutable member, and instead of passing the both the key and the hash to insert(), just pass the key, and compute the hash internally.

**Comment by ndellingwood** [comment]
I'll mark this cleanup enhancement since this isn't a bug

**Comment by e10harvey** [comment]
> Keep as immutable member, and instead of passing the both the key and the hash to insert(), just pass the key, and compute the hash internally.

@brian-kelley: Although removing `hash_key_size` is the simplest solution. I will attempt to refactor all the code to compute the hash internally, within HashmapAccumulator. Computing the hash internally is a step in the right direction. There is one special use-case of https://github.com/kokkos/kokkos-kernels/blob/750fe24508a69ed4dba92bb4a9e17a6094b1a083/src/common/KokkosKernels_HashmapAccumulator.hpp#L442-L502 in https://github.com/kokkos/kokkos-kernels/blob/750fe24508a69ed4dba92bb4a9e17a6094b1a083/src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp#L433-L444 which calculates the hash using modulo instead of bit-wise AND.

This same use-case is making completely removing `max_value_size` as a parameter challenging.

**Comment by srajama1** [comment]
Keep in mind this is used at the very low level. Performance of this data structure is important for the performance of the kernels.

**Comment by e10harvey** [comment]
> Keep in mind this is used at the very low level. Performance of this data structure is important for the performance of the kernels.

Thanks, Siva. What are the reasons for calculating the hash outside of the inlined HashmapAccumulator insertion routines?

**Comment by srajama1** [comment]
I don't see a particular use case for that.

**Comment by e10harvey** [comment]
I mean, we are currently calculating the hash outside of the inlined HashmapAccumulator insertion routines. Why are we doing this?

**Comment by brian-kelley** [comment]
@e10harvey I guess you could make ``bool powerOfTwoHashSize`` a template parameter, and that way no flags need to be stored and there's no runtime overhead. However you do it, we definitely need to use bitwise-AND masking where possible because integer div/mod are expensive on CUDA.

**Comment by e10harvey** [comment]
> @e10harvey I guess you could make `bool powerOfTwoHashSize` a template parameter, and that way no flags need to be stored and there's no runtime overhead. However you do it, we definitely need to use bitwise-AND masking where possible because integer div/mod are expensive on CUDA.

Thanks @brian-kelley. This is exactly what I've started.

**Comment by e10harvey** [comment]
> > @e10harvey I guess you could make `bool powerOfTwoHashSize` a template parameter, and that way no flags need to be stored and there's no runtime overhead. However you do it, we definitely need to use bitwise-AND masking where possible because integer div/mod are expensive on CUDA.
> 
> Thanks @brian-kelley. This is exactly what I've started.

@brian-kelley: Actually, thinking about this more, is there any reason against adding the following to the constructor bodies:
```cpp
compute_hash_func = compute_hash_func_table[__hash_op];
```

Then the instertion routines will invoke:
```cpp
hash = compute_hash_func(arg1, arg2);
```

**Comment by brian-kelley** [comment]
@e10harvey Function pointers/first-class functions incur overhead on CPUs and I don't think they can be used at all in CUDA. I would just go with the template.

**Comment by brian-kelley** [comment]
Actually function pointers are supported in all CUDA versions supported by Kokkos, but they still have a performance cost.
