### ISSUE TITLE
Need BLAS interface for <>trsm

### ISSUE THREAD

**Issue by srajama1** [kokkos/kokkos-kernels#513]
This is a user request for Exawind milestone runs. @iyamazaki

@vqd8a : Do you have time do it ? Ideally we would like it in 3.0

**Comment by vqd8a** [comment]
@srajama1 do we need KokkosKernels implementation for ```trsm``` as well or just TPL interfaces?

**Comment by iyamazaki** [comment]
I think just TPL would be enough for now.

**Comment by vqd8a** [comment]
@iyamazaki @srajama1 Thanks. I will work on it asap.

**Comment by iyamazaki** [comment]
Thank you!!

**Comment by srajama1** [comment]
@vqd8a  Thanks a lot ! I appreciate the help.

**Comment by vqd8a** [comment]
@iyamazaki @srajama1 I just pushed the PR for this.

**Comment by ndellingwood** [comment]
Cross-reference PR #532
