### ISSUE TITLE
CMake build system does not work properly on CUDA platforms

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#517]
@ndellingwood 
I am just using this issue to track a couple of changes that need to happen in the CMake build system of Kokkos-Kernels for my build to work on white:

1. the tests of Kokkos are enabled by default which make building kokkos-kernels much slower
   proposed fix: add a variable called `KOKKOS_DO_TESTS` and set it to off by default, also add logic to allow users to turn it on explicitly from the command line
```
 KOKKOS_DO_EXAMPLES=OFF
 KOKKOS_DO_TESTS=OFF
 KOKKOS_MAKEINSTALL_J=4

    --no-tests)
      KOKKOS_DO_TESTS=OFF
      ;;

echo cmake ... -DKokkos_ENABLE_TESTS=${KOKKOS_DO_TESTS} ...
cmake ... -DKokkos_ENABLE_TESTS=${KOKKOS_DO_TESTS}
```
Also the above code follows the logic used to turn on/off the compilation of tests in kokkos, but there seems to be no way to turn on the examples explicitly (at all?) since the default value if `OFF` and the command line option only allows you to turn it off...

2. there are typos in `CMakeList.txt` on line 135 and 138 (extra "}" after variable names), it currently reads:
```
  IF(KOKKOSKERNELS_INST_EXECSPACE_CUDA} AND KOKKOSKERNELS_INST_MEMSPACE_CUDASPACE})
    LIST(APPEND DEVICE_LIST "<Cuda,CudaSpace>")
  ENDIF()
  IF(KOKKOSKERNELS_INST_EXECSPACE_CUDA} AND KOKKOSKERNELS_INST_MEMSPACE_CUDAUVMSPACE})
    LIST(APPEND DEVICE_LIST "<Cuda,CudaUVMSpace>")
ENDIF()
```
but should be
```
  IF(KOKKOSKERNELS_INST_EXECSPACE_CUDA AND KOKKOSKERNELS_INST_MEMSPACE_CUDASPACE)
    LIST(APPEND DEVICE_LIST "<Cuda,CudaSpace>")
  ENDIF()
  IF(KOKKOSKERNELS_INST_EXECSPACE_CUDA AND KOKKOSKERNELS_INST_MEMSPACE_CUDAUVMSPACE)
    LIST(APPEND DEVICE_LIST "<Cuda,CudaUVMSpace>")
ENDIF()
```

**Comment by ndellingwood** [comment]
Adding a couple more items from conversations with @lucbv 

3. --with-cuda=* should not break when an explicit path for CUDA_ROOT is provided

4. Parse --cxxflags input with space separators

**Comment by ndellingwood** [comment]
See PR #519

**Comment by lucbv** [comment]
Thanks @ndellingwood this solves my issues : )
