### ISSUE TITLE
Expose graph clustering, RCM, BFS as first-class KokkosGraph features

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#523]
See #475 

These three graph algorithms are only used by cluster Gauss-Seidel now, but would be useful for outside users. Move them to src/graph and make them first-class features of KokkosGraph.

- [ ] ETI (hpp/spec/impl files for each thing)
- [ ] Wiki documentation
- [ ] Standalone unit testing

**Comment by srajama1** [comment]
@seheracer has some ideas about BFS ... please coordinate. She had suggestions for RCM as well. If a better RCM helps apps they will be very interested.

**Comment by brian-kelley** [comment]
I'm going to go ahead and close this now, we do have public interfaces for RCM and clustering/coarsening now. We haven't had a use case for BFS come up since this issue.
