### ISSUE TITLE
header files name changes impact on MueLu

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#53]
I noticed that the latest snapshot of kokkos in Trilinos included a large renaming of files which triggered some build errors in MueLu.
I talked with @mndevec and it seems that the integration test done before the snapshot push did not catch MueLu's dependencies on kokkos.
To have MueLu use Kokkos you need to add the following flags in your configure script:
```
-D MueLu_ENABLE_Experimental=ON \
-D MueLu_ENABLE_Kokkos_Refactor=ON \
-D Xpetra_ENABLE_Experimental=ON \
-D Xpetra_ENABLE_Kokkos_Refactor=ON \
```

as far as I can tell we have only issues with the renaming of ```Kokkos_CrsMatrix.hpp``` into ```KokkosSparse_CrsMatrix.hpp```
@jhux2 @tawiesn @csiefer2 do you have any comments/additions to make

**Comment by mhoemmen** [comment]
@crtrott recently pushed a big batch of changes to kokkos-kernels to improve interfaces.  He tested everything downstream, but may not have realized the large number of experimental build options that are OFF by default.

**Comment by mndevec** [comment]
We did not see KokkosKernels in Dependencies.cmake of MueLu. We were compiling MeuLu for Stokhos, unfortunately without the experimental flags. 

Packages in trilinos that have direct dependency to KokkosKernels are below:
 tpetra
 ifpack2
 stokhos
 trilinoscouplings
 minitensor
 xpetra
As well as MueLu with the flags above. 

We should keep this list somewhere, like wiki again, with the required options.

**Comment by srajama1** [comment]
Ugh .. I knew about the experimental flag and I knew about the name changes, but didn't put them together.  I missed warning the team. Sorry ! Can you change file name as it is experimental code ? We changed the naming convention for sparse, graph, dense etc to be more uniform. 

BTW, It might not be a bad idea to directly add Kokkoskernels to the dependencies list if you are directly including files.

**Comment by lucbv** [comment]
Yes I am looking into updating our code to support the new naming scheme.
This should not be too long I think.

**Comment by crtrott** [comment]
Just to clarify, MueLu and Xpetra were on for all integration testing. Just the extra flags were not on. We manually went through all packages which had an explicit dependency on KokkosKernels in the dependencies.cmake to look for classes coming from KokkosKernels. We didn't do that for everything since the namespace previously overlapped with Kokkos and the class names overlap with all kinds of stuff in Trilinos, and thus there were tons of falls alarms.

**Comment by crtrott** [comment]
Also if anybody else knows of any flags which need setting: both KokkosKernels and Kokkos use the script inside of Trilinos/sampleScripts/Sandia-SEMS/configure-testbeds-jenkins-all as the main integration testing vehicle (in addition to running Trilinos check-in-test script. 
So everything you want getting tested can simply go in there.

**Comment by crtrott** [comment]
Also if anybody else knows of any flags which need setting: both KokkosKernels and Kokkos use the script inside of Trilinos/sampleScripts/Sandia-SEMS/configure-testbeds-jenkins-all as the main integration testing vehicle (in addition to running Trilinos check-in-test script. 
So everything you want getting tested can simply go in there.

**Comment by crtrott** [comment]
I added the experimental settings to the integration test script.

**Comment by lucbv** [comment]
I have pushed bd41966 which should take care of the namespace and header renaming.
