### ISSUE TITLE
kokkos-dev-2 CUDA modules leading to cm_test_all errors

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos-kernels#534]
The cuda/10.1 module is missing `cublas` libraries. Additionally, even working around the missing libraries, it reports device version `0.0` causing all tests to fail. The cuda/10.0 module works as does the sems-cuda/10.1.

**Comment by ndellingwood** [comment]
@jjwilke I'll mark this as bug due to the cm_test_all_sandia script using a module without proper TPL support
