### ISSUE TITLE
gemv transpose mode issues with cublas and M == 0

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#539]
Recent updates with added testing for `gemv` (see #514) added a testing condition that appears to be unsupported by cublas in Transpose mode when `M == 0` [(see comments in the documentation)](https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-gemv).

As a first pass I'm going to guard the test to prevent the failure with TPLs not supporting this case.

The kokkos-kernels fall-back implementation supports this (returning `beta*y` if `beta != 0; returns `y` if `beta == 0`). If this is generally expected behavior of users we'll need to "short-circuit" the TPL macros to handle this case.

Adding @iyamazaki  @srajama1 @mhoemmen for feedback on what expected behavior for this case should be, so TPL macros can be updated if necessary.

**Comment by ndellingwood** [comment]
Detected testing with the following:

Machine - kokkos-dev-2

kokkos develop branch SHA kokkos/kokkos@0378c0fa18fd366a6fe5e94b04b11e8e46836df3

kokkos-kernels develop branch SHA 5d5d07ccc0b16f097542f714870d1dd50451c571

Configuration:
```
module load sems-cuda/10.1 sems-gcc/7.3.0 sems-cmake/3.12.2

../../cm_generate_makefile.bash --kokkos-path=${HOME}/kokkos --compiler=${HOME}/kokkos/bin/nvcc_wrapper --with-cuda --arch=Volta70 --with-tpls=cublas --kokkos-make-j=12
```

**Comment by ndellingwood** [comment]
PR disabling the M==0 test with TPLs in #540

**Comment by mhoemmen** [comment]
@ndellingwood wrote:
> added a testing condition that appears to be unsupported by cublas in Transpose mode when `M == 0`....

Do you mean the condition on `x`, that it have at least `(1+(m-1)*abs(incx))` elements if `transa != CUBLAS_OP_N`?  That should only be a problem if `incx != 1`.  cuBLAS seems to have inherited this condition from [the Reference BLAS](http://www.netlib.org/lapack/explore-html/d7/d15/group__double__blas__level2_gadd421a107a488d524859b4a64c1901a9.html).

CUDA needs to be able to handle this case.  I would rather that we fix kokkos-kernels, not that we hide this bug by disabling the test.

**Comment by ndellingwood** [comment]
I just tried reproducing this with the develop branch and not seeing the failure, will test again tomorrow to check if in case I made some mistake, been juggling multiple PRs for a few days so it's possible...

**Comment by ndellingwood** [comment]
Reproduced during integration testing on Waterman, in that case the serial test failed with large diffs:

```
74: [ RUN      ] serial.gemv_double
174: /ascldap/users/ndellin/trilinos/Trilinos/kokkos-kernels/unit_test/../test_common/KokkosKernels_TestUtils.hpp:87: Failure
174: The difference between double(AT1::abs(val1)) and double(AT2::abs(val2)) is 848328.00593907409, which exceeds double(AT3::abs(tol)), where
174: double(AT1::abs(val1)) evaluates to 35347.00024746135,
174: double(AT2::abs(val2)) evaluates to 883675.00618653547, and
174: double(AT3::abs(tol)) evaluates to 0.088367500618653547.
174: /ascldap/users/ndellin/trilinos/Trilinos/kokkos-kernels/unit_test/../test_common/KokkosKernels_TestUtils.hpp:87: Failure
174: The difference between double(AT1::abs(val1)) and double(AT2::abs(val2)) is 848328.00593907409, which exceeds double(AT3::abs(tol)), where
174: double(AT1::abs(val1)) evaluates to 35347.00024746135,
174: double(AT2::abs(val2)) evaluates to 883675.00618653547, and
174: double(AT3::abs(tol)) evaluates to 0.088367500618653547.
174: /ascldap/users/ndellin/trilinos/Trilinos/kokkos-kernels/unit_test/../test_common/KokkosKernels_TestUtils.hpp:87: Failure
174: The difference between double(AT1::abs(val1)) and double(AT2::abs(val2)) is 848328.00593907409, which exceeds double(AT3::abs(tol)), where
174: double(AT1::abs(val1)) evaluates to 35347.00024746135,
174: double(AT2::abs(val2)) evaluates to 883675.00618653547, and
174: double(AT3::abs(tol)) evaluates to 0.088367500618653547.
174: [  FAILED  ] serial.gemv_double (22 ms)
```

**Comment by ndellingwood** [comment]
PR #551 issued with fix to call fallback impl for this failing case. The failing test posted above is now passing with the change.
