### ISSUE TITLE
CUDA 10, GCC 7.4.0 internal error in GEMM impl

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#543]
On a build with GCC 7.4.0 and CUDA 10.1, I get an internal compiler error in gemm_impl.hpp:
```
...src/impl/generated_specializations_cpp/gemm/KokkosBlas3_gemm_eti_spec_inst_dbl_LayoutLeft_Serial_HostSpace.cpp:55:17:   required from here
.../src/blas/impl/KokkosBlas3_gemm_impl.hpp:109:61: internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c:1739
           A_scr(i,j) = idx_i<A.extent_int(0) && idx_j<A.extent_int(1) ? A(idx_i,idx_j) : ATV::zero();
```
I've tried to work around it by making trivial syntax changes but that didn't make a difference. If I break up this statement into several small operations, the real issue is in the ``idx_j<A.extent_int(1)`` part (the ternary operator is OK).

**Comment by ndellingwood** [comment]
@brian-kelley this has been a weird issue popping up in some gcc compilers but not others, could you try removing the `const` from the `idx_j` creation and assignment lines (line 106, but other places)?

**Comment by ndellingwood** [comment]
There is a PR that may fix this but I was nervous to merge because this issue comes up inconsistently with some gcc versions, and changing the cxx standard adds complications as well.

**Comment by mhoemmen** [comment]
I think we've had issues like this before, where changing inner lambda capture from `&` to `=` or removing `const` from indices helps.

**Comment by brian-kelley** [comment]
@ndellingwood @mhoemmen Yes, removing const from the outer idx (i or j) seems to be fixing it. I added this to #544.
