### ISSUE TITLE
Add SuperLU as optional CMake TPL

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos-kernels#545]
Add the necessary CMake options to enable SuperLU.  This is tricky....

* SuperLU might be installed as static or shared library
* If static, SuperLU might or might not contain BLAS symbols
* If containing BLAS symbols, they might be from an external BLAS or they might be wrapper functions implemented directly in SuperLU

Not clear how much error checking and validation we want to engineer into the CMake. It's very easy to add a basic TPL that just finds `libsuperlu` and adds the include path. It will be very difficult to figure out exactly how SuperLU was installed and generate good diagnostic messages.

**Comment by jjwilke** [comment]
My recommendation is to just do a simple TPL find.  We could potentially also add a `try_compile` that builds a simple test program. If the test program fails, rather than generating an exact diagonstic, we just list all the possible reasons it could have failed.

**Comment by jjwilke** [comment]
@ndellingwood

**Comment by ndellingwood** [comment]
@jjwilke I like your recommendation; the need for SuperLU in this case is for a specialization of sptrsv but will not be important to the rest of kokkos-kernels.
