### ISSUE TITLE
trsm_complex_double fails under OpenMP and Serial, on Intel 18 only

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#559]
I ran spot checks on Bowman with double and complex_double enabled as scalars. On intel 16 and 17, everything passes. But on intel 18, complex trsm fails. Probably a compiler bug...

```
[ RUN      ] openmp.trsm_complex_double
/ascldap/users/bmkelle/FixSortingTest/kokkos-kernels/unit_test/blas/Test_Blas3_trsm.hpp:187: Failure
Value of: true
Expected: test_flag
Which is: false
/ascldap/users/bmkelle/FixSortingTest/kokkos-kernels/unit_test/blas/Test_Blas3_trsm.hpp:187: Failure
Value of: true
Expected: test_flag
Which is: false
/ascldap/users/bmkelle/FixSortingTest/kokkos-kernels/unit_test/blas/Test_Blas3_trsm.hpp:187: Failure
Value of: true
Expected: test_flag
Which is: false
/ascldap/users/bmkelle/FixSortingTest/kokkos-kernels/unit_test/blas/Test_Blas3_trsm.hpp:187: Failure
Value of: true
Expected: test_flag
Which is: false
/ascldap/users/bmkelle/FixSortingTest/kokkos-kernels/unit_test/blas/Test_Blas3_trsm.hpp:187: Failure
Value of: true
Expected: test_flag
Which is: false
/ascldap/users/bmkelle/FixSortingTest/kokkos-kernels/unit_test/blas/Test_Blas3_trsm.hpp:187: Failure
Value of: true
Expected: test_flag
Which is: false
```

**Comment by crtrott** [comment]
Before you blame a compiler bug test this with Intel 19 (for example on Blake compiling for Skylake (SKX)). It might be that it is doing an optimization now which exposes a code bug.

**Comment by vqd8a** [comment]
I just want to say I have run double complex TRSM tests on Blake with different Intel compilers. The tests passed on Intel 17 and Intel 19 but failed on Intel 18 as @brian-kelley saw on Bowman. I think it is possibly an Intel 18 compiler bug.

| Compilers | using MKL    | Fallback implementation    |
|-------------|------------|------------|
|intel 17.4.196       | passed      | passed     |
|intel 18.0.128       | passed      | **failed**       |
|intel 18.1.163      | passed      | **failed**        |
|intel 19.1.144      | passed      | passed      |
|intel 19.3.199      | passed      | passed      |

**Comment by srajama1** [comment]
@ndellingwood Is it ok to update spot check to use Intel 19 ? Otherwise this will mess up every spot-check.

 @crtrott We probably need to bring it to the attention of Intel team.

**Comment by brian-kelley** [comment]
Closing since we dropped support for Intel 18 in 4.0.
