### ISSUE TITLE
KokkosBlas::dot: Poor accuracy with float on Mac Clang causes Trilinos test failure

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos-kernels#574]
See https://github.com/trilinos/Trilinos/issues/6633.

**Comment by ndellingwood** [comment]
@mhoemmen would you submit a PR with your fix from the Trilinos PR?

**Comment by ndellingwood** [comment]
If so I can test and will cherry-pick into the release candidate.

**Comment by mhoemmen** [comment]
@ndellingwood https://github.com/kokkos/kokkos-kernels/pull/575 :-)

**Comment by mhoemmen** [comment]
@ndellingwood I just fixed the base branch in that PR, btw.

**Comment by mhoemmen** [comment]
@ndellingwood FYI I had forgotten to test a change for complex.  I will fix it.

**Comment by mhoemmen** [comment]
@ndellingwood I fixed it :-)

**Comment by ndellingwood** [comment]
PR #575 merged, will be included in 3.0 release.
