### ISSUE TITLE
Spot checking with CUDA 10.1 on White/RIDE

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#576]
White and RIDE support CUDA 10.1 now. Could I add that as one of the spot-check configurations? This way, all CUDA graph stuff (which I expect will be more than just Gauss-Seidel soon) will get tested in every PR.

@ndellingwood @kyungjoo-kim

**Comment by ndellingwood** [comment]
Yes, and please modify the xl spot check to only test Serial on white/ride.

**Comment by ndellingwood** [comment]
I'll have a PR up soon to add tpl support, started working on it then got pulled into other things before finalizing.
