### ISSUE TITLE
Jenkins Testing

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-kernels#58]
The following are the environment variables set and arguments used for test_all_sandia to run the jenkins jobs:

Apollo:
  * clang/4.0.0 --build-list=Pthreads

Bowman:
```
export OMP_NUM_THREADS=256
export OMP_PROC_BIND=close
export OMP_PLACES=threads
```
  * intel/17.0.098 --build-list=OpenMP
  * intel/17.0.098 --build-list=Serial
 
White:
```
export OMP_NUM_THREADS=64
export OMP_PROC_BIND=close
export OMP_PLACES=threads
```
  * cuda/8.0.44 --build-list=OpenMP_Cuda
  * gcc/5.4.0 --build-list=OpenMP

**Comment by kyungjoo-kim** [comment]
where can I find the testing script (including all modules and compilers that are identical to jenkins) you mentioned ?

**Comment by mndevec** [comment]
Moved to wiki. 
https://github.com/kokkos/kokkos-kernels/wiki/Jenkins-Testing-Parameters
