### ISSUE TITLE
Remove all references to Kokkos::Impl::is_same

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos-kernels#586]
This has been removed in Kokkos develop - so we have now have incompatible Kokkos and Kokkos-Kernels develop branches.

**Comment by srajama1** [comment]
@crtrott Can the Kokkos team check Kokkos Kernels develop for any incompatibilities, please ?

**Comment by crtrott** [comment]
It is an impl function which was only needed prior to requiring C++11 i.e. prior to existence of KokkosKernels - we didn't expect anyone to actually use that ...

**Comment by ndellingwood** [comment]
This is showing up in the nightlies that I switched over to using the `cm_test_all_sandia` script building against kokkos' develop branch.

**Comment by ndellingwood** [comment]
```
kokkos-kernels/src/sparse/KokkosSparse_gauss_seidel_handle.hpp (581),(586)
kokkos-kernels/src/graph/KokkosGraph_Distance1ColorHandle.hpp(502)
kokkos-kernels/src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp(741)
```

Should be quick fix, I'm debugging some other stuff right now though

**Comment by ndellingwood** [comment]
The occurrences above were the only ones poked at by the nightly test, many more files.

`find . -type f -name "*.hpp" -print0 | xargs -0 sed -i  "s/Kokkos\:\:Impl\:\:is_same/std\:\:is_same/g"

**Comment by ndellingwood** [comment]
PR #592

**Comment by ndellingwood** [comment]
PR #592 merged to develop with fix.
