### ISSUE TITLE
PortableNumericCHASH can't align shared memory 

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-kernels#587]
This makes the PR for Kokkos/KokkosKernels Integration fail right now. 

https://testing.sandia.gov/cdash/testDetails.php?test=100331563&build=6287299

This fails here: 
KokkosSparse_spgemm_impl_kkmem.hpp:204

**Comment by ndellingwood** [comment]
@crtrott yes, that was added after dealing with the shmem alignment issues. the requested shmem from the handle probably needs to be adjusted.

**Comment by ndellingwood** [comment]
Original issue #500

**Comment by ndellingwood** [comment]
Have a better handle on this, issues are occurring when dealing ensemble-like types. 

Reverting this changes from #500 to determine `thread_memory` during construction necessary to address issue. Will put in a PR to the release-candidate-3.0 branch once fixes are confirmed.

**Comment by ndellingwood** [comment]
Addressed by PRs #588 and #591
