### ISSUE TITLE
Update Sptrsv to use KokkosBLAS

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos-kernels#590]
Related to #589.

**Comment by ndellingwood** [comment]
@e10harvey @iyamazaki I think this went in as part of PR #680, can I mark this in develop?

**Comment by iyamazaki** [comment]
Hi, @ndellingwood .  We have integrated [PR#622](https://github.com/kokkos/kokkos-kernels/pull/622) into Sptrsv, but not [PR#697](https://github.com/kokkos/kokkos-kernels/pull/697), yet..

**Comment by e10harvey** [comment]
> @e10harvey @iyamazaki I think this went in as part of PR #680, can I mark this in develop?

Yes.
