### ISSUE TITLE
Question: CMake warning for standard TriBITS/Trilinos TPL integration?

### ISSUE THREAD

**Issue by bartlettroscoe** [kokkos/kokkos-kernels#595]
It would seems the since the Kokkos and KokkosKernels 2.99 upgrade, the KokkosKernels configure now generates CMake Warnings that show up on CDash:

```
CMake Warning at packages/kokkos-kernels/cmake/kokkoskernels_tpls.cmake:10 (MESSAGE):
  Overriding KOKKOSKERNELS_ENABLE_TPL_BLAS=OFF with TPL_ENABLE_BLAS=ON
Call Stack (most recent call first):
  packages/kokkos-kernels/cmake/kokkoskernels_tpls.cmake:383 (KOKKOSKERNELS_ADD_TPL_OPTION)
  packages/kokkos-kernels/CMakeLists.txt:375 (INCLUDE)


CMake Warning at packages/kokkos-kernels/cmake/kokkoskernels_tpls.cmake:10 (MESSAGE):
  Overriding KOKKOSKERNELS_ENABLE_TPL_LAPACK=OFF with TPL_ENABLE_LAPACK=ON
Call Stack (most recent call first):
  packages/kokkos-kernels/cmake/kokkoskernels_tpls.cmake:385 (KOKKOSKERNELS_ADD_TPL_OPTION)
  packages/kokkos-kernels/CMakeLists.txt:375 (INCLUDE)
```

like you can see here:

* https://testing-dev.sandia.gov/cdash/viewConfigure.php?buildid=5215671

Since these vars are set by TriBITS automatically, I don't see how this can be resolved.

Can KokkosKernels please changes these from a CMake Warning to a "NOTE"?

**Comment by bartlettroscoe** [comment]
@jjwilke

**Comment by jjwilke** [comment]
Are there real consequences for testing if we have the warnings? We want to pretty forcefully encourage build scripts to be updated.
