### ISSUE TITLE
complex_double misalignment still breaking SPGEMM

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#598]
Memory alignment problems are still causing test failures for SGPEMM on CUDA: 
```
[ RUN      ] cuda.sparse_spgemm_kokkos_complex_double_int_int_TestExecSpace
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaFuncGetAttributes( &attr, cuda_parallel_launch_local_memory<DriverType>) error( cudaErrorMisalignedAddress): misaligned address /home/bmkelle/FixMultZeroRow-testing-1580941058/build/kokkos-install/include/Cuda/Kokkos_Cuda_KernelLaunch.hpp:439
Traceback functionality not available

Aborted
```

The above was from RIDE with GCC 7.2.0, CUDA 10.1, configured with:
```
../kokkos-kernels/cm_generate_makefile.bash --with-cuda --with-scalars=double,complex_double --compiler=/ascldap/users/bmkelle/FixMultZeroRow-testing-1580941058/kokkos/bin/nvcc_wrapper --debug --arch=Power8,Kepler37
```
But this affects release builds and CUDA 9.2 as well.

**Comment by brian-kelley** [comment]
Note: replacing ``alignof(scalar_type)`` with ``sizeof(scalar_type)`` doesn't fix this.

**Comment by mhoemmen** [comment]
Does the test code create an array of `std::complex<double>` and `reinterpret_cast` it to `Kokkos::complex<double>`?

**Comment by brian-kelley** [comment]
@mhoemmen @ndellingwood and I think it's still in the shared memory logic (so we think no). This takes a raw pointer and breaks it into pieces by casting this pointer to different types and then incrementing it, so if that's wrong anywhere it would explain the problem.

**Comment by brian-kelley** [comment]
Found it:
```
#define CHECKALIGN(ptr) \
  if((size_t) (ptr) % alignof(*(ptr))) \
  printf("Alignment of %s wrong (%s:%d)!\n", #ptr, __FILE__, __LINE__);

....
Alignment of vals wrong (/ascldap/users/bmkelle/KK_FixComplexAlignment/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp:610)!
```

**Comment by ndellingwood** [comment]
> Found it:

@brian-kelley nice! The same issue is probably happening with the memory pool as was with the shmem where the heuristic that determines chunk sizes and number of chunks does not check for alignment

**Comment by ndellingwood** [comment]
https://github.com/kokkos/kokkos-kernels/blob/6d0becda14a6248e88026e8eedaa4a18e7396ee4/src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp#L1488-L1546

**Comment by brian-kelley** [comment]
@ndellingwood Good idea, I'll make sure the level-2 hashmap values are aligned too.

The way I was going about fixing this was to just compute an aligned ``scalar_t*`` on-device, rather than adjusting the different table size heuristics ahead of time so that the alignment adds up to exactly the right value. I think the first way is less fragile. There just needs to be a few spare bytes of shared so that there's room to do the alignment. What do you think?

**Comment by brian-kelley** [comment]
Fixed in KK, and I just posted a Trilinos PR.
