### ISSUE TITLE
TPL support for SpMV

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#614]
I am adding TPL support in SpMV, the main goal is to enable the use of cuSPARSE spmv functionalities but other TPLs such as MKL could be explored too?

So my plan is to proceed as follows:

- [x] Provide a first cut implementation that allows for SpMV using CUDA 10 and a subset of all possible type combinations. This will not be as general as we want but it will allow us to work out the kinks and will provide a first capability that can be tested.
- [x] Provide more generic available for multiple versions of cuda and hopefully all types
- [x] Add a macro similar to Kokkos' CUDA_SAFE_CALL for cusparse to help clean the code a bit
- [x] Implement logic to apply transpose operator to input matrix if needed
- [ ] Add utility functions to create cusparse `CrsMatrix` and `DenseVector` from kokkos-kernels objects
- [ ] Do some performance benchmarking and monitor the cost of the cusparse handle creation
- [ ] Update documentation as appropriate to mention then new possible algorithmic path

**Comment by mhoemmen** [comment]
@lucbv Note that cuSPARSE uses `int` as the row offset type (type of the entries of `ptr`), while Tpetra uses whatever Kokkos says is the size type.  (The difference wasn't my idea -- Mike Heroux insisted on 64-bit row offsets.)  This means you'll either need to make a copy of `ptr` (use `Tpetra::Details::copyOffsets`, which can do bounds checking), or change Tpetra's storage format.

**Comment by mhoemmen** [comment]
@lucbv If you want to make a copy of `ptr`, you could either store that in one of those kokkos-kernels "handle" things, or store it in Tpetra.  Either way, it could make sense to use (and maybe extend) the existing `Tpetra::{LocalOperator, LocalCrsMatrixOperator}` class hierarchy.  The point of `LocalCrsMatrixOperator` was to reduce build times and sizes by hiding the actual sparse mat-vec call from `Tpetra::CrsMatrix` compilation units, but it's also a point at which you know the structure of the local matrix.  It could be a place to store things like handles or copies of data structures.

**Comment by mhoemmen** [comment]
@lucbv For an example of how to hide TPL header files from downstream code, see `CuSolverHandle` and `CuSolver` in `packages/tpetra/tsqr/src`.

**Comment by lucbv** [comment]
@mhoemmen things might be a bit more complicated depending on the CUDA version being used. I think that under CUDA 10 you can specify the type of rowPtr but it has to be the same as the type of colInd... Here is the API documentation for [CUSPARSE 10 CrsMAtrix](https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-spmat-ref) in any case I am not planning on addressing everything from Kokkos-kernels to Tpetra right away, I want to make small incremental progress to make sure things actually get merged! I have been too ambitious in the past and do not want PRs that last months anymore : )

**Comment by mhoemmen** [comment]
@lucbv Are you planning to plug in cuSPARSE sparse mat-vec to compare with the existing kokkos-kernels sparse mat-vec, or do you plan to pull in other functions that don't have good support in kokkos-kernels yet?

**Comment by lucbv** [comment]
I want to do the latter, although by I only intend to do SpMV so far but if there is a need for other functionalities we can look at it in a second time.
I am sure that we have a Kokkos-kernels list of todos : )

**Comment by lucbv** [comment]
Modifying the first comment to reflect work done and upcoming work to make the code cleaner and developer friendly.

**Comment by mhoemmen** [comment]
@lucbv Thanks for the conversation earlier this week!  I'd like @vbrunini to know about this work.  My conclusion about our conversation is that even if kokkos-kernels wraps cuSPARSE, Tpetra would still need to manage auxiliary data structures, like a copy of the row offsets array with the right type, or the handle itself.

**Comment by lucbv** [comment]
Updating the list of to-do above to include @srajama1 comments on performance monitoring and specifically evaluating the cost of handle creation, which could actually be tested on its own in a performance test?

**Comment by lucbv** [comment]
OK, the transpose mode and `KOKKOS_CUSPARSE_SAFE_CALL` have been implemented and merged with PR #643 next step will probably involve some testing and documentation updating.
@srajama1 @ndellingwood do I need to submit the documentation I will write for R&A or do we consider it a simple update not worthy of official check?

**Comment by ndellingwood** [comment]
@lucbv If the documentation results in a new wiki page or significant changes it should go through R&A (make sure to update the private wiki and I can put in the request), if it is minor updates to an existing page than that should be able to go directly to the public wiki.

**Comment by ndellingwood** [comment]
@lucbv can this be marked as InDevelop since CuSparse support was added for SPMV (and the merge based algorithm can be considered as an enhancement)?

**Comment by lucbv** [comment]
Yes that would make sense, I am doing that right now.
