### ISSUE TITLE
Error in directions at https://github.com/kokkos/kokkos-kernels/wiki/Using

### ISSUE THREAD

**Issue by kuberry** [kokkos/kokkos-kernels#621]
On the "Using" page, there is a code block:

```
cmake_minimum_required(VERSION 3.13)
project(myMath CXX)

add_subdirectory(kokkos)
add_subdirectory(kokkos-kernels)

add_library(myMathLib <LIST_OF_SOURCE_FILES>)
target_link_libraries(myMathLib Kokkos::kokkoskernels)
```

This results in errors like:
```
CMake Error at examples/CMakeLists.txt:14 (add_executable):
  Target "NeighborSearchTest" links to target "Kokkos::kokkoskernels" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:43 (add_exe_w_compadre)
```

Changing the last line to:
```
target_link_libraries(myMathLib kokkos-kernels)
```
results in:
```
ld: library not found for -lkokkos-kernels
```

Changing the last line to:
```
target_link_libraries(myMathLib kokkoskernels)
```
results in an error (but CMake still configures):
```
CMake Error: install(EXPORT "compadre-target" ...) includes target "compadre" which requires target "kokkoskernels" that is not in the export set.
```
Using the last line, I can build and link, but I'm unsure whether it works once installed.

**Comment by srajama1** [comment]
@jjwilke

**Comment by jjwilke** [comment]
You are missing the `find_package(KokkosKernels REQUIRED)` that find and imports the target.

**Comment by kuberry** [comment]
Hi @jjwilke , 

find_package(KokkosKernels REQUIRED) fails to find the package (it isn't installed, just added using add_subdirectory(), so there is no KokkosKernelsConfig.cmake in the source or build directories)

Changing the last line to:
```
target_link_libraries(myMathLib kokkoskernels)
```
works, but it still needs its target "kokkoskernels" exported to the final target (in my case, compadre-target was the target complaining), so I resolved this with:
```
      install( TARGETS kokkoskernels EXPORT compadre-target DESTINATION lib)
      install( TARGETS LAPACK EXPORT compadre-target DESTINATION lib)
      install( TARGETS BLAS EXPORT compadre-target DESTINATION lib)
```
but then I need to do this for each target that kokkoskernels relies on.

**Comment by kuberry** [comment]
Just a few more details, on line 10 of kokkos-kernels/cmake/kokkoskernels_tribits.cmake, there is a check ELSEIF(NOT KOKKOSKERNELS_HAS_PARENT) (which is false when using add_subdirectory(kokkos-kernels), so KokkosKernelsConfig.cmake and all of the other .cmake files are never created.

find_package(KokkosKernels) won't have any chance of succeeding without these files being created.

**Comment by kuberry** [comment]
PR #626 addresses the changes that are needed for CMake, along with a description of each change, in order to produce the needed files / variables to build, install, and then build/link against the final installed project and have Kokkos Kernels work correctly.

**Comment by ndellingwood** [comment]
@kuberry I think all the PRs related the issue have been merged into develop, I'm going to mark this "InDevelop", if any more outstanding issues need addressing please comment.
