### ISSUE TITLE
supernodal does not build with UVM enabled

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos-kernels#633]
If Kokkos is built with UVM enabled, the supernodal build fails with several static asserts about invalid conversions, e.g.

````
static assertion failed with "View assignment must have compatible spaces"
src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp(2586)
  Kokkos::View<scalar_t*, memory_space> work = thandle.get_workspace ();
````

This does not occur on Cuda builds without UVM or OpenMP builds.

**Comment by ndellingwood** [comment]
Does replacing 
`Kokkos::View<scalar_t*, memory_space> work = thandle.get_workspace ();`
with
`auto work = thandle.get_workspace ();`
fix this?

**Comment by jjwilke** [comment]
No, I started to get more conversion errors in other places and gave up : )

**Comment by ndellingwood** [comment]
@iyamazaki was this fixed with your updates in PR #675 or #676? I think you had addressed this but I lost track of which PR.

**Comment by iyamazaki** [comment]
Hi, @nellingwood. No, it has not. But, I am working with @e10harvey to integrate the KK interface for TRMM and TRTRI, and that PR should fix this.

**Comment by ndellingwood** [comment]
Thanks @iyamazaki ! Wasn't trying to rush you, I mistakenly thought this was part of a different PR.

**Comment by ndellingwood** [comment]
Marked as In Develop based on merge of #680, thanks @iyamazaki !
