### ISSUE TITLE
graph_color_d2_symmetric_double_int_int_TestExecSpace seg faults in cuda/10.1 + Volta nightly test on kokkos-dev-2

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#634]
The following test began seg faulting in the nightly cuda/10.1 test on kokkos-dev-2 (Volta70 arch), this did not occur in the UVM build:

```
02:44:31 3: [ RUN      ] cuda.graph_graph_color_d2_symmetric_double_int_int_TestExecSpace
02:44:31 3/8 Test #3: graph_cuda .......................***Exception: SegFault  3.52 sec
```

@brian-kelley I'm guessing this is related to the changes from PR #623?

Reproducer:

```
./kokkos-kernels/scripts/cm_test_all_sandia cuda/10.1 --build-list=Cuda_OpenMP
```

**Comment by ndellingwood** [comment]
Adding link to failing nightly build [output: ](https://jenkins-son.sandia.gov/view/KokkosKernels/job/KokkosKernels_KokkosDev2_CUDA10_1/390/console)

**Comment by brian-kelley** [comment]
@ndellingwood I was able to replicate a crash. It was actually in resolveConflictsSerial(), which runs on host, but I think cuda tends to generate more conflicts.

**Comment by brian-kelley** [comment]
This bug happens randomly when a raw malloc'd array happens to contain all zeros. The fix was just to initialize it.

**Comment by ndellingwood** [comment]
If you aren't able to sign in when clicking the link above you'll need to request through WebCARS, I'll send you an email.
