### ISSUE TITLE
Split Tests spgemm and gauss_seidel into multipl object files.

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-kernels#64]
XL 14 output during build. Yes we are looking at over 45mins compile time with 7 and 3 GB footprint respectively:
```
 27473 crtrott   20   0 7897280 7.436g  58560 R  84.0  1.5  44:58.57 /home/projects/pwr8-rhel73-lsf/ibm/xl/xlC/14.1.0/exe/ipa -comp -qalias=ansi -qthreaded -qtls -qtls -maltivec -qtls -qlanglvl=extended0x -qarch=pwr8 -qtune=pwr8 -qsmp=omp /tmp/xlcW0wbmEmP /tmp/xlcW13OIGeu Test_OpenMP_Sparse_spgemm.o /tmp/xlcLj2CORsT.lst /tmp/xlcW25m6I68                                                                                               
 27312 crtrott   20   0 3903744 3.159g  58624 R  80.0  0.6  45:19.68 /home/projects/pwr8-rhel73-lsf/ibm/xl/xlC/14.1.0/exe/ipa -comp -qalias=ansi -qthreaded -qtls -qtls -maltivec -qtls -qlanglvl=extended0x -qarch=pwr8 -qtune=pwr8 -qsmp=omp /tmp/xlcW02Rd4eQ /tmp/xlcW1XvNf7u Test_OpenMP_Sparse_gauss_seidel.o /tmp/xlcLOE0GKtT.lst /tmp/xlcW26HmrZ9  
```

**Comment by crtrott** [comment]
SPGEMM is closing on two hours:
```
27473 crtrott   20   0 8655616 5.390g  58560 R 100.0  1.1 112:59.11 /home/projects/pwr8-rhel73-lsf/ibm/xl/xlC/14.1.0/exe/ipa -comp -qalias=ansi -qthreaded -qtls -qtls -maltivec -qtls -qlanglvl=extended0x -qarch=pwr8 -qtune=pwr8 -qsmp=omp /tmp/xlcW0wbmEmP /tmp/xlcW13OIGeu Test_OpenMP_Sparse_spgemm.o /tmp/xlcLj2CORsT.lst /tmp/xlcW25m6I68 
```

gauss_seidel finished at some point after 85 mins.

**Comment by mndevec** [comment]
These are compilation times, not test times right?

What are the data types that are enabled?

**Comment by crtrott** [comment]
Just the default double , complex<double>

**Comment by crtrott** [comment]
It finished!! Took almost 5 hours.

**Comment by mhoemmen** [comment]
this makes baby Turing unhappy :(

**Comment by mndevec** [comment]
I finished the eti of spgemm and gauss seidel. 
Would this separation be still required? I mean, would separation speedup the linking of ETI'd kernels?

**Comment by mndevec** [comment]
I am closing this issue, as it looks like this does not have much effect once the kernels are ETI'ed. 

I separated the tests and compiled it for double and complex double. The overall compilation took 8 minutes. 
Without the split it was 7m 57 seconds. There can be noises for timings but apparently this does not have much affect on the compilation time.

**Comment by srajama1** [comment]
Are you saying XL compilation time went from 5 hrs to 8 mins before splitting SGS and SpGEMM tests ?

**Comment by mndevec** [comment]
No, 8 min is on my workstation. 

Basically, XL compiler issue is solved with ETI (5 hours to 15 min). I was experimenting whether splitting test files would further improve the compile time. I was trying this on my workstation with gcc compiler. Basically, once we the eti is done splitting do not have further improvement.
