### ISSUE TITLE
Some tests don't use Kokkos Kernels :)

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos-kernels#647]
Hey folks,

With a fairly standard build using CMake, I run into problems with the tests

```
./perf_test/sparse/sparse_spmv --test kk-kernels
```

Leads to errors that the `Selected test is not available.`

If I simply delete the `ifdef`'s surrounding `HAVE_KK_KERNELS` being defined (in the test and the header it includes) things compile fine. I think this is just a build problem, HAVE_KK_KERNELS isn't being set up as a preprocessor macro

**Comment by brian-kelley** [comment]
@DavidPoliakoff You'll have to use develop branch or wait for a release to use the spmv perf test, unfortunately. This issue was fixed (in develop) with PR #613.
