### ISSUE TITLE
cuSPARSE spmv wrapper doesn't actually use 'mode'

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#650]
This is kind of halfway between a bug and a feature request, but the cuSPARSE SPMV backend does not actually use the "const char mode[]" parameter. It always does the ``CUSPARSE_OPERATION_NON_TRANSPOSE``. We'll need to fix this fully support large-row SPMV in Tpetra (see https://github.com/trilinos/Trilinos/pull/6982).

**Comment by brian-kelley** [comment]
See ``src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp``.

**Comment by ndellingwood** [comment]
@lucbv will you have time to provide support for this before the next Trilinos release (The goal may be to start testing in a week or two)? If not, I'm guessing we will need to disable the cusparse spmv capability when Trilinos is enabled to avoid packages running into issues when calling spmv with transpose mode?

**Comment by lucbv** [comment]
@ndellingwood @brian-kelley 
I actually implemented that this morning in my branch for PR #643, I can push that now if you want, that PR also cleans the implementation and provides a nice utility function for cusparse support in kokkos-kernels and for external users.

**Comment by ndellingwood** [comment]
> I can push that now if you want

@lucbv not a rush so push when you feel it is ready to be updated into the PR, I just wanted to get a sense what the status might be over the next couple weeks before the next round of integration testing, thanks!

**Comment by lucbv** [comment]
@ndellingwood 
I just pushed my branch and you can see it in the related PR, I will ask a couple of questions regarding this work tomorrow at our meeting and will probably be able to finish the work before the end of the week

**Comment by lucbv** [comment]
OK, I think that #643 has taken care of this, I am marking this as fixed in develop.
