### ISSUE TITLE
Add CI for PR spot-checking?

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos-kernels#654]
We can improve developer workflow by automating PR spot-checking. Is there any interest in getting continuous integration set up for kokkos-kernels? @vqd8a, @jjwilke, @seheracer, @srajama1, @lucbv, @ndellingwood, @kyungjoo-kim, @crtrott.

**Comment by lucbv** [comment]
Yes please!

**Comment by vqd8a** [comment]
Yes please!!!

**Comment by ndellingwood** [comment]
Yes!
@e10harvey can this be done in a way to allow for external collaborators to issue PRs that are tested as well?

**Comment by e10harvey** [comment]
> @e10harvey can this be done in a way to allow for external collaborators to issue PRs that are tested as well?

I need to look into this further. This should be possible by using GitHub Actions.

**Comment by jjwilke** [comment]
You should chat with @dalg24  or @masterleinad about how we do this with Kokkos. For external users, we usually either require an approving review or I think they actually set it up so that someone can just comment "okay to test".

**Comment by ndellingwood** [comment]
> You should chat with @dalg24 or @masterleinad about how we do this with Kokkos

@jjwilke good suggestion, I think they have the CI set up on resources at ORNL that have different restrictions than Sandia, so there may be an extra layer of issues to get this setup on Sandia resources that was bypassed by using ORNL's.

**Comment by e10harvey** [comment]
This has been addressed and tested via https://github.com/kokkos/kokkos-kernels/pull/753. The CI will not be turned on until going through another round of review and approval.
