### ISSUE TITLE
cusparse SpMV merge algorithm

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#670]
@srajama1 @brian-kelley 
This is a request from @vbrunini, the goal is to allow users to chose the algorithm that cusparse uses for its SpMV kernels at runtime. This will improve performance of SpMV when a matrix has a lot of imbalance in terms of nnz per row (very long rows are not well handled by kk native algorithm).
This will require #669 to make some progress and probably some extra clean-up in the spmv_tpl interface.
Once this work is done interfacing will be required in Tpetra to make this available to users of Trilinos.

**Comment by ndellingwood** [comment]
@lucbv I added this to the 3.2 milestone since it seems the PR is nearly ready.

**Comment by ndellingwood** [comment]
Cross-reference PR #725 and issue #669, since #725 introduces a prototype for the new Control structure.

**Comment by lucbv** [comment]
@ndellingwood I am not sure if milestone 3.2 is appropriate.
We will probably get this snapshotted fairly quickly to enable the integration with Tpetra and then Sierra. I am not sure if that changes things for the 3.2 release?
