### ISSUE TITLE
Zero diagonals in diagonally dominant matrices generated

### ISSUE THREAD

**Issue by seheracer** [kokkos/kokkos-kernels#678]
**Link:**
Lines 179-183, **kk_generate_diagonally_dominant_sparse_matrix** function, 
https://github.com/kokkos/kokkos-kernels/blob/1be37e8aee0ddfee5ad5076f3a049c4c473f5665/src/common/KokkosKernels_IOUtils.hpp

**Related Code:**
```
  for(int row=0;row<nrows;row++)
  {
    int varianz = (1.0*rand()/RAND_MAX-0.5)*row_size_variance;
    rowPtr[row+1] = rowPtr[row] + elements_per_row+varianz;
  }
```

**Problem:** 
According to the last line of the above-given code, **kk_generate_diagonally_dominant_sparse_matrix** may create matrices with some diagonal entries being zero, because`elements_per_row+varianz` may be equal to 0, so, some rows may end up with all zero entries. 

Is this behavior acceptable?  

**Edit:** 
Also, the loop in https://github.com/kokkos/kokkos-kernels/blob/1be37e8aee0ddfee5ad5076f3a049c4c473f5665/src/common/KokkosKernels_IOUtils.hpp#L191 does not check if the newly-computed column index already exists in the current row.  We want to fix that, too, right?

**Comment by ndellingwood** [comment]
> Is this behavior acceptable?

@seheracer For non-strictly diagonally dominant matrices a row of 0's would allow for a 0 at the diagonal, I don't see any comments in the files you reference to determine if this was intentionally allowed to occur (I doubt it, I'm guessing there would be added options to intentionally generate such a matrix since this would test corner cases in algorithms).

**Comment by ndellingwood** [comment]
Based on meeting discussion sounds like the path forward is to modify the code to ensure diagonal entries are present, rather than adding structural zeros as place holders for rows-of-zeros.

**Comment by brian-kelley** [comment]
@ndellingwood I agree with this, GS tests use this and expect the diagonal values to be nonzero.

**Comment by seheracer** [comment]
Sounds good. I will push the PR today.
