### ISSUE TITLE
Clang 8.0 + CUDA reproducer modules not found (kokkos-dev2)

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#705]
@ndellingwood I was trying to rebuild to look into #704, but I get this when I try to reload modules:

```
[bmkelle@kokkos-dev-2 Cuda_OpenMP-release]$ cat reload_modules.sh 
  #   Load modules:
        module load sems-env sems-cmake/3.12.2 kokkos-env clang/8.0 cuda/10.0

[bmkelle@kokkos-dev-2 Cuda_OpenMP-release]$ source reload_modules.sh 
kokkos-env(20):ERROR:105: Unable to locate a modulefile for 'clang/8.0'
kokkos-env(20):ERROR:105: Unable to locate a modulefile for 'cuda/10.0'
```

If I load sems-env and kokkos-env, I can't find clang/8.0 in ``module avail``. Purging didn't help. This could be a machine problem but earlier today, cm_test_all_sandia was able to load it and complete a build.

**Comment by crtrott** [comment]
These modules are locally installed. You need to add something like module use /home/projects/modulefiles or whatever. Which machine?

**Comment by brian-kelley** [comment]
@crtrott Ah I found it, cm_test_all_sandia does ``module use /home/projects/x86-64/modulefiles/local``. Thanks!

@ndellingwood Could we add this to the reproducer script?

**Comment by brian-kelley** [comment]
@ndellingwood Actually I'll just take care of this
