### ISSUE TITLE
test failure on Kokkos-dev

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#724]
@ndellingwood @brian-kelley 
I am seeing the following errors during a spot-check on Kokkos-dev in the Cuda-clang build:
```
1: [ RUN      ] cuda.gemv_double
1: [       OK ] cuda.gemv_double (132 ms)
1: [ RUN      ] cuda.gemv_complex_double
1: terminate called after throwing an instance of 'std::runtime_error'
1:   what():  cudaFuncGetAttributes( &attr, cuda_parallel_launch_local_memory<DriverType>) error( cudaErrorMisalignedAddress): misaligned address /ascldap/users/lberge/kk_lucbv_build/spot_check/TestAll_2020-05\
-21_17.51.39/clang/7.0.1/Cuda_OpenMP-release/kokkos-install/include/Cuda/Kokkos_Cuda_KernelLaunch.hpp:440
1: Traceback functionality not available
```
it also happens in some sparse kernels, I can post the full test log if useful.
Is this a known issue or something that you might have seen before?

**Comment by lucbv** [comment]
Interestingly this does not happen with the Cuda-9.2/gcc-6.1.0 build.
Is there a chance that the alignment of complex is different with clang and gcc?

**Comment by ndellingwood** [comment]
Are you using an older Kokkos? Hopefully this is fixed if you update your Kokkos version to 3.1.1 and rebuild the library, some alignment issue Brian chased down and reported were recently resolved, though this could be separate (or introduced by the other changes).

**Comment by ndellingwood** [comment]
@lucbv also, the previous alignment issues @brian-kelley chased down occurred only with clang+cuda, not cuda+gcc, so hopefully you're kokkos repo is out of date and a pull of develop or the 3.1.1 tag resolves the issue.

**Comment by ndellingwood** [comment]
Cross-referencing #645, #704

**Comment by lucbv** [comment]
@ndellingwood it is quite possible that my kokkos repo on `kokkos-dev` is somewhat out-dated, I will do a pull there and let you know. Thanks for the quick response, I figured @brian-kelley and you would be the right persons to ask : )

**Comment by lucbv** [comment]
A question and an fyi for you @ndellingwood 
I guess in general it is our policy to run the spot-check tests with the develop branch of kokkos?
And the tests I am doing are in preparation for a PR regarding the cusparse merge algorithm that is needed by Sierra/Aria for their milestone. Should come up today if the alignment problem is fixed!

**Comment by brian-kelley** [comment]
@lucbv @ndellingwood I never saw a misalignment error in GEMV, but hopefully updating Kokkos fixes it. I saw errors in Gauss-Seidel and team dot, and those were fixed in Kokkos PR 3009. That PR is now in master and 3.1.1.

@lucbv If updating Kokkos doesn't fix it, you could do a debug build and run with ``cuda-memcheck --show-backtrace``. That gave me the exact line number in device code where the failing access happened.

**Comment by lucbv** [comment]
OK, I do no see the issue anymore with an up to data kokkos repo. I guess you are both right, @brian-kelley fix in kokkos was probably all that was needed. I will close this issue and open my PR for SpMV merge algorithm.

Thanks!
