### ISSUE TITLE
Support complex_float, complex_double in cuSPARSE SPMV wrapper

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#726]
Follow on to PR #725. Only required steps, hopefully:
Add to ``src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp:100`` these two lines, but checking for complex Kokkos types and then using the ``CUDA_C_xxF`` enums:
```
    if(std::is_same<value_type, float>::value)    {myCudaDataType = CUDA_R_32F;}
    if(std::is_same<value_type, double>::value)   {myCudaDataType = CUDA_R_64F;}
```
Then add the instantiations around line 238.

**Comment by lucbv** [comment]
@brian-kelley thanks for opening this issue, I would actually like to do a few more things, here is my plan:

1. as mentioned above, fix the logic so we can tackle the Kokkos::complex<> case
2. add a parameter validation function so we can check that parameters on the `controls` object are valid and make sense
3. talk with @jjwilke to understand a little better what should be done with `COMPILE_LIBRARY` template parameter
4. I am singularly itching to write the same wrapper for [rocSPARSE](https://github.com/ROCmSoftwarePlatform/rocSPARSE) or [hipSPARSE](https://github.com/ROCmSoftwarePlatform/hipSPARSE)
5. the documentation and performance test need to be tested (@srajama1 this one is for you ; ) )

**Comment by lucbv** [comment]
Regarding point 4, it would actually be good to know if the interface for spmv will adopt the same changes as happened in cusparse `10.3.00` or if it will stick with the older interface?

**Comment by ndellingwood** [comment]
Cross-referencing #771
