### ISSUE TITLE
ETI SpGEMM and Gauss Seidel and take it out of Experimental namespace

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos-kernels#74]
XL compiler is already having issues: https://github.com/kokkos/kokkos-kernels/issues/64

ETI will be necessary to reduce the compile time. 
Also, SpGEMM class includes all features for triangle counting as well as multi-coloring spgemm methods. Separate those for reducing the compile time.

**Comment by srajama1** [comment]
Came from #64 - Are you saying XL compilation time went from 5 hrs to 8 mins before splitting SGS and SpGEMM tests ?

**Comment by crtrott** [comment]
Not quite, 8mins is the actual unit test you have to count the ETI for those function as well. But we did go from 5 hrs to about 15 mins.

**Comment by mndevec** [comment]
Sorry, see my reply to #64. 

8 min is on my workstation, not with XL compilers. The experiment was to see whether splitting test files improves the compile time of ETI'ed kernels. It looks like it does not.

**Comment by srajama1** [comment]
5 hrs -> 15 mins still sounds good :)
