### ISSUE TITLE
SpADD and SpGEMM numerical phases input requirements

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#744]
@srajama1 @brian-kelley @seheracer 
This issue/question follows up on the discussion in PR #743

For some reason both SpADD and SpGEMM are performing the following check:
```c++
static_assert(std::is_same<typename clno_row_view_t_::value_type,
                           typename clno_row_view_t_::value_type>::value,
              "add_symbolic: C size_type must not be const");
```
This suggests that the numerical phase of both algorithms intends to modify the number of entries in the matrix.
Changing the row_map ***after*** the symbolic phase has been performed goes against the idea of a symbolic phase!
Further more this poses problems of interoperability with `Kokkos::StaticCrsGraph` which stores its internal data as follows:
```c++
  typedef View<const size_type*, array_layout, device_type, memory_traits>
      row_map_type;
  typedef View<data_type*, array_layout, device_type, memory_traits>
      entries_type;
  typedef View<const size_type*, array_layout, device_type, memory_traits>
      row_block_type;

  entries_type entries;
  row_map_type row_map;
  row_block_type row_block_offsets;
```
which makes sense since the graph is static hence the last value in row_map must be constant after the graph is constructed.
This will clash when a user tries to call the numerical phase of SpADD or SpGEMM. To go around this issue one needs to do something like:
```c++
using row_map_type = CrsMatrix::row_map_type::non_const_type;

row_map_type newRowMap("new row map", myMatrix.nnumRows() + 1);
Kokkos::deep_copy(newRowMap, myMatrix.graph.row_amp);
```
the problem here is that we are reallocating and doing a deep_copy just to get rid of the constness of the original row map contained in `myMatrix`. 
This looks wrong to me, any thoughts?

**Comment by brian-kelley** [comment]
@lucbv @srajama1 That is definitely not right. I think this is the result of 2 bad copy-pastes:
- The first one copied the checks from spgemm_symbolic to spgemm_numeric (the static_assert message in numeric still says "KokkosSparse::spgemm_symbolic")
- The second was me copying the checks from spgemm numeric to spadd numeric

Neither spgemm nor spadd numeric should change C's rowmap (if they do, it's a bug). I'm making a PR to get rid of those checks. Reuse of the symbolic phase should work in SPGEMM and SPADD. They both assume the graphs of A and B are completely identical between the symbolic call and all numeric calls though (including the order of entries in each row).

**Comment by brian-kelley** [comment]
I opened #745 to fix this

**Comment by lucbv** [comment]
@brian-kelley thanks for checking, for a minute I was worried that something different was going on in these functions and I did not have time to test these yet with the const row_map. This will allow to wrap the symbolic and numeric phases separately with CrsMatrix interface.
I will subsequently open a PR to add a test that multiplies matrices using symbolic and numeric the first time and numeric only afterward.
