### ISSUE TITLE
Make cuSPARSE SPMV support multivectors (rank-2 X/Y)

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#746]
``cusparseSpMV()`` only supports rank-1 vectors, but ``cusparseSpMM()`` supports rank-2. We could use this to provide TPL specializations internally for ``SPMV_MV::spmv``. This will be necessary to use merge-path SPMV on multivectors, although cuSPARSE doesn't support merge path (alg 2) in SpMM yet. So this is very low priority until then.

**Comment by lucbv** [comment]
OK, this sounds like a good idea, I quickly looked at the API and it looks like it will be easy to make that work just like the SpMV.
Thanks for pointing this out @brian-kelley

**Comment by brian-kelley** [comment]
Closing since @cwpearson took care of this last year and it's been released in 3.7.01.
