### ISSUE TITLE
Questions: why are ArithTraits functions not constexpr?

### ISSUE THREAD

**Issue by aprokop** [kokkos/kokkos-kernels#75]
This maybe a stupid question from a novice to C++ 11, but why not? Particularly, `zero()` and `one()`.

**Comment by mhoemmen** [comment]
CUDA hasn't had good support for `constexpr` return values in `__device__` functions.  If that's changed, then we should definitely make those methods `constexpr`.

**Comment by aprokop** [comment]
Has anybody tried `--expt-relaxed-constexpr`? According to [this](http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#constexpr-functions) it may work.

**Comment by mhoemmen** [comment]
It's safe to use `constexpr` return values conditional on `__CUDACC_RELAXED_CONSTEXPR__`.  I'm pretty sure that CUDA will evolve to support this by default, but it would be nice not to _require_ the flag for now.

**Comment by aprokop** [comment]
Thanks @mhoemmen for the discussion. Closing as there is no action to be taken.
