### ISSUE TITLE
cuSPARSE SpGemm compile issue

### ISSUE THREAD

**Issue by euphoricpoptarts** [kokkos/kokkos-kernels#754]
I am trying to use KokkosSparse::Experimental::spgemm_symbolic and numeric with a Cuda default execution space. My code successfully compiles with g++ and an openMP default execution space. However when using the Cuda default execution space and nvcc_wrapper to compile, I get a bunch of different issues. See the below make error log (warning: long):
[err.txt](https://github.com/kokkos/kokkos-kernels/files/4847148/err.txt)

Here is my CMakeLists:
[CMakeLists.txt](https://github.com/kokkos/kokkos-kernels/files/4847157/CMakeLists.txt)

I ran the cmake command as follows:
"cmake -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_TURING75=ON -DKokkos_ENABLE_CUDA_LAMBDA=ON -DCMAKE_CXX_COMPILER=/home/mike/workspace/kokkos/bin/nvcc_wrapper -DKokkos_ENABLE_OPENMP=ON .."

I am using an RTX 2080 Ti with Cuda 10.1, and the OS is Ubuntu 20.04

**Comment by lucbv** [comment]
@euphoricpoptarts thanks for posting this issue.
Let me add a label and mention @seheracer who will be helpful with this.

@srajama1 why are we not using the tpl unification layer for spgemm cusparse?

**Comment by euphoricpoptarts** [comment]
This particular problem is happening when I build with kokkos and kokkos-kernels in-tree with my project (cmake add_subdirectory). When I build kokkos and kokkos-kernels separately and install them, I don't get these compile errors, but I get a much shorter linker error:
[err.txt](https://github.com/kokkos/kokkos-kernels/files/4848061/err.txt)

**Comment by seheracer** [comment]
@lucbv Do you think the problem is not having a tpl unification layer? It looks like a type mismatch to me.

**Comment by lucbv** [comment]
No I do not think that this is related to the tpl unification layer, I just don't remember why it was done this way?
I also agree that it looks like a type error but I am a bit bothered that it is not caught by our testing system so there must be something in the settings that @euphoricpoptarts uses that we miss in our current testing.

**Comment by seheracer** [comment]
@lucbv I'm not sure. If something does not compile, how can you test it as if it was compiled? 


@euphoricpoptarts  Mike, how are you 
i) creating your A and B matrices and
ii) calling the spgemm symbolic function?

**Comment by euphoricpoptarts** [comment]
Well I construct the A and B matrices by creating mirror views of the three views (row_map, entries, values) on the host and deep copying them to the device. Sometimes these matrices are the result of a transpose kernel or the result of spgemm itself. See this file for how I am using it https://github.com/kmadduri/cmg/blob/spgemm_kernel/coarsen_kokkos.h (line 157-244)

**Comment by euphoricpoptarts** [comment]
Oh I realized @seheracer is the only one who can access this file. Here it is for @lucbv or anyone else who wants to see:
[coarsen_kokkos.h.txt](https://github.com/kokkos/kokkos-kernels/files/4848277/coarsen_kokkos.h.txt)

**Comment by seheracer** [comment]
@euphoricpoptarts 
Do you intend to use SPGEMM_KK_SPEED or the cuSPARSE spgemm?

**Comment by euphoricpoptarts** [comment]
I'm not sure which will be better for my use case, so it could be either depending on experimental timing results

**Comment by euphoricpoptarts** [comment]
I was able to get this to compiler and link correctly with nvcc_wrapper and cuda by re-installing Kokkos and kokkos-kernels. This issue appears to be related to building with kokkos and kokkos-kernels in-tree.

**Comment by seheracer** [comment]
@euphoricpoptarts Nice! Glad to hear that there are no issues anymore.
