### ISSUE TITLE
Kokkos::fence called on all execution spaces within KokkosBlas

### ISSUE THREAD

**Issue by stevenrbrill** [kokkos/kokkos-kernels#757]
When building KokkosKernels with multiple execution spaces, specifically Serial and Cuda, `Kokkos::fence()` is called within `KokkosBlas::dot` at https://github.com/kokkos/kokkos-kernels/blob/master/src/blas/KokkosBlas1_dot.hpp#L122 which calls the fence on all executions spaces, not just the execution space for the function. I think this is the same point made in point 2 of this comment on a previous issue https://github.com/kokkos/kokkos/issues/2659#issuecomment-577344565

For completeness of my use case, I'm using KokkosKernels within a Legion application which is throwing an error because `cudaDeviceSynchronize()` is being called outside of a Cuda task.  But I think in general synchronizing all execution spaces would be a performance issue.

**Comment by srajama1** [comment]
@vqd8a @e10harvey : Can one of you look at this please ?

**Comment by e10harvey** [comment]
> @vqd8a @e10harvey : Can one of you look at this please ?

Looking at this now.

> For completeness of my use case, I'm using KokkosKernels within a Legion application which is throwing an error because `cudaDeviceSynchronize()` is being called outside of a Cuda task.

@stevenrbrill: would you share a simple code snippet and build instructions that we can use to reproduce the error you're seeing?

**Comment by stevenrbrill** [comment]
The error occurs in Kokkos_Saxpy example of Legion, which a few minor modifications to enable KokkosKernels, since the cmake process of Legion doesn't use KokkosKernels even though the code is in the example. I can boil it into a simpler example, but since this builds with Legion, I thought making a separate code would only create more steps. The line that causes the problem is https://github.com/StanfordLegion/legion/blob/22714015fe3a1abd89e3141fa7bb04c502b24db8/examples/kokkos_saxpy/kokkos_saxpy.cc#L141 which is just calling `KokkosBlas::dot`. The process to reproduce the Legion error is:

1. Build Kokkos and KokkosKernels with Serial, OpenMP, and Cuda.
2. Pull the master branch of Legion: https://github.com/StanfordLegion/legion/tree/master
3. At https://github.com/StanfordLegion/legion/blob/22714015fe3a1abd89e3141fa7bb04c502b24db8/examples/kokkos_saxpy/CMakeLists.txt#L29 
Add these lines to link KokkosKernels
`find_package(KokkosKernels REQUIRED) `
`target_link_libraries(kokkos_saxpy Kokkos::kokkoskernels)`
4. At https://github.com/StanfordLegion/legion/blob/22714015fe3a1abd89e3141fa7bb04c502b24db8/examples/kokkos_saxpy/kokkos_saxpy.cc#L25
Add the line
`#define USE_KOKKOS_KERNELS`
5. Create a build directory
6. Build legion with examples enabled. The CMake command I use is, where LEGION_ROOT, KOKKOS_DIR, KERNELS_DIR, and KOKKOS_COMPILER need to be set appropriately
.
```
LEGION_ROOT=/home/steven/Documents/Research/legion/kokkos_bug
KOKKOS_DIR=/home/steven/Documents/Research/kokkos/kokkos_gpu/build_all/install/lib/cmake/Kokkos
KERNELS_DIR=/home/steven/Documents/Research/kokkos/kokkos-kernels/build_all/install/lib/cmake/KokkosKernels
KOKKOS_COMPILER=/home/steven/Documents/Research/kokkos/kokkos_gpu/bin/nvcc_wrapper

cmake -DCMAKE_BUILD_TYPE=Release \
      -DLegion_BUILD_EXAMPLES=ON \
      -DCMAKE_CXX_COMPILER="g++" \
      -DCMAKE_INSTALL_PREFIX="$LEGION_ROOT" \
      -DKOKKOS_CXX_COMPILER="$KOKKOS_COMPILER" \
      -DLegion_USE_Kokkos=ON \
      -DCMAKE_CXX_FLAGS="-std=c++11" \
      -DKokkosKernels_DIR="$KERNELS_DIR" \
      -DKokkos_DIR="$KOKKOS_DIR" \
      -DLegion_USE_OpenMP=ON \
      -DLegion_USE_CUDA=ON \
      ..
```

7. Run the example `bin/kokkos_saxpy -ll:ocpu 1 -ll:onuma 0 -ll:gpu 1`

The resulting error is:
```
[0 - 7f33d0b437c0]   57.534044 {6}{cudart}: cudaDeviceSynchronize() called outside CUDA task
kokkos_saxpy: /home/steven/Documents/Research/legion/kokkos_bug/runtime/realm/cuda/cudart_hijack.cc:142: 
Realm::Cuda::GPUProcessor* Realm::Cuda::get_gpu_or_die(const char*): Assertion 'false' failed.
```

**Comment by e10harvey** [comment]
@stevenrbrill: The blocking overload of `dot` being called via `kokkos_saxpy` in Legion allocates a return vector on the host; this is why `dot` fences. Please try [this](https://github.com/kokkos/kokkos-kernels/wiki/BLAS-1%3A%3Adot#interface-single-and-multivector) non-blocking 3 parameter overload of `dot` which allows you to specify the return vector type and reference. I've made a note to update the documentation with respect to which kernels are blocking.

**Comment by streichler** [comment]
@e10harvey the need for a fence when the `dot` runs on the device is understood.  However, if `dot` is run on the host, fencing the device is unnecessary at best and can easily be a performance problem (or a functional problem when using Legion's kokkos interop).

I believe that only execution space that needs to be fenced is the one on which the dot kernel runs, so I'd think something like this ought to be sound and eliminate the potential performance/functional issues:

```
diff --git a/src/blas/KokkosBlas1_dot.hpp b/src/blas/KokkosBlas1_dot.hpp
   //Impl::Dot needs to support both cases, and it's easier to do this with overloading than
   //by extending the ETI to deal with two different scalar types.
   Impl::DotSpecialAccumulator<RVector_Internal,XVector_Internal,YVector_Internal>::dot(R,X,Y);
-  Kokkos::fence();
+  // the implementation uses X's execution space, so that's what we fence
+  typename XVector_Internal::execution_space().fence();
+  //Kokkos::fence();
   // mfh 22 Jan 2020: We need the line below because
   // Kokkos::complex<T> lacks a constructor that takes a
   // Kokkos::complex<U> with U != T.
```

**Comment by e10harvey** [comment]
@streichler: We will look into fencing on a single execution space; we do not want to break other applications use-cases. [This](https://github.com/kokkos/kokkos-kernels/wiki/BLAS-1%3A%3Adot#interface-single-and-multivector) non-blocking overload of `dot` allows the caller to perform the fence.

**Comment by streichler** [comment]
>  [This](https://github.com/kokkos/kokkos-kernels/wiki/BLAS-1%3A%3Adot#interface-single-and-multivector) non-blocking overload of `dot` allows the caller to perform the fence.

I'll take a look at using this in our example for now, but this actually makes the code more fragile I think?  Now the application code has to guess correctly which execution space `dot` is going to use if it wants to perform a precise fence.

**Comment by e10harvey** [comment]
> I'll take a look at using this in our example for now, but this actually makes the code more fragile I think? Now the application code has to guess correctly which execution space `dot` is going to use if it wants to perform a precise fence.

@streichler, good point and thank you for bringing this to our attention. [This](https://github.com/kokkos/kokkos-kernels/wiki/BLAS-1%3A%3Adot#interface-single-and-multivector) non-blocking overload of `dot` also uses VectorX's execution space.

We are looking into adding more overloads for kernels which would allow the caller to specify an execution space more clearly; we also have made a node to update our documentation.
