### ISSUE TITLE
Add CudaUVMSpace specializations for cuBLAS IAMAX and SCAL

### ISSUE THREAD

**Issue by vqd8a** [kokkos/kokkos-kernels#758]
Requested by GEMMA for integrating GEMMA and ADELUS.

**Comment by srajama1** [comment]
Oh man, why do they need UVM when I am trying to remove it in other places.

**Comment by crtrott** [comment]
That's for ETI? Because what else would be the specialization?

**Comment by vqd8a** [comment]
It is for cuBLAS TPL. Kokkos-kernels' IAMAX and SCAL have no CudaUVMSpace specializations when calling cuBLAS TPL.  We only have CudaSpace specializations. For example:

https://github.com/kokkos/kokkos-kernels/blob/ad36ed69f480c47138be9fc1c1b2c47004e29f0f/src/impl/tpls/KokkosBlas1_iamax_tpl_spec_decl.hpp#L524

When CudaUVMSpace is used, the fall-back implementations would be called, which might be slower than cuBLAS.
I did a simple fix in #759 by adding CudaUVMSpace specializations to the TPL files: ```KokkosBlas1_iamax_tpl_spec_decl.hpp```, ```KokkosBlas1_iamax_tpl_spec_avail.hpp```, and ```KokkosBlas1_scal_tpl_spec_decl.hpp```, ```KokkosBlas1_scal_tpl_spec_avail.hpp```

**Comment by crtrott** [comment]
why isn't this type-erased before it this that (i.e. use Device<Cuda,AnonymousSpace>)?

**Comment by vqd8a** [comment]
Does it require re-write the whole TPLs? I just followed what was done in #397 and #399 for GEMM for a quick fix.

**Comment by vqd8a** [comment]
As pointed by @ndellingwood, there is an open issue #144 about AnonymousSpace but it was backlogged. I feel it is somehow beyond the scope of my PR. But should using AnonymousSpace be reprioritized? @srajama1 @crtrott

**Comment by crtrott** [comment]
yeah its fine not to do it in your PR. but generally it might be worthwhile to look at that.

**Comment by vqd8a** [comment]
Thanks @crtrott

**Comment by vqd8a** [comment]
I will look at that.
