### ISSUE TITLE
Dump a `CrsMatrix` to a file

### ISSUE THREAD

**Issue by cartoonist** [kokkos/kokkos-kernels#798]
I am working with a library using kokkos-kernels to generate a `CrsMatrix`. I want to dump the matrix to a file and reload it later instead of recomputing it again. I searched through the documentation and could not find anything. Do you have any suggestion how to serialize a `CrsMatrix` instance to a file?

Thanks in advance.

**Comment by lucbv** [comment]
@cartoonist 
I am not sure what you mean by serialize, as long as you are not storing the CrsMatrix in a distributed formate using MPI or SHMEM all the data should be local on one GPU/CPU memory.
That being said, we do have writers/readers for CrsMatrix data that we use internally for testing purposes located in the file `src/common/KokkosKernels_IOUtils.hpp`. These are only use internally for test purposes so we do not offer much guarantees on their efficacy but they can be helpful.
Let us know if you need more help.

**Comment by brian-kelley** [comment]
@cartoonist If the matrix is not distributed, you can use this to dump it in MatrixMarket format:
```
#include "KokkosKernels_IOUtils.hpp"
...
KokkosKernels::Impl::write_kokkos_crst_matrix(A, "filename.mtx");
```
It can be loaded back in with this:
```
CrsMat A = KokkosKernels::Impl::read_kokkos_crst_matrix<CrsMat>("filename.mtx");
```

**Comment by cartoonist** [comment]
Thanks @lucbv, @brian-kelley. Yes, the matrix is stored locally on one CPU memory and what you suggested is exactly what I was looking for.
