### ISSUE TITLE
cusparse 11 deprecates some spgemm interface

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#803]
@srajama1 @brian-kelley @vbrunini

cuSPARSE 11 is removing some (deprecated?) function calls and those need to be guarded properly in our code base.
For instance: `cusparseXcsrgemmNnz` has disappeared...

**Comment by lucbv** [comment]
PR #804 fixes the build issue but does not provide an implementation for SpGEMM cusparse backend with cuda/11.
Providing the backend for cuda/11 or later will require to rewrite the interface since CrsMatrix are needed to represent A, B and C...

**Comment by ndellingwood** [comment]
I think we'll need this for the 3.7.00 release

**Comment by lucbv** [comment]
FYI, this should have been fixed now, in develop at least and will land in 4.0.0.
I am not sure if it made it for 3.7.1?

**Comment by brian-kelley** [comment]
@lucbv I just checked and neither Junchao's PR (for newest spgemm of cusparse 11.4+) or mine (for 11.0-11.3) made it in to 3.7.1.

**Comment by ndellingwood** [comment]
Correct, for 3.7.01 there were only a couple minor bug fixes that went in and cherry-picks matching changes made directly to Trilinos to avoid clobber

**Comment by lucbv** [comment]
Okay, so I think we can close this now, thanks @brian-kelley and @ndellingwood for tracking this : )
