### ISSUE TITLE
HIP: KokkosBatched::Algo::Level3::Blocked::mb() is not defined for Kokkos::Experimental::HIPSpace

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#808]
Compiling with the HIP backend enabled fails in `src/batched/KokkosBatched_Trsm_Serial_Internal.hpp:97`.
Tracking the missing function definition leads to `KokkosBatched_Util.hpp:267` where the method `mb()` is only defined for `Kokkos::CudaSpace` and `Kokkos::HostSpace`.
We need to add a definition for `Kokkos::Experimental::HIPSpace`.

@kyungjoo-kim is there a logical choice for the return value of mb on HIP? I am tempted to use the same definition as Cuda for the time being but I also worry that if I do that we will forget about it and never revisit this issue...

**Comment by kyungjoo-kim** [comment]
Is there a way that I can access an amd machine and test it compiles ? Is this the only problem with hip ?

**Comment by lucbv** [comment]
I am using caraway to run tests with HIP backend at the moment but the testbed is fairly small, only two gpu nodes.
It's enough to compile and test code though

**Comment by kyungjoo-kim** [comment]
I submitted webcars request for the machine and I will take care of this problem as soon as I have the machine set up. I appreciate if you can let me know the compiler (or any kokkos wrapper) and arch flag (cpu and gpu) for the machine.

**Comment by lucbv** [comment]
I have posted the scripts I am using on the internal repo, you can just rip-it off and it should build fine on caraway.

**Comment by kyungjoo-kim** [comment]
Would you give me a bit more detailed hint about the internal repo ?

**Comment by lucbv** [comment]
Oh, sure, it is here: [https://gitlab-ex.sandia.gov/kokkos-kernels-internal/kokkos-kernels-internal/-/wikis/home](https://gitlab-ex.sandia.gov/kokkos-kernels-internal/kokkos-kernels-internal/-/wikis/home) on the homepage we have a `Technical tips` section and the third link is where I dropped the AMD/HIP build information.
Hopefully it should be straight forward from there, plus access to caraway is probably approved rather quickly.

**Comment by kyungjoo-kim** [comment]
I have a trouble in accessing gitlab-ex from home. I will be in csri tomorrow and will take care of this tmrw.

**Comment by lucbv** [comment]
As an FYI, I did the following and the build proceeds correctly:
```
#if defined(KOKKOS_ENABLE_CUDA)
        template<typename ActiveMemorySpaceType> KOKKOS_INLINE_FUNCTION static constexpr
        typename std::enable_if<std::is_same<ActiveMemorySpaceType,Kokkos::CudaSpace>::value,int>
	::type mb() { return 2; }
#elif defined(KOKKOS_ENABLE_HIP)
        template<typename ActiveMemorySpaceType> KOKKOS_INLINE_FUNCTION static constexpr
        typename std::enable_if<std::is_same<ActiveMemorySpaceType,Kokkos::Experimental::HIPSpace>::value,int>
	::type mb() { return 2; }
#endif
      	template<typename ActiveMemorySpaceType> KOKKOS_INLINE_FUNCTION static constexpr
        typename std::enable_if<std::is_same<ActiveMemorySpaceType,Kokkos::HostSpace>::value,int>
        ::type mb() { return 4; }
```
but of course I have no idea if 2 is the right thing to return here x)

**Comment by kyungjoo-kim** [comment]
That is fine. 2 is unroll factor. If this simple thing can move forward your work, then please include it in your work.

**Comment by kyungjoo-kim** [comment]
BTW, there is no need for ``#elif``. If should be ``#if and #endif`` for each specialization.

**Comment by kyungjoo-kim** [comment]
#812 fixes the problem.

**Comment by kyungjoo-kim** [comment]
closing.

**Comment by lucbv** [comment]
@ndellingwood should we leave this open for release traceability?

**Comment by ndellingwood** [comment]
@lucbv I think it is fine to leave closed (kokkos has begun doing this), since this differs from our past process of waiting for release we should discuss revising the process offline so we are consistent. The changelog generator will track based on issues closed between release tags using the InDevelop label, and going forward I think we may shift to more manual curation of the changelog including PRs (not picked up by the generator) because some important changes get lost in that set of changes. We tried that with Kokkos 3.2 and it wasn't as tedious as it sounds, since the auto changelog requires cleanup anyway.

**Comment by lucbv** [comment]
OK, so I'll do my best to put the `InDevelop` label if that helps with the changelog. Thanks for clarifying this for me : )
