### ISSUE TITLE
Test_Common_ArithTraits bug

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos-kernels#814]
`runAllArithTraitsDeviceTests` and `runAllArithTraitsHostTests` do not catch the last `curSuccess`:
https://github.com/kokkos/kokkos-kernels/blob/0cced12d008ae41fc09bab8ff97e93f082abd72b/test_common/Test_Common_ArithTraits.hpp#L1542-L1545
https://github.com/kokkos/kokkos-kernels/blob/0cced12d008ae41fc09bab8ff97e93f082abd72b/test_common/Test_Common_ArithTraits.hpp#L1613-L1616

**Comment by lucbv** [comment]
Go point, we should really `return success && curSuccess` instead of `return success`.
I guess we could rewrite these files to have the updates to `success` at the end of each line instead of the beginning, that sounds a bit painful though...

**Comment by e10harvey** [comment]
Addressed via https://github.com/e10harvey/kokkos-kernels/commit/b88cb33346e82e705090830fd25e491ae527d058#diff-048d6af83b90aebbfd67728a05acb2f2abbb37ef03e3fc3eec5a70ed1d6f380aR1591 and https://github.com/e10harvey/kokkos-kernels/commit/b88cb33346e82e705090830fd25e491ae527d058#diff-048d6af83b90aebbfd67728a05acb2f2abbb37ef03e3fc3eec5a70ed1d6f380aR1668.
