### ISSUE TITLE
Building kokkos-kernels using hipcc gives an error

### ISSUE THREAD

**Issue by sameershende** [kokkos/kokkos-kernels#830]
Is hipcc supported yet for building for AMD GPUs? I am using:
cmake ..  -DCMAKE_CXX_COMPILER=hipcc -DKokkos_ROOT=<DIR>
make 

[  1%] Building CXX object src/CMakeFiles/kokkoskernels.dir/impl/generated_specializations_cpp/abs/Blas1_abs_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_SERIAL_MEMSPACE_HOSTSPACE.cpp.o
cd /root/kokkos-kernels/build/src && /opt/rocm/bin/hipcc  -DKOKKOS_DEPENDENCE -I/root/kokkos-kernels/build/src -I/root/kokkos-kernels/src -I/root/kokkos-kernels/src/impl -I/root/kokkos-kernels/build/src/impl -I/root/kokkos-kernels/src/impl/tpls -I/root/kokkos-kernels/src/blas -I/root/kokkos-kernels/src/blas/impl -I/root/kokkos-kernels/src/sparse -I/root/kokkos-kernels/src/sparse/impl -I/root/kokkos-kernels/src/graph -I/root/kokkos-kernels/src/graph/impl -I/root/kokkos-kernels/src/batched -I/root/kokkos-kernels/src/common  -fno-gpu-rdc --amdgpu-target=gfx906 -std=gnu++14 -o CMakeFiles/kokkoskernels.dir/impl/generated_specializations_cpp/abs/Blas1_abs_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_SERIAL_MEMSPACE_HOSTSPACE.cpp.o -c /root/kokkos-kernels/build/src/impl/generated_specializations_cpp/abs/Blas1_abs_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_SERIAL_MEMSPACE_HOSTSPACE.cpp
In file included from /root/kokkos-kernels/build/src/impl/generated_specializations_cpp/abs/Blas1_abs_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_SERIAL_MEMSPACE_HOSTSPACE.cpp:48:
In file included from /root/kokkos-kernels/src/blas/impl/KokkosBlas1_abs_spec.hpp:49:
/root/kokkos-kernels/src/Kokkos_ArithTraits.hpp:2929:36: error: call to 'sqrt' is ambiguous
    return static_cast<val_type> ( ::sqrt (static_cast<long double> (abs (x))));
                                   ^~~~~~
/opt/rocm-3.8.0/llvm/lib/clang/11.0.0/include/__clang_cuda_math_forward_declares.h:169:19: note: candidate function
__DEVICE__ double sqrt(double);
                  ^
/opt/rocm-3.8.0/llvm/lib/clang/11.0.0/include/__clang_cuda_math_forward_declares.h:170:18: note: candidate function
__DEVICE__ float sqrt(float);
                 ^

I would appreciate any suggestions. 
Thanks!

**Comment by lucbv** [comment]
@sameershende my only suggestion at the moment is to follow issue #806, I am trying to keep track of our progress on the HIP backend there.
Things are getting better but we are not yet there, if you want to try to use the latest version from the develop branch it will offer more support but not full support.

**Comment by lucbv** [comment]
@sameershende , this issue should be resolved by now, if you still have problems with hip compilation of Kokkos Kernels let us now.
