### ISSUE TITLE
Print Configuration utility

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-kernels#888]
Coming out of the Sierra meeting: it would be nice to have a configuration printer like the Kokkos Core print_configuration, which one can use to figure out what options are enabled in the kokkos kernels my application is linked to. For example for generating meta data when doing performance measurements, or providing debug information.

**Comment by crtrott** [comment]
@lucbv @srajama1

**Comment by srajama1** [comment]
@crtrott Sure we can do it.

**Comment by lucbv** [comment]
Going to close this since we have added that feature with PR #1665 and subsequent PRs to flesh it out.
