### ISSUE TITLE
Serial SpMV fails on Kokkos-dev2 nightly

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#896]
The new serial specialization in Kokkos Kernels fails to compile in our nightly Jenkins build.
The error reported is related to a `memset` call that fails on `Kokkos::complex` see below:

```
03:26:59 /home/jenkins/slave/workspace/KokkosKernels_KokkosDev2_CUDA110_GCC92_cpp17/kokkos-kernels/src/sparse/impl/KokkosSparse_spmv_impl.hpp:344:7: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘using non_const_value_type = using non_const_value_type = using non_const_value_type = using non_const_value_type = std::remove_const<Kokkos::complex<double> >::type’ {aka ‘class Kokkos::complex<double>’}; use assignment or value-initialization instead [-Werror=class-memaccess]
03:26:59   344 |         memset(y_ptr, 0, sizeof(typename YVector::value_type)*nrow);
03:26:59       |       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

should not be to annoying to fix : )

**Comment by kyungjoo-kim** [comment]
umm.... does this only happen on cuda gcc build ? Is it also reproduceable from just gcc serial build ? I am not sure why it complains bout the sizeof(object). It should work but the solution is easy. I will submit an PR for this soon.

**Comment by kyungjoo-kim** [comment]
PR #898

**Comment by lucbv** [comment]
This has now been fixed, thanks @kyungjoo-kim for working in this : )
