### ISSUE TITLE
auto-tester: Add LayoutRight PR test?

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos-kernels#916]
@ndellingwood, @brian-kelley, @lucbv, @vqd8a, @srajama1, @ajpowelsnl: Is anyone interested in a LayoutRight PR test?

**Comment by brian-kelley** [comment]
@e10harvey I think that's a good idea. LayoutRight only builds used to work, but broke over time since we weren't testing it.

**Comment by lucbv** [comment]
Yeah, I concur we should test it to keep from regressing more.

**Comment by e10harvey** [comment]
Depends on #903.
