### ISSUE TITLE
Compiler BUG in IBM XL pragma unrolling

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos-kernels#92]
Jenkins reports IBM XL 14 BETA fails my batched test lately. 

This is the code that incurs the segmentation error.
```
      printf(" I am here yeah\n");
      ValueType
        a_0p, b_p0, c_00 = 0;
      const int
        i0 = 0*_as0,
        j0 = 0*_bs1;
      printf(" loop k: %d\n",k);
#if defined(KOKKOS_ENABLE_PRAGMA_UNROLL)
#pragma unroll
#endif
      for (int p=0;p<k;++p) {
        printf(" p= %d, k= %d, (p<k) = %d\n", p, k, int(p<k) );
        a_0p = A[i0+p*_as1];
        b_p0 = B[p*_bs0+j0];
        c_00 += a_0p * b_p0;
      }
```

This is the output from the above. Without unroll pragma this error disappears.
```
 I am here yeah
 loop k: 1
 p= 0, k= 1, (p<k) = 1
 p= 1, k= 1, (p<k) = 0
 p= 2, k= 1, (p<k) = 0
 p= 3, k= 1, (p<k) = 0
 p= 4, k= 1, (p<k) = 0
 p= 5, k= 1, (p<k) = 0
 p= 6, k= 1, (p<k) = 0
 p= 7, k= 1, (p<k) = 0
 p= 8, k= 1, (p<k) = 0
 p= 9, k= 1, (p<k) = 0
```

An easy fix can be made in Kokkos: disable unroll pragma for IBM compilers
```
#if defined( KOKKOS_COMPILER_IBM )
#define KOKKOS_ENABLE_PRAGMA_UNROLL 1 // disable this
  //#define KOKKOS_ENABLE_PRAGMA_IVDEP 1
  //#define KOKKOS_ENABLE_PRAGMA_LOOPCOUNT 1
  //#define KOKKOS_ENABLE_PRAGMA_VECTOR 1
  //#define KOKKOS_ENABLE_PRAGMA_SIMD 1

  #if ! defined( KOKKOS_ENABLE_ASM )
    #define KOKKOS_ENABLE_ASM 1
  #endif
#endif
```

Actions:

- create a bug branch ibm-unroll-bug to reproduce this (ibm xl 14.1 bet, openmp)
- submit an issue to Kokkos to request to disable unroll pragma for IBM compilers.

**Comment by kyungjoo-kim** [comment]
[https://github.com/kokkos/kokkos-kernels/tree/ibm-unroll-bug](https://github.com/kokkos/kokkos-kernels/tree/ibm-unroll-bug)

**Comment by mhoemmen** [comment]
Just curious -- does removing the `printf` from the loop to unroll have some effect?

**Comment by crtrott** [comment]
No, the code was initially failing with a segfault in the loop. The printf (surprisingly) didn't change the behaviour but demonstrated clearly why ...

**Comment by nmhamster** [comment]
@kyungjoo-kim @srajama1 - new IBM compiler on white (13.1.6). Please can you see if this still has the same problem?
