### ISSUE TITLE
Compiling KokkosKernels without cmake?

### ISSUE THREAD

**Issue by zLi90** [kokkos/kokkos-kernels#950]
Good afternoon!

I have some codes (hydrology model) written with Kokkos and now I am trying to use the pcg solver in KokkosKernels to solve some flow equations. I just got some issues when compiling. It seems my Kokkos and KokkosKernels don't recognize each other. Some typical error messages are:

`/Users/zli2/Codes/kokkos/kokkos-kernels/build/include/generated_specializations_hpp/KokkosBlas1_scal_eti_spec_avail.hpp:48:67: error: no member named 'Serial' in namespace 'Kokkos'
KOKKOSBLAS1_SCAL_ETI_SPEC_AVAIL(double,Kokkos::LayoutLeft,Kokkos::Serial,Kokkos::HostSpace)
/Users/zli2/Codes/kokkos/kokkos-kernels-build/include/KokkosBlas1_scal_spec.hpp:77:54: note: expanded from macro 'KOKKOSBLAS1_SCAL_ETI_SPEC_AVAIL'
        Kokkos::View<SCALAR*, LAYOUT, Kokkos::Device<EXEC_SPACE, MEM_SPACE>, \`

`/Users/zli2/Codes/kokkos/kokkos-kernels-build/include/generated_specializations_hpp/KokkosBlas1_scal_eti_spec_avail.hpp:48:1: error: expected a type
KOKKOSBLAS1_SCAL_ETI_SPEC_AVAIL(double,Kokkos::LayoutLeft,Kokkos::Serial,Kokkos::HostSpace)
/Users/zli2/Codes/kokkos/kokkos-kernels-build/include/KokkosBlas1_scal_spec.hpp:77:76: note: expanded from macro 'KOKKOSBLAS1_SCAL_ETI_SPEC_AVAIL'
        Kokkos::View<SCALAR*, LAYOUT, Kokkos::Device<EXEC_SPACE, MEM_SPACE>, \
`

The following code links Kokkos in our makefile:
`include ${KOKKOS_PATH}/Makefile.kokkos`

To use KokkosKernels, I simply write -I flags to include directories containing the relevant header files, but this doesn't work. I can compile the pcg solver alone with cmake smoothly, just wondering if it would be possible to link KokkosKernels in our existing makefile using something similar to `include ${KOKKOS_PATH}/Makefile.kokkos`?

Thanks!

**Comment by lucbv** [comment]
Let me look at this.
Of course we are strongly recommending to use CMake as what you want could be done very easily in that case.

**Comment by lucbv** [comment]
Yes, configuring netCDF with CMake would be the right thing to do if you want to pick it up using findPackage.
I checked our source code and we do not support makefiles like Kokkos does but I would have guessed that including he library path and the include path include path would have been enough. I will experiment with that a little...

**Comment by zLi90** [comment]
Now I am able to compile my code using cmake, together with kokkoskernels and netcdf. If you have a solution for compiling kokkoskernels without cmake, I'd like to hear. Otherwise we might switch to cmake and this issue can be closed! Thank you so much for the help!

**Comment by srajama1** [comment]
@zLi90 We use to have support for compiling without cmake few years ago, but we have moved away from that. We rely on Cmake fully now. We recommend using Cmake.

**Comment by zLi90** [comment]
Ok we will switch to cmake then. Thanks!
