### ISSUE TITLE
Failing nightly tests failing due to deprecated call

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos-kernels#953]
The Jenkins tests are failing because of a call to a deprecated function.
We should fix that but we should also probably investigate whether the auto-tester should have caught this issue?

**Comment by brian-kelley** [comment]
@lucbv Thanks for taking care of this. I think KokkosKernels just hasn't used ``[[deprecated]]`` until now. Since the autotester builds are pretty strict on warnings (Wall, Wpendantic, etc) it probably makes sense to add Wdeprecated as well. @ndellingwood @e10harvey What do you guys think?

**Comment by lucbv** [comment]
Well we are definitely not strict about unused variables, at least in the tests as we are generating an awful lot of these :p
But yeah we probably want to start tracking the [[deprecated]] warnings in the auto-tester : )

**Comment by e10harvey** [comment]
> @lucbv Thanks for taking care of this. I think KokkosKernels just hasn't used `[[deprecated]]` until now. Since the autotester builds are pretty strict on warnings (Werror, Wall, Wpendantic, etc) it probably makes sense to add Wdeprecated as well. @ndellingwood @e10harvey What do you guys think?

This makes sense to me. It looks like Wdeprecated-declaration is added by clang. I'll see if I can add a clang auto-tester build.
