### ISSUE TITLE
Windows compilation of kokkos-kernels fails because popcount and least_set_bit are not defined

### ISSUE THREAD

**Issue by jrobcary** [kokkos/kokkos-kernels#957]
D:\winsame\cary\vorpalall-dev1\trilinos\packages\kokkos-kernels\src\common\KokkosKernels_BitUtils.hpp(207): fatal error C1189: #error:  "Popcount function is not defined for this compiler. Please report this with the compiler you are using to KokkosKernels."
D:\winsame\cary\vorpalall-dev1\trilinos\packages\kokkos-kernels\src\common\KokkosKernels_IOUtils.hpp(428): error C2664: 'int _stat64i32(const char *,_stat64i32 *)': cannot convert argument 2 from 'stat *' to '_stat64i32 *'

I have these fixed in my fork.  Would like to know how to test before submitting PR.  Assume I should just build.  Do kokkos-kernels build standalone?  Is there a sample cmake invocation somewhere?

**Comment by lucbv** [comment]
@jrobcary we are not testing against windows compilers in our testing.
Can you propose a PR for us to look at while we are looking at how we will test this.
If you can build a release version with ETI, tests and examples on that would be a good place to start.

**Comment by lucbv** [comment]
@ndellingwood @e10harvey
Do you guys know where we could test this?

**Comment by jrobcary** [comment]
I can submit a pull request if you like.  I just hate to waste your time.

**Comment by e10harvey** [comment]
> @ndellingwood @e10harvey
> Do you guys know where we could test this?

This can be tested via github actions: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.

**Comment by ndellingwood** [comment]
Resolved by @jrobcary with PR #981
