### ISSUE TITLE
kokkos-kernels fails to build on Windows: problems with gauss_seidel and atomic_assign

### ISSUE THREAD

**Issue by jrobcary** [kokkos/kokkos-kernels#967]
Using llvm-11.0.  Configured trilionos as per the attached.  Kokkos-kernels errors are

NMAKE : fatal error U1073: don't know how to make 'packages\kokkos-kernels\src\impl\generated_specializations_cpp\gauss_seidel_symbolic\Sparse_gauss_seidel_symbolic_eti_DOUBLE_ORDINAL_INT_OFFSET_INT_LAYOUTLEFT_EXECSPACE_OPENMP_MEMSPACE_HOSTSPACE_MEMSPACE_HOSTSPACE.cpp'
D:\winsame\cary\vorpalall-dev2\trilinos\packages\kokkos-kernels\src\sparse\KokkosSparse_CrsMatrix.hpp(721,19): error: no member named 'atomic_assign' in namespace 'Kokkos'
1 error generated.
(repeated twice more)

This machine had LongPathsEnabled, and so trilinos was configured with -DCMAKE_OBJECT_PATH_MAX=4096 as shown in the configuration script.

Some analysis:

KokkosSparse_CrsMatrix.hpp makes a call to Kokkos::atomic_assign.  "grep -r" shows that Kokkos::atomic_assign is defined in Kokkos_Atomic_Exchange.hpp in various forms.  To make sure it is included, I added 
```
#include <Kokkos_Atomic_Exchange.hpp>
```
at line 61 of KokkosSparse_CrsMatrix.hpp.  The compilation then complained
```
Building CXX object packages/kokkos-kernels/src/CMakeFiles/kokkoskernels.dir/impl/generated_specializations_cpp/sptrsv_solve/Sparse_sptrsv_solve_eti_DOUBLE_ORDINAL_INT_OFFSET_INT_LAYOUTLEFT_EXECSPACE_OPENMP_MEMSPACE_HOSTSPACE.cpp.obj

        cd E:\serllvm\packages\kokkos-kernels\src
        C:\PROGRA~1\LLVM\bin\clang-cl.exe @C:\cygwin64\tmp\nm698A.tmp
In file included from E:\serllvm\packages\kokkos-kernels\src\impl\generated_specializations_cpp\sptrsv_solve\Sparse_sptrsv_solve_eti_DOUBLE_ORDINAL_INT_OFFSET_INT_LAYOUTLEFT_EXECSPACE_OPENMP_MEMSPACE_HOSTSPACE.cpp:47:
In file included from D:\winsame\cary\vorpalall-dev2\trilinos\packages\kokkos-kernels\src\sparse\impl\KokkosSparse_sptrsv_solve_spec.hpp:50:
D:\winsame\cary\vorpalall-dev2\trilinos\packages\kokkos-kernels\src\sparse\KokkosSparse_CrsMatrix.hpp(61,10): fatal error: 'Kokkos_Atomic_Exchange.hpp' file not found
#include <Kokkos_Atomic_Exchange.hpp>
```

so it appears that KokkosSparse_CrsMatrix.hpp is not including a file that it needs.

[grating.txcorp.com-trilinos-ser-config.sh.txt](https://github.com/kokkos/kokkos-kernels/files/6448641/grating.txcorp.com-trilinos-ser-config.sh.txt)

**Comment by ndellingwood** [comment]
Is this related to kokkos/kokkos#4014 ?

**Comment by jrobcary** [comment]
atomic_assign issue fixed in kokkos PR 4029.  The gauss-seidel issue remains.  Will close this issue and open a new one for that.
