### ISSUE TITLE
generate makefile with-spaces option 

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos-kernels#98]
When no memory space is provided to generate makefile, it adds HostSpace and instantiates it. Same way with memkind option.

However, when with-spaces option is used; it overwrites memory spaces. As a result HostSpace is not instantiated. Currently whenever we provide memory space, we need to explicity provide HostSpace to instantiate it. 

It would be better to fix this, even when a memory space is provided without HostSpace, I think it should be instantiated.

**Comment by ndellingwood** [comment]
This was done by @crtrott, SHA cd5d9fb7e in 2017. Marking InDevelop and closing.
