### ISSUE TITLE
Supernodal Sptrsv code coverage

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos-kernels#987]
CC: @iyamazaki 
- [x] Check whether supernodal sptrsv unit-tests can be run without superlu, cholmod, and blas
- [ ] Check whether superlu, cholmod, and blas are available for CI testing:
  - [x] superlu - YES
  - [ ] cholmod - ?
  - [x] blas - YES

**Comment by srajama1** [comment]
@e10harvey : Supernodal sptrsv has to have either SuperLU or Cholmod for running correctly. Otherwise, we won't get the supernodes. However, we could create an artificial supernodal tree just for testing it if we want.

**Comment by e10harvey** [comment]
@iyamazaki: Can an artifical supernodal tree be used for covering the sptrsv code protected by `KOKKOSKERNELS_ENABLE_SUPERNODAL_SPTRSV` ifdef's?

**Comment by iyamazaki** [comment]
Yes. Our current unit-test takes each column as a supernode, and SpTRSV internally constructs the tree (it does not depend on SuuperLU/Cholmod).

**Comment by e10harvey** [comment]
Thank you, @iyamazaki !
